-- Let a city have more than one tape.
--
-- WHAT WAS STOPPING IT: public.soundtracks.city_slug is the PRIMARY KEY, so
-- "one tape per city" was not a convention the admin room chose, it was the
-- database refusing a second row. This gives the table a surrogate key and
-- demotes city_slug to an ordinary foreign key, which is what it always was
-- semantically: a pointer at public.cities.
--
-- WHY A CITY WOULD WANT TWO. The spine phrase is a brief, not a label. "Denver
-- Late Night" and "Denver Rumba Mix" are different tapes that happen to share a
-- city, and merging them into one cassette of thirty songs is not the same
-- product. The prompts were changed on the same day to pick songs for the
-- tape's NAME as well as its city, which is the editorial half of this.
--
-- ============================================================================
-- THE ONE RULE THAT CHANGES MEANING: the do-not-rescrape tombstone.
--
-- The unique index on (city_slug, lower(title), lower(artist)) is what stops the
-- routine ever re-picking a song a human turned down for that city. It moves to
-- (tape_id, ...), so the scope narrows from THE CITY to THE TAPE: a song shelved
-- on "Denver Late Night" can now be proposed for "Denver Rumba Mix".
--
-- That is the correct reading of the new model and it is still a real loss: a
-- song rejected as "no genuine tie to Denver" is wrong for every Denver tape,
-- and the narrower index will let it come back on a sibling. There is no way to
-- have both, because the same index also has to allow a song that legitimately
-- belongs on two tapes in one city. The audit is what catches the first case;
-- see the relevance kind.
-- ============================================================================
--
-- soundtrack_songs.city_slug is KEPT rather than dropped, and is now derived: a
-- trigger holds it equal to its tape's city. Everything that reads songs by city
-- (the public page, soundtrack_issues, the stats view) keeps working untouched,
-- and nothing has to learn about tapes to answer "what plays in Denver".

begin;

-- ---------------------------------------------------------------- the key --
alter table public.soundtracks
  add column if not exists id bigint generated by default as identity;

-- Fill any row that predates the column, then make it the real key. The
-- identity default only covers inserts.
update public.soundtracks set id = default where id is null;

create unique index if not exists soundtracks_id_key on public.soundtracks (id);

-- ------------------------------------------------------------- the tape id --
alter table public.soundtrack_songs
  add column if not exists tape_id bigint;

update public.soundtrack_songs g
   set tape_id = s.id
  from public.soundtracks s
 where s.city_slug = g.city_slug
   and g.tape_id is null;

-- A song whose city has no tape row cannot exist (the old FK guaranteed it), so
-- this is a safety net rather than an expected case.
delete from public.soundtrack_songs where tape_id is null;

alter table public.soundtrack_songs alter column tape_id set not null;

-- ------------------------------------------------------------ swap the keys --
-- EVERY child FK has to go before the parent key it points at, and there were
-- TWO, not one: soundtrack_songs.city_slug and soundtrack_issues.city_slug.
-- Missing the second is what made the first attempt at this migration fail with
--   cannot drop constraint soundtracks_pkey ... soundtrack_issues_city_slug_fkey
--     depends on index soundtracks_pkey
--
-- So rather than name them, find them: any foreign key on any table that points
-- at public.soundtracks is dropped here and re-pointed below. A named list is a
-- list that goes stale the moment a fourth table references tapes.
do $$
declare c record;
begin
  for c in
    select conrelid::regclass as tbl, conname
      from pg_constraint
     where contype = 'f'
       and confrelid = 'public.soundtracks'::regclass
  loop
    execute format('alter table %s drop constraint %I', c.tbl, c.conname);
    raise notice 'dropped FK %.% -> soundtracks', c.tbl, c.conname;
  end loop;
end $$;

alter table public.soundtracks
  drop constraint if exists soundtracks_pkey;

alter table public.soundtracks
  add constraint soundtracks_pkey primary key (id);

-- city_slug stays a foreign key into the city catalogue, exactly as before, and
-- keeps ON UPDATE CASCADE so renaming a city slug still carries its tapes.
alter table public.soundtracks
  drop constraint if exists soundtracks_city_slug_fkey;

alter table public.soundtracks
  add constraint soundtracks_city_slug_fkey
  foreign key (city_slug) references public.cities (slug) on update cascade;

alter table public.soundtrack_songs
  add constraint soundtrack_songs_tape_id_fkey
  foreign key (tape_id) references public.soundtracks (id) on delete cascade;

create index if not exists soundtracks_city_slug_idx
  on public.soundtracks (city_slug);

-- The two city_slug columns that used to point at soundtracks now point at the
-- city catalogue, which is what they always MEANT. They cannot go back to
-- soundtracks: city_slug is no longer unique there, so "denver" no longer names
-- one row. Each keeps ON UPDATE CASCADE so a renamed city slug still carries
-- its songs and its findings, exactly as before.
alter table public.soundtrack_songs
  add constraint soundtrack_songs_city_slug_fkey
  foreign key (city_slug) references public.cities (slug) on update cascade;

alter table public.soundtrack_issues
  add constraint soundtrack_issues_city_slug_fkey
  foreign key (city_slug) references public.cities (slug) on update cascade;

-- ------------------------------------------------- city_slug stays in step --
-- Derived from the tape, never written by a caller. Without this the two could
-- disagree the first time a tape is moved to another city, and the public page
-- would keep showing its songs under the old one.
--
-- IT RESOLVES BOTH WAYS, and the second direction is what keeps the site up
-- through this migration. tgb_pull_soundtrack_songs inserts a song knowing only
-- a city_slug, and tape_id is NOT NULL, so the moment this ran every routine
-- insert would fail until the RPC was rewritten. A caller that names only a city
-- gets that city's tape; a caller that names a tape is authoritative and the
-- city follows from it.
--
-- WHEN A CITY HAS SEVERAL TAPES the oldest wins, which is the honest answer to
-- an ambiguous question rather than a good one: a city-only caller has not said
-- which tape it means, and the first tape is the one that behaved this way
-- before. Every caller should name a tape; this branch exists so nothing BREAKS
-- while they are being changed one at a time, not so they can stay that way.
create or replace function public.tgb_soundtrack_songs_sync_city()
returns trigger
language plpgsql
as $$
begin
  if new.tape_id is not null then
    select s.city_slug into new.city_slug
      from public.soundtracks s
     where s.id = new.tape_id;
  elsif new.city_slug is not null then
    select s.id into new.tape_id
      from public.soundtracks s
     where s.city_slug = new.city_slug
     order by s.created_at, s.id
     limit 1;
    if new.tape_id is null then
      raise exception 'no tape for city %, create one before adding songs to it', new.city_slug;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists soundtrack_songs_sync_city on public.soundtrack_songs;
create trigger soundtrack_songs_sync_city
  before insert or update of tape_id, city_slug on public.soundtrack_songs
  for each row execute function public.tgb_soundtrack_songs_sync_city();

-- And the other direction: a tape that changes city takes its songs with it.
create or replace function public.tgb_soundtracks_sync_song_cities()
returns trigger
language plpgsql
as $$
begin
  if new.city_slug is distinct from old.city_slug then
    update public.soundtrack_songs
       set city_slug = new.city_slug
     where tape_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists soundtracks_sync_song_cities on public.soundtracks;
create trigger soundtracks_sync_song_cities
  after update of city_slug on public.soundtracks
  for each row execute function public.tgb_soundtracks_sync_song_cities();

-- -------------------------------------------------------- the tombstone -----
-- Per tape now, not per city. See the note at the top of this file: this is the
-- one behaviour whose MEANING changes, not just its plumbing.
drop index if exists soundtrack_songs_city_title_artist_key;
drop index if exists public.soundtrack_songs_city_title_artist_key;

create unique index if not exists soundtrack_songs_tape_title_artist_key
  on public.soundtrack_songs (tape_id, lower(btrim(title)), lower(btrim(artist)));

-- Play order is per tape as well.
drop index if exists soundtrack_songs_city_position_idx;
drop index if exists public.soundtrack_songs_city_position_idx;

create index if not exists soundtrack_songs_tape_position_idx
  on public.soundtrack_songs (tape_id, position, id);

-- ----------------------------------------------------------------- stats ----
-- Keyed by tape now. city_slug is still a column, so a caller that wants a
-- whole city sums the rows for it rather than reading one.
-- DROP then CREATE, not CREATE OR REPLACE: replace can only APPEND columns to a
-- view, and tape_id goes in front, so replace fails with "cannot change name of
-- view column". Nothing has a stored dependency on this view; it is read over
-- PostgREST by the Tape Room and the site footer.
drop view if exists public.soundtrack_stats;

create view public.soundtrack_stats as
select
  s.id            as tape_id,
  s.city_slug,
  s.spine_tag,
  s.spine_tag_position,
  s.archived,
  count(g.id) filter (where g.archived is not true)              as active_songs,
  count(g.id) filter (where g.archived is true)                  as archived_songs,
  max(g.created_at)                                              as last_song_at
from public.soundtracks s
left join public.soundtrack_songs g on g.tape_id = s.id
group by s.id, s.city_slug, s.spine_tag, s.spine_tag_position, s.archived;

-- DROP took the grants with it. This view is anon-readable: the site footer
-- counts tapes with active_songs > 0 over it with the publishable key, and so
-- does /soundtracks/. Without this they start returning 401 rather than rows.
grant select on public.soundtrack_stats to anon, authenticated;

-- --------------------------------------------------------------- issues -----
-- An issue can now name the tape it is about. city_slug is left in place and
-- still filled, so nothing that reads issues by city breaks; tape_id is what a
-- reader should prefer once it is populated.
alter table public.soundtrack_issues
  add column if not exists tape_id bigint references public.soundtracks (id) on delete cascade;

update public.soundtrack_issues i
   set tape_id = s.id
  from public.soundtracks s
 where s.city_slug = i.city_slug
   and i.tape_id is null;

create index if not exists soundtrack_issues_tape_idx
  on public.soundtrack_issues (tape_id);

commit;

-- ============================================================================
-- STILL TO DO IN THE APPLICATION, and none of it is safe until this has run:
--
--   * tgb_pull_soundtrack_songs  DONE, in 2026081602, which must be run in the
--     SAME SITTING as this file. Its `on conflict (city_slug)` raises the moment
--     city_slug stops being unique, and it fails at RUN time, so the first sign
--     would be a routine run that inserted nothing.
--   * tgb_report_soundtrack_issues  resolves a city to a tape. It still works
--     unchanged, because soundtrack_issues.tape_id is nullable and city_slug is
--     still filled; a finding just cannot yet say WHICH tape it is about in a
--     city holding two.
--   * /soundtracks/  renders one cassette per city; it must render one per tape.
--   * the Tape Room  keys every row, every write and the city picker on
--     city_slug being unique.
--
-- Written 2026-08-16. NOT APPLIED: remote migration history in this project has
-- drifted (the CLI refuses db push, and nothing since 2026-05 is recorded), so
-- this goes in by hand in the SQL editor like the rest.
