-- Expand every existing initial-form player name (e.g. "A. Johnson") to its
-- full name (e.g. "Andre Johnson") so the two-line nameplate shows a real
-- first name. Matches on (team, current name, number); rows already storing
-- full names are left untouched. Generated from the live jersey_game table.
with name_map(team, abbrev, num, full) as (
  values
  ('Atlanta Falcons', 'A. Crumpler', 83, 'Alge Crumpler'),
  ('Atlanta Falcons', 'C. Chandler', 12, 'Chris Chandler'),
  ('Atlanta Falcons', 'D. Sanders', 21, 'Deion Sanders'),
  ('Atlanta Falcons', 'G. Riggs', 42, 'Gerald Riggs'),
  ('Atlanta Falcons', 'J. Anderson', 32, 'Jamal Anderson'),
  ('Atlanta Falcons', 'J. Jones', 11, 'Julio Jones'),
  ('Atlanta Falcons', 'J. Tuggle', 58, 'Jessie Tuggle'),
  ('Atlanta Falcons', 'M. Andersen', 5, 'Morten Andersen'),
  ('Atlanta Falcons', 'M. Ryan', 2, 'Matt Ryan'),
  ('Atlanta Falcons', 'M. Turner', 33, 'Michael Turner'),
  ('Atlanta Falcons', 'M. Vick', 7, 'Michael Vick'),
  ('Atlanta Falcons', 'S. Bartkowski', 10, 'Steve Bartkowski'),
  ('Atlanta Falcons', 'T. Gonzalez', 88, 'Tony Gonzalez'),
  ('Atlanta Falcons', 'T. Nobis', 60, 'Tommy Nobis'),
  ('Atlanta Falcons', 'W. Dunn', 28, 'Warrick Dunn'),
  ('Boston Celtics', 'B. Cousy', 14, 'Bob Cousy'),
  ('Boston Celtics', 'J. Tatum', 0, 'Jayson Tatum'),
  ('Boston Celtics', 'K. Garnett', 5, 'Kevin Garnett'),
  ('Boston Celtics', 'L. Bird', 33, 'Larry Bird'),
  ('Boston Celtics', 'P. Pierce', 34, 'Paul Pierce'),
  ('Boston Red Sox', 'D. Ortiz', 34, 'David Ortiz'),
  ('Boston Red Sox', 'M. Ramirez', 24, 'Manny Ramirez'),
  ('Boston Red Sox', 'P. Martinez', 45, 'Pedro Martinez'),
  ('Boston Red Sox', 'T. Williams', 9, 'Ted Williams'),
  ('Carolina Panthers', 'C. McCaffrey', 22, 'Christian McCaffrey'),
  ('Carolina Panthers', 'C. Newton', 1, 'Cam Newton'),
  ('Carolina Panthers', 'D. Moore', 12, 'DJ Moore'),
  ('Carolina Panthers', 'D. Williams', 34, 'DeAngelo Williams'),
  ('Carolina Panthers', 'G. Olsen', 88, 'Greg Olsen'),
  ('Carolina Panthers', 'J. Beason', 52, 'Jon Beason'),
  ('Carolina Panthers', 'J. Delhomme', 17, 'Jake Delhomme'),
  ('Carolina Panthers', 'J. Gross', 69, 'Jordan Gross'),
  ('Carolina Panthers', 'J. Peppers', 90, 'Julius Peppers'),
  ('Carolina Panthers', 'L. Kuechly', 59, 'Luke Kuechly'),
  ('Carolina Panthers', 'M. Muhammad', 87, 'Muhsin Muhammad'),
  ('Carolina Panthers', 'S. Mills', 51, 'Sam Mills'),
  ('Carolina Panthers', 'S. Smith', 89, 'Steve Smith'),
  ('Carolina Panthers', 'T. Davis', 58, 'Thomas Davis'),
  ('Chicago Bears', 'B. Urlacher', 54, 'Brian Urlacher'),
  ('Chicago Bears', 'D. Butkus', 51, 'Dick Butkus'),
  ('Chicago Bears', 'D. Hester', 23, 'Devin Hester'),
  ('Chicago Bears', 'M. Ditka', 89, 'Mike Ditka'),
  ('Chicago Bears', 'M. Singletary', 50, 'Mike Singletary'),
  ('Chicago Bears', 'W. Payton', 34, 'Walter Payton'),
  ('Chicago Bulls', 'D. Rose', 1, 'Derrick Rose'),
  ('Chicago Bulls', 'S. Pippen', 33, 'Scottie Pippen'),
  ('Chicago Cubs', 'A. Rizzo', 44, 'Anthony Rizzo'),
  ('Chicago Cubs', 'E. Banks', 14, 'Ernie Banks'),
  ('Chicago Cubs', 'G. Maddux', 31, 'Greg Maddux'),
  ('Chicago Cubs', 'R. Sandberg', 23, 'Ryne Sandberg'),
  ('Chicago Cubs', 'S. Sosa', 21, 'Sammy Sosa'),
  ('Chicago White Sox', 'F. Thomas', 35, 'Frank Thomas'),
  ('Colorado Avalanche', 'J. Sakic', 19, 'Joe Sakic'),
  ('Colorado Avalanche', 'N. MacKinnon', 29, 'Nathan MacKinnon'),
  ('Colorado Avalanche', 'P. Forsberg', 21, 'Peter Forsberg'),
  ('Colorado Avalanche', 'P. Roy', 33, 'Patrick Roy'),
  ('Colorado Rockies', 'C. Blackmon', 19, 'Charlie Blackmon'),
  ('Colorado Rockies', 'C. Gonzalez', 5, 'Carlos Gonzalez'),
  ('Colorado Rockies', 'L. Walker', 33, 'Larry Walker'),
  ('Colorado Rockies', 'N. Arenado', 28, 'Nolan Arenado'),
  ('Colorado Rockies', 'T. Helton', 17, 'Todd Helton'),
  ('Colorado Rockies', 'T. Tulowitzki', 2, 'Troy Tulowitzki'),
  ('Denver Broncos', 'J. Elway', 7, 'John Elway'),
  ('Denver Broncos', 'P. Manning', 18, 'Peyton Manning'),
  ('Denver Nuggets', 'A. English', 2, 'Alex English'),
  ('Denver Nuggets', 'C. Anthony', 15, 'Carmelo Anthony'),
  ('Denver Nuggets', 'D. Issel', 44, 'Dan Issel'),
  ('Denver Nuggets', 'N. Jokic', 15, 'Nikola Jokic'),
  ('Detroit Lions', 'B. Sanders', 20, 'Barry Sanders'),
  ('Detroit Pistons', 'B. Laimbeer', 40, 'Bill Laimbeer'),
  ('Detroit Pistons', 'D. Rodman', 10, 'Dennis Rodman'),
  ('Detroit Pistons', 'I. Thomas', 11, 'Isiah Thomas'),
  ('Detroit Pistons', 'J. Dumars', 4, 'Joe Dumars'),
  ('Detroit Red Wings', 'G. Howe', 9, 'Gordie Howe'),
  ('Detroit Red Wings', 'N. Lidstrom', 5, 'Nicklas Lidstrom'),
  ('Detroit Red Wings', 'P. Datsyuk', 13, 'Pavel Datsyuk'),
  ('Detroit Red Wings', 'S. Yzerman', 19, 'Steve Yzerman'),
  ('Detroit Tigers', 'A. Kaline', 6, 'Al Kaline'),
  ('Detroit Tigers', 'A. Trammell', 3, 'Alan Trammell'),
  ('Detroit Tigers', 'H. Greenberg', 5, 'Hank Greenberg'),
  ('Detroit Tigers', 'J. Verlander', 35, 'Justin Verlander'),
  ('Detroit Tigers', 'L. Whitaker', 1, 'Lou Whitaker'),
  ('Detroit Tigers', 'M. Cabrera', 24, 'Miguel Cabrera'),
  ('Detroit Tigers', 'W. Horton', 23, 'Willie Horton'),
  ('Houston Astros', 'C. Biggio', 7, 'Craig Biggio'),
  ('Houston Astros', 'J. Altuve', 27, 'Jose Altuve'),
  ('Houston Astros', 'J. Bagwell', 5, 'Jeff Bagwell'),
  ('Houston Astros', 'L. Berkman', 17, 'Lance Berkman'),
  ('Houston Astros', 'N. Ryan', 34, 'Nolan Ryan'),
  ('Houston Rockets', 'H. Olajuwon', 34, 'Hakeem Olajuwon'),
  ('Houston Rockets', 'J. Harden', 13, 'James Harden'),
  ('Houston Rockets', 'Y. Ming', 11, 'Yao Ming'),
  ('Houston Texans', 'A. Foster', 23, 'Arian Foster'),
  ('Houston Texans', 'A. Johnson', 80, 'Andre Johnson'),
  ('Houston Texans', 'C. Stroud', 7, 'CJ Stroud'),
  ('Houston Texans', 'D. Hopkins', 10, 'DeAndre Hopkins'),
  ('Houston Texans', 'J. Clowney', 90, 'Jadeveon Clowney'),
  ('Houston Texans', 'M. Schaub', 8, 'Matt Schaub'),
  ('Indiana Pacers', 'G. McGinnis', 30, 'George McGinnis'),
  ('Indiana Pacers', 'P. George', 24, 'Paul George'),
  ('Indiana Pacers', 'R. Miller', 31, 'Reggie Miller'),
  ('Indiana Pacers', 'R. Smits', 45, 'Rik Smits'),
  ('Indianapolis Colts', 'A. Luck', 12, 'Andrew Luck'),
  ('Indianapolis Colts', 'A. Vinatieri', 4, 'Adam Vinatieri'),
  ('Indianapolis Colts', 'B. Sanders', 21, 'Bob Sanders'),
  ('Indianapolis Colts', 'E. James', 32, 'Edgerrin James'),
  ('Indianapolis Colts', 'J. Taylor', 28, 'Jonathan Taylor'),
  ('Indianapolis Colts', 'M. Harrison', 88, 'Marvin Harrison'),
  ('Indianapolis Colts', 'P. Manning', 18, 'Peyton Manning'),
  ('Indianapolis Colts', 'Q. Nelson', 56, 'Quenton Nelson'),
  ('Indianapolis Colts', 'R. Mathis', 98, 'Robert Mathis'),
  ('Indianapolis Colts', 'R. Wayne', 87, 'Reggie Wayne'),
  ('Indianapolis Colts', 'S. Leonard', 53, 'Darius Leonard'),
  ('Jacksonville Jaguars', 'A. Bouye', 21, 'A.J. Bouye'),
  ('Jacksonville Jaguars', 'B. Bortles', 5, 'Blake Bortles'),
  ('Jacksonville Jaguars', 'F. Taylor', 28, 'Fred Taylor'),
  ('Jacksonville Jaguars', 'J. Ramsey', 20, 'Jalen Ramsey'),
  ('Jacksonville Jaguars', 'J. Smith', 82, 'Jimmy Smith'),
  ('Jacksonville Jaguars', 'K. McCardell', 87, 'Keenan McCardell'),
  ('Jacksonville Jaguars', 'M. Brunell', 8, 'Mark Brunell'),
  ('Jacksonville Jaguars', 'M. Jones-Drew', 32, 'Maurice Jones-Drew'),
  ('Jacksonville Jaguars', 'P. Posluszny', 51, 'Paul Posluszny'),
  ('Jacksonville Jaguars', 'R. Mathis', 27, 'Rashean Mathis'),
  ('Jacksonville Jaguars', 'T. Boselli', 71, 'Tony Boselli'),
  ('Jacksonville Jaguars', 'T. Lawrence', 16, 'Trevor Lawrence'),
  ('Los Angeles Angels', 'M. Trout', 27, 'Mike Trout'),
  ('Los Angeles Angels', 'N. Ryan', 30, 'Nolan Ryan'),
  ('Los Angeles Dodgers', 'C. Kershaw', 22, 'Clayton Kershaw'),
  ('Los Angeles Dodgers', 'F. Valenzuela', 34, 'Fernando Valenzuela'),
  ('Los Angeles Dodgers', 'J. Robinson', 42, 'Jackie Robinson'),
  ('Los Angeles Dodgers', 'M. Betts', 50, 'Mookie Betts'),
  ('Los Angeles Lakers', 'K. Abdul-Jabbar', 33, 'Kareem Abdul-Jabbar'),
  ('Los Angeles Lakers', 'K. Bryant', 8, 'Kobe Bryant'),
  ('Los Angeles Lakers', 'K. Bryant', 24, 'Kobe Bryant'),
  ('Los Angeles Lakers', 'L. James', 23, 'LeBron James'),
  ('Los Angeles Lakers', 'M. Johnson', 32, 'Magic Johnson'),
  ('Los Angeles Rams', 'C. Kupp', 10, 'Cooper Kupp'),
  ('Nashville Predators', 'D. Legwand', 11, 'David Legwand'),
  ('Nashville Predators', 'F. Forsberg', 9, 'Filip Forsberg'),
  ('Nashville Predators', 'P. Rinne', 35, 'Pekka Rinne'),
  ('Nashville Predators', 'R. Suter', 20, 'Ryan Suter'),
  ('Nashville Predators', 'S. Weber', 6, 'Shea Weber'),
  ('New England Patriots', 'A. Tippett', 56, 'Andre Tippett'),
  ('New England Patriots', 'A. Vinatieri', 4, 'Adam Vinatieri'),
  ('New England Patriots', 'J. Edelman', 11, 'Julian Edelman'),
  ('New Orleans Saints', 'A. Kamara', 41, 'Alvin Kamara'),
  ('New Orleans Saints', 'B. Hebert', 3, 'Bobby Hebert'),
  ('New Orleans Saints', 'C. Daniel', 10, 'Chase Daniel'),
  ('New Orleans Saints', 'C. Jordan', 94, 'Cameron Jordan'),
  ('New Orleans Saints', 'D. Brees', 9, 'Drew Brees'),
  ('New Orleans Saints', 'D. Hilliard', 21, 'Dalton Hilliard'),
  ('New Orleans Saints', 'G. Hartley', 5, 'Garrett Hartley'),
  ('New Orleans Saints', 'H. Gajan', 46, 'Hokie Gajan'),
  ('New Orleans Saints', 'J. Graham', 80, 'Jimmy Graham'),
  ('New Orleans Saints', 'J. Horn', 87, 'Joe Horn'),
  ('New Orleans Saints', 'K. Turley', 68, 'Kyle Turley'),
  ('New Orleans Saints', 'L. Moore', 16, 'Lance Moore'),
  ('New Orleans Saints', 'M. Andersen', 7, 'Morten Andersen'),
  ('New Orleans Saints', 'M. Colston', 12, 'Marques Colston'),
  ('New Orleans Saints', 'M. Ingram', 22, 'Mark Ingram'),
  ('New Orleans Saints', 'M. Thomas', 13, 'Michael Thomas'),
  ('New Orleans Saints', 'R. Bush', 25, 'Reggie Bush'),
  ('New Orleans Saints', 'S. Mills', 51, 'Sam Mills'),
  ('New Orleans Saints', 'W. Roaf', 77, 'Willie Roaf'),
  ('New York Giants', 'L. Taylor', 56, 'Lawrence Taylor'),
  ('New York Giants', 'M. Strahan', 92, 'Michael Strahan'),
  ('New York Jets', 'D. Maynard', 13, 'Don Maynard'),
  ('New York Jets', 'J. Namath', 12, 'Joe Namath'),
  ('New York Knicks', 'C. Anthony', 7, 'Carmelo Anthony'),
  ('New York Knicks', 'J. Brunson', 11, 'Jalen Brunson'),
  ('New York Knicks', 'P. Ewing', 33, 'Patrick Ewing'),
  ('New York Knicks', 'W. Frazier', 10, 'Walt Frazier'),
  ('New York Mets', 'G. Hodges', 14, 'Gil Hodges'),
  ('New York Mets', 'M. Piazza', 31, 'Mike Piazza'),
  ('New York Yankees', 'A. Judge', 99, 'Aaron Judge'),
  ('New York Yankees', 'D. Jeter', 2, 'Derek Jeter'),
  ('New York Yankees', 'D. Mattingly', 23, 'Don Mattingly'),
  ('New York Yankees', 'M. Rivera', 42, 'Mariano Rivera'),
  ('New York Yankees', 'R. Clemens', 22, 'Roger Clemens'),
  ('Philadelphia 76ers', 'H. Greer', 15, 'Hal Greer'),
  ('Philadelphia 76ers', 'J. Embiid', 21, 'Joel Embiid'),
  ('Philadelphia 76ers', 'J. Erving', 6, 'Julius Erving'),
  ('Philadelphia Eagles', 'B. Dawkins', 20, 'Brian Dawkins'),
  ('Philadelphia Eagles', 'B. Westbrook', 36, 'Brian Westbrook'),
  ('Philadelphia Eagles', 'D. Jackson', 10, 'DeSean Jackson'),
  ('Philadelphia Eagles', 'D. McNabb', 5, 'Donovan McNabb'),
  ('Philadelphia Eagles', 'J. Hurts', 1, 'Jalen Hurts'),
  ('Philadelphia Eagles', 'J. Kelce', 62, 'Jason Kelce'),
  ('Philadelphia Eagles', 'N. Foles', 9, 'Nick Foles'),
  ('Philadelphia Eagles', 'R. Cunningham', 12, 'Randall Cunningham'),
  ('Philadelphia Phillies', 'B. Harper', 3, 'Bryce Harper'),
  ('Philadelphia Phillies', 'C. Utley', 26, 'Chase Utley'),
  ('Philadelphia Phillies', 'R. Howard', 6, 'Ryan Howard'),
  ('Philadelphia Phillies', 'S. Carlton', 32, 'Steve Carlton'),
  ('Tampa Bay Buccaneers', 'B. Mayfield', 6, 'Baker Mayfield'),
  ('Tampa Bay Buccaneers', 'C. Godwin', 14, 'Chris Godwin'),
  ('Tampa Bay Buccaneers', 'H. Nickerson', 56, 'Hardy Nickerson'),
  ('Tampa Bay Buccaneers', 'J. Lynch', 47, 'John Lynch'),
  ('Tampa Bay Buccaneers', 'K. Johnson', 19, 'Keyshawn Johnson'),
  ('Tampa Bay Buccaneers', 'L. David', 54, 'Lavonte David'),
  ('Tampa Bay Buccaneers', 'L. Selmon', 63, 'Lee Roy Selmon'),
  ('Tampa Bay Buccaneers', 'M. Alstott', 40, 'Mike Alstott'),
  ('Tampa Bay Buccaneers', 'M. Evans', 13, 'Mike Evans'),
  ('Tampa Bay Buccaneers', 'M. Gramatica', 7, 'Martin Gramatica'),
  ('Tampa Bay Buccaneers', 'R. Barber', 20, 'Ronde Barber'),
  ('Tampa Bay Buccaneers', 'R. Gronkowski', 87, 'Rob Gronkowski'),
  ('Tampa Bay Buccaneers', 'S. Rice', 97, 'Simeon Rice'),
  ('Tampa Bay Buccaneers', 'T. Brady', 12, 'Tom Brady'),
  ('Tampa Bay Buccaneers', 'V. Jackson', 83, 'Vincent Jackson'),
  ('Tampa Bay Buccaneers', 'W. Dunn', 28, 'Warrick Dunn'),
  ('Tampa Bay Buccaneers', 'W. Sapp', 99, 'Warren Sapp'),
  ('Tennessee Titans', 'D. Henry', 22, 'Derrick Henry'),
  ('Tennessee Titans', 'E. Campbell', 34, 'Earl Campbell'),
  ('Tennessee Titans', 'E. George', 27, 'Eddie George'),
  ('Tennessee Titans', 'F. Wycheck', 89, 'Frank Wycheck'),
  ('Tennessee Titans', 'J. Kearse', 90, 'Jevon Kearse'),
  ('Tennessee Titans', 'K. Byard', 31, 'Kevin Byard'),
  ('Tennessee Titans', 'M. Mariota', 8, 'Marcus Mariota'),
  ('Tennessee Titans', 'R. Tannehill', 17, 'Ryan Tannehill'),
  ('Tennessee Titans', 'S. McNair', 9, 'Steve McNair'),
  ('Tennessee Titans', 'W. Moon', 1, 'Warren Moon')
)
update public.jersey_game j set
  player1name = coalesce(m1.full, j.player1name),
  player2name = coalesce(m2.full, j.player2name),
  player3name = coalesce(m3.full, j.player3name)
from public.jersey_game j2
  left join name_map m1 on m1.team = j2.player1team and m1.abbrev = j2.player1name and m1.num = j2.player1num
  left join name_map m2 on m2.team = j2.player2team and m2.abbrev = j2.player2name and m2.num = j2.player2num
  left join name_map m3 on m3.team = j2.player3team and m3.abbrev = j2.player3name and m3.num = j2.player3num
where j.id = j2.id
  and (m1.full is not null or m2.full is not null or m3.full is not null);
