-- Rewrite boring/templated fandom-game taglines with bespoke,
-- matchup-aware copy (rivalry trash talk + host-city flavor).
-- One guarded UPDATE per game. Idempotent: each fires only while the row
-- still holds its previous tagline, so re-running is a no-op and later manual
-- edits are never clobbered. ASCII punctuation only (no em-dashes).

begin;

update public.games set tagline = $t$Cardinals fans scout the loudest stadium on earth the night before, just to feel at home tomorrow.$t$
  where name = $t$Arizona Fans Takeover Kansas City$t$ and tagline is not distinct from $t$Arizona rolls in a day early for a clue-led run through Kansas City.$t$;
update public.games set tagline = $t$Cardinals fans take the long way to the stadium, straight through the SoFi glow.$t$
  where name = $t$Arizona Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$One night early, Arizona turns Los Angeles into a pregame playground.$t$;
update public.games set tagline = $t$Cardinals fans descend on beignets and brass bands: the home crowd can wait until tomorrow.$t$
  where name = $t$Arizona Fans Takeover New Orleans$t$ and tagline is not distinct from null;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Cardinals fans loose in the bright lights.$t$
  where name = $t$Arizona Fans Takeover New York$t$ and tagline is not distinct from $t$Arizona gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$The NFC West score is open. Cardinals fans start settling it across Silicon Valley.$t$
  where name = $t$Arizona Fans Takeover San Francisco$t$ and tagline is not distinct from $t$Arizona rolls in a day early for a clue-led run through Santa Clara.$t$;
update public.games set tagline = $t$The NFC West score is open. Cardinals fans start settling it across the rain and the roar of the 12s.$t$
  where name = $t$Arizona Fans Takeover Seattle$t$ and tagline is not distinct from $t$Arizona rolls in a day early for a clue-led run through Seattle.$t$;
update public.games set tagline = $t$Division week gets personal: Falcons fans seize NASCAR country before facing the Panthers.$t$
  where name = $t$Atlanta Fans Takeover Carolina$t$ and tagline is not distinct from $t$Atlanta rolls in a day early for a clue-led run through Charlotte.$t$;
update public.games set tagline = $t$Falcons fans answer kickoff with a head start through the Dawg Pound.$t$
  where name = $t$Atlanta Fans Takeover Cleveland$t$ and tagline is not distinct from $t$Atlanta fans, take over Cleveland before kickoff.$t$;
update public.games set tagline = $t$The visitors strike first: Falcons fans light up a tailgate in the cold the night before.$t$
  where name = $t$Atlanta Fans Takeover Green Bay$t$ and tagline is not distinct from $t$Atlanta fans, take over Green Bay before kickoff.$t$;
update public.games set tagline = $t$Passport, jersey, game face: Falcons fans take on the Bernabeu's backyard.$t$
  where name = $t$Atlanta Fans Takeover Madrid$t$ and tagline is not distinct from $t$Atlanta rolls in a day early for a clue-led run through Madrid.$t$;
update public.games set tagline = $t$Falcons fans crash land of ten thousand lakes and make themselves right at home.$t$
  where name = $t$Atlanta Fans Takeover Minnesota$t$ and tagline is not distinct from $t$Atlanta rolls in a day early for a clue-led run through Minneapolis.$t$;
update public.games set tagline = $t$Deep South grudge match: Falcons fans settle the Saints score before the snap.$t$
  where name = $t$Atlanta Fans Takeover New Orleans$t$ and tagline is not distinct from null;
update public.games set tagline = $t$A day early, Falcons fans go looking for trouble in black-and-gold country.$t$
  where name = $t$Atlanta Fans Takeover Pittsburgh$t$ and tagline is not distinct from $t$Atlanta fans, take over Pittsburgh before kickoff.$t$;
update public.games set tagline = $t$The NFC South score is open. Falcons fans start settling it across pirate country.$t$
  where name = $t$Atlanta Fans Takeover Tampa Bay$t$ and tagline is not distinct from $t$Atlanta fans, take over Tampa Bay before kickoff.$t$;
update public.games set tagline = $t$Falcons fans turn the monuments into a tailgate that started a day too early.$t$
  where name = $t$Atlanta Fans Takeover Washington$t$ and tagline is not distinct from $t$Atlanta fans, take over Washington before kickoff.$t$;
update public.games set tagline = $t$The visitors strike first: Ravens fans light up peach-tree streets and trap beats the night before.$t$
  where name = $t$Baltimore Fans Takeover Atlanta$t$ and tagline is not distinct from $t$Baltimore fans, take over Atlanta before kickoff.$t$;
update public.games set tagline = $t$Ravens fans trade home turf for the Orchard Park snow and dare the locals to notice.$t$
  where name = $t$Baltimore Fans Takeover Buffalo$t$ and tagline is not distinct from $t$Baltimore fans, take over Buffalo before kickoff.$t$;
update public.games set tagline = $t$Ravens fans scout the Queen City the night before, just to feel at home tomorrow.$t$
  where name = $t$Baltimore Fans Takeover Carolina$t$ and tagline is not distinct from $t$Baltimore gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$AFC North venom, a day early: Ravens fans turn a bowl of Cincinnati chili into enemy territory.$t$
  where name = $t$Baltimore Fans Takeover Cincinnati$t$ and tagline is not distinct from $t$Baltimore fans, take over Cincinnati before kickoff.$t$;
update public.games set tagline = $t$Ravens fans crash the shores of Lake Erie looking for Browns fans to needle before kickoff.$t$
  where name = $t$Baltimore Fans Takeover Cleveland$t$ and tagline is not distinct from $t$One night early, Baltimore turns Cleveland into a pregame playground.$t$;
update public.games set tagline = $t$Ravens fans scout Space City the night before, just to feel at home tomorrow.$t$
  where name = $t$Baltimore Fans Takeover Houston$t$ and tagline is not distinct from $t$Baltimore rolls in a day early for a clue-led run through Houston.$t$;
update public.games set tagline = $t$Ravens fans answer kickoff with a head start through downtown Indy.$t$
  where name = $t$Baltimore Fans Takeover Indianapolis$t$ and tagline is not distinct from $t$Baltimore fans, take over Indianapolis before kickoff.$t$;
update public.games set tagline = $t$The AFC North's meanest rivalry: Ravens fans settle the Steelers score in the streets first.$t$
  where name = $t$Baltimore Fans Takeover Pittsburgh$t$ and tagline is not distinct from $t$The Game Before The Game$t$;
update public.games set tagline = $t$Passport, jersey, game face: Ravens fans take on samba and sunshine.$t$
  where name = $t$Baltimore Fans Takeover Rio de Janeiro$t$ and tagline is not distinct from $t$One night early, Baltimore turns Rio de Janeiro into a pregame playground.$t$;
update public.games set tagline = $t$Christmas Eve at altitude: Bills fans claim Mile High before the Broncos unwrap a thing.$t$
  where name = $t$Buffalo Fans Takeover Denver$t$ and tagline is not distinct from $t$Something To Do On Christmas Eve In Denver$t$;
update public.games set tagline = $t$Bills fans trade home turf for Titletown and dare the locals to notice.$t$
  where name = $t$Buffalo Fans Takeover Green Bay$t$ and tagline is not distinct from $t$Buffalo rolls in a day early for a clue-led run through Green Bay.$t$;
update public.games set tagline = $t$Bills fans descend on smoked-brisket country: the home crowd can wait until tomorrow.$t$
  where name = $t$Buffalo Fans Takeover Houston$t$ and tagline is not distinct from $t$Buffalo rolls in a day early for a clue-led run through Houston.$t$;
update public.games set tagline = $t$Bills fans bring the away-game energy to Sin City, 24 hours early.$t$
  where name = $t$Buffalo Fans Takeover Las Vegas$t$ and tagline is not distinct from $t$Buffalo gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Bills fans descend on the SoFi glow: the home crowd can wait until tomorrow.$t$
  where name = $t$Buffalo Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$Buffalo gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Bills fans don't wait for kickoff to remind the Dolphins who they are: not in South Beach.$t$
  where name = $t$Buffalo Fans Takeover Miami$t$ and tagline is not distinct from $t$Buffalo fans, take over Miami before kickoff.$t$;
update public.games set tagline = $t$Bills fans descend on land of ten thousand lakes: the home crowd can wait until tomorrow.$t$
  where name = $t$Buffalo Fans Takeover Minnesota$t$ and tagline is not distinct from $t$Buffalo rolls in a day early for a clue-led run through Minneapolis.$t$;
update public.games set tagline = $t$The AFC East throne, contested a day early: Bills fans come for the Patriots.$t$
  where name = $t$Buffalo Fans Takeover New England$t$ and tagline is not distinct from $t$Buffalo rolls in a day early for a clue-led run through Foxborough.$t$;
update public.games set tagline = $t$A day early, Bills fans go looking for trouble in the bright lights.$t$
  where name = $t$Buffalo Fans Takeover New York$t$ and tagline is not distinct from $t$Buffalo gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Division week gets personal: Panthers fans seize the Benz before facing the Falcons.$t$
  where name = $t$Carolina Fans Takeover Atlanta$t$ and tagline is not distinct from $t$One night early, Carolina turns Atlanta into a pregame playground.$t$;
update public.games set tagline = $t$Panthers fans roll into the lakefront chill a full day before kickoff.$t$
  where name = $t$Carolina Fans Takeover Cleveland$t$ and tagline is not distinct from $t$Carolina rolls in a day early for a clue-led run through Cleveland.$t$;
update public.games set tagline = $t$Panthers fans scout a tailgate in the cold the night before, just to feel at home tomorrow.$t$
  where name = $t$Carolina Fans Takeover Green Bay$t$ and tagline is not distinct from $t$Carolina rolls in a day early for a clue-led run through Green Bay.$t$;
update public.games set tagline = $t$the frozen North, but loud and in road colors: Panthers fans arrive early.$t$
  where name = $t$Carolina Fans Takeover Minnesota$t$ and tagline is not distinct from $t$One night early, Carolina turns Minnesota into a pregame playground.$t$;
update public.games set tagline = $t$Panthers fans crash a second-line down the French Quarter looking for Saints fans to needle before kickoff.$t$
  where name = $t$Carolina Fans Takeover New Orleans Too$t$ and tagline is not distinct from null;
update public.games set tagline = $t$Twenty-four hours before kickoff, Panthers fans run the cheesesteak capital.$t$
  where name = $t$Carolina Fans Takeover Philadelphia$t$ and tagline is not distinct from $t$Carolina rolls in a day early for a clue-led run through Philadelphia.$t$;
update public.games set tagline = $t$Panthers fans trade home turf for the Steel City and dare the locals to notice.$t$
  where name = $t$Carolina Fans Takeover Pittsburgh$t$ and tagline is not distinct from $t$Carolina rolls in a day early for a clue-led run through Pittsburgh.$t$;
update public.games set tagline = $t$Two NFC South rivals, one city: Panthers fans get the Gulf beaches first.$t$
  where name = $t$Carolina Fans Takeover Tampa Bay$t$ and tagline is not distinct from $t$One night early, Carolina turns Tampa Bay into a pregame playground.$t$;
update public.games set tagline = $t$First ones in: Bears fans claim the Benz a day ahead of the home side.$t$
  where name = $t$Chicago Fans Takeover Atlanta$t$ and tagline is not distinct from $t$Chicago rolls in a day early for a clue-led run through Atlanta.$t$;
update public.games set tagline = $t$The visitors strike first: Bears fans light up a folding-table tailgate the night before.$t$
  where name = $t$Chicago Fans Takeover Buffalo$t$ and tagline is not distinct from $t$One night early, Chicago turns Buffalo into a pregame playground.$t$;
update public.games set tagline = $t$Bears fans take the long way to the stadium, straight through uptown Charlotte.$t$
  where name = $t$Chicago Fans Takeover Carolina$t$ and tagline is not distinct from $t$Chicago gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Bears fans don't wait for kickoff to remind the Lions who they are: not in Ford Field.$t$
  where name = $t$Chicago Fans Takeover Detroit$t$ and tagline is not distinct from $t$Chicago rolls in a day early for a clue-led run through Detroit.$t$;
update public.games set tagline = $t$The NFC North score is open. Bears fans start settling it across the frozen North.$t$
  where name = $t$Chicago Fans Takeover Minnesota$t$ and tagline is not distinct from $t$One night early, Chicago turns Minnesota into a pregame playground.$t$;
update public.games set tagline = $t$The visitors strike first: Bears fans light up the Space Needle skyline the night before.$t$
  where name = $t$Chicago Fans Takeover Seattle$t$ and tagline is not distinct from $t$Chicago fans, take over Seattle before kickoff.$t$;
update public.games set tagline = $t$Bengals fans answer kickoff with a head start through the ATL.$t$
  where name = $t$Cincinnati Fans Takeover Atlanta$t$ and tagline is not distinct from $t$Cincinnati rolls in a day early for a clue-led run through Atlanta.$t$;
update public.games set tagline = $t$AFC North venom, a day early: Bengals fans turn the Inner Harbor into enemy territory.$t$
  where name = $t$Cincinnati Fans Takeover Baltimore$t$ and tagline is not distinct from $t$Cincinnati rolls in a day early for a clue-led run through Baltimore.$t$;
update public.games set tagline = $t$Bengals fans roll into NASCAR country a full day before kickoff.$t$
  where name = $t$Cincinnati Fans Takeover Carolina$t$ and tagline is not distinct from $t$One night early, Cincinnati turns Carolina into a pregame playground.$t$;
update public.games set tagline = $t$Battle of Ohio: Bengals fans cross the state line to claim it before the Browns even wake up.$t$
  where name = $t$Cincinnati Fans Takeover Cleveland$t$ and tagline is not distinct from $t$Cincinnati gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Bengals fans roll into smoked-brisket country a full day before kickoff.$t$
  where name = $t$Cincinnati Fans Takeover Houston$t$ and tagline is not distinct from $t$Cincinnati gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Game faces on in the Circle City: Bengals fans beat the home crowd to it.$t$
  where name = $t$Cincinnati Fans Takeover Indianapolis$t$ and tagline is not distinct from $t$Cincinnati rolls in a day early for a clue-led run through Indianapolis.$t$;
update public.games set tagline = $t$Kickoff abroad: Bengals fans get the Bernabeu's backyard to themselves first.$t$
  where name = $t$Cincinnati Fans Takeover Madrid$t$ and tagline is not distinct from $t$Cincinnati rolls in a day early for a clue-led run through Madrid.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Bengals fans run South Beach.$t$
  where name = $t$Cincinnati Fans Takeover Miami$t$ and tagline is not distinct from $t$Cincinnati gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Two AFC North rivals, one city: Bengals fans get black-and-gold country first.$t$
  where name = $t$Cincinnati Fans Takeover Pittsburgh$t$ and tagline is not distinct from $t$Cincinnati rolls in a day early for a clue-led run through Pittsburgh.$t$;
update public.games set tagline = $t$Bengals fans descend on the monuments: the home crowd can wait until tomorrow.$t$
  where name = $t$Cincinnati Fans Takeover Washington$t$ and tagline is not distinct from $t$One night early, Cincinnati turns Washington into a pregame playground.$t$;
update public.games set tagline = $t$Browns fans crash the Inner Harbor looking for Ravens fans to needle before kickoff.$t$
  where name = $t$Cleveland Fans Takeover Baltimore$t$ and tagline is not distinct from $t$Cleveland rolls in a day early for a clue-led run through Baltimore.$t$;
update public.games set tagline = $t$Battle of Ohio: Browns fans cross the state line to claim it before the Bengals even wake up.$t$
  where name = $t$Cleveland Fans Takeover Cincinnati$t$ and tagline is not distinct from $t$Cleveland gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Browns fans run the beaches.$t$
  where name = $t$Cleveland Fans Takeover Jacksonville$t$ and tagline is not distinct from $t$Cleveland gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Browns fans scout Bourbon Street the night before, just to feel at home tomorrow.$t$
  where name = $t$Cleveland Fans Takeover New Orleans$t$ and tagline is not distinct from $t$Cleveland rolls in a day early for a clue-led run through New Orleans.$t$;
update public.games set tagline = $t$First ones in: Browns fans claim the bright lights a day ahead of the home side.$t$
  where name = $t$Cleveland Fans Takeover New York$t$ and tagline is not distinct from $t$One night early, Cleveland turns New York into a pregame playground.$t$;
update public.games set tagline = $t$Browns fans hunt down black-and-gold country while the Steelers faithful sleep on it.$t$
  where name = $t$Cleveland Fans Takeover Pittsburgh$t$ and tagline is not distinct from $t$One night early, Cleveland turns Pittsburgh into a pregame playground.$t$;
update public.games set tagline = $t$Browns fans trade home turf for pirate country and dare the locals to notice.$t$
  where name = $t$Cleveland Fans Takeover Tampa Bay$t$ and tagline is not distinct from $t$One night early, Cleveland turns Tampa Bay into a pregame playground.$t$;
update public.games set tagline = $t$Browns fans bring the away-game energy to the honky-tonks of Broadway, 24 hours early.$t$
  where name = $t$Cleveland Fans Takeover Tennessee$t$ and tagline is not distinct from $t$Cleveland rolls in a day early for a clue-led run through Nashville.$t$;
update public.games set tagline = $t$Cowboys fans turn a tailgate in the cold into a tailgate that started a day too early.$t$
  where name = $t$Dallas Fans Takeover Green Bay$t$ and tagline is not distinct from $t$Dallas gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Cowboys fans trade home turf for the Bayou City and dare the locals to notice.$t$
  where name = $t$Dallas Fans Takeover Houston$t$ and tagline is not distinct from $t$Dallas rolls in a day early for a clue-led run through Houston.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Cowboys fans loose in racing country.$t$
  where name = $t$Dallas Fans Takeover Indianapolis$t$ and tagline is not distinct from $t$Dallas gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Cowboys fans trade home turf for sunshine and palm trees and dare the locals to notice.$t$
  where name = $t$Dallas Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$Dallas rolls in a day early for a clue-led run through Inglewood.$t$;
update public.games set tagline = $t$Pregame belongs to the visitors: Cowboys fans own the city that never sleeps for a night.$t$
  where name = $t$Dallas Fans Takeover New York$t$ and tagline is not distinct from $t$Dallas rolls in a day early for a clue-led run through East Rutherford.$t$;
update public.games set tagline = $t$Cowboys-Eagles, the NFC East's ugliest feud: Cowboys fans give no ground.$t$
  where name = $t$Dallas Fans Takeover Philadelphia$t$ and tagline is not distinct from $t$Dallas rolls in a day early for a clue-led run through Philadelphia.$t$;
update public.games set tagline = $t$Neutral turf, road colors: Cowboys fans claim Copacabana the night before.$t$
  where name = $t$Dallas Fans Takeover Rio de Janeiro$t$ and tagline is not distinct from $t$Dallas fans, take over Rio de Janeiro before kickoff.$t$;
update public.games set tagline = $t$Cowboys fans answer kickoff with a head start through the Space Needle skyline.$t$
  where name = $t$Dallas Fans Takeover Seattle$t$ and tagline is not distinct from $t$One night early, Dallas turns Seattle into a pregame playground.$t$;
update public.games set tagline = $t$America's Team meets the Capital: Cowboys fans crash Commanders turf for an NFC East score that never settles.$t$
  where name = $t$Dallas Fans Takeover Washington$t$ and tagline is not distinct from $t$Dallas fans, take over Washington before kickoff.$t$;
update public.games set tagline = $t$Game faces on in cactus country: Broncos fans beat the home crowd to it.$t$
  where name = $t$Denver Fans Takeover Arizona$t$ and tagline is not distinct from $t$Denver gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Broncos fans trade home turf for the Queen City and dare the locals to notice.$t$
  where name = $t$Denver Fans Takeover Carolina$t$ and tagline is not distinct from $t$One night early, Denver turns Carolina into a pregame playground.$t$;
update public.games set tagline = $t$Broncos fans bring the AFC West bad blood to burnt ends and BBQ smoke. Let the trash talk begin.$t$
  where name = $t$Denver Fans Takeover Kansas City$t$ and tagline is not distinct from $t$One night early, Denver turns Kansas City into a pregame playground.$t$;
update public.games set tagline = $t$The AFC West's oldest argument picks back up: Broncos fans stake out Raiders turf.$t$
  where name = $t$Denver Fans Takeover Las Vegas$t$ and tagline is not distinct from $t$Denver fans, take over Las Vegas before kickoff.$t$;
update public.games set tagline = $t$Broncos fans trade home turf for Hollywood and dare the locals to notice.$t$
  where name = $t$Denver Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$Denver fans, take over Los Angeles before kickoff.$t$;
update public.games set tagline = $t$Broncos fans bring the away-game energy to Patriot Place, 24 hours early.$t$
  where name = $t$Denver Fans Takeover New England$t$ and tagline is not distinct from $t$Denver rolls in a day early for a clue-led run through Foxborough.$t$;
update public.games set tagline = $t$Pregame belongs to the visitors: Broncos fans own Times Square for a night.$t$
  where name = $t$Denver Fans Takeover New York$t$ and tagline is not distinct from $t$Denver fans, take over New York before kickoff.$t$;
update public.games set tagline = $t$First ones in: Broncos fans claim three rivers and a sea of Terrible Towels a day ahead of the home side.$t$
  where name = $t$Denver Fans Takeover Pittsburgh$t$ and tagline is not distinct from $t$Denver fans, take over Pittsburgh before kickoff.$t$;
update public.games set tagline = $t$Broncos fans descend on the fog and the Golden Gate: the home crowd can wait until tomorrow.$t$
  where name = $t$Denver Fans Takeover San Francisco$t$ and tagline is not distinct from $t$Denver fans, take over San Francisco before kickoff.$t$;
update public.games set tagline = $t$Lions fans descend on the Valley of the Sun: the home crowd can wait until tomorrow.$t$
  where name = $t$Detroit Fans Takeover Arizona$t$ and tagline is not distinct from $t$Detroit rolls in a day early for a clue-led run through Glendale.$t$;
update public.games set tagline = $t$Lions fans trade home turf for the Benz and dare the locals to notice.$t$
  where name = $t$Detroit Fans Takeover Atlanta$t$ and tagline is not distinct from $t$Detroit rolls in a day early for a clue-led run through Atlanta.$t$;
update public.games set tagline = $t$Lions fans roll into a folding-table tailgate a full day before kickoff.$t$
  where name = $t$Detroit Fans Takeover Buffalo$t$ and tagline is not distinct from $t$Detroit rolls in a day early for a clue-led run through Orchard Park.$t$;
update public.games set tagline = $t$Lions fans hunt clues across uptown Charlotte while the home side sleeps.$t$
  where name = $t$Detroit Fans Takeover Carolina$t$ and tagline is not distinct from $t$Detroit rolls in a day early for a clue-led run through Charlotte.$t$;
update public.games set tagline = $t$Lions fans don't wait for kickoff to remind the Bears who they are: not in the lakefront.$t$
  where name = $t$Detroit Fans Takeover Chicago$t$ and tagline is not distinct from $t$Detroit fans, take over Chicago before kickoff.$t$;
update public.games set tagline = $t$Division week gets personal: Lions fans seize Titletown before facing the Packers.$t$
  where name = $t$Detroit Fans Takeover Green Bay$t$ and tagline is not distinct from $t$Detroit rolls in a day early for a clue-led run through Green Bay.$t$;
update public.games set tagline = $t$First ones in: Lions fans claim the neon and palm trees a day ahead of the home side.$t$
  where name = $t$Detroit Fans Takeover Miami$t$ and tagline is not distinct from $t$Detroit gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Lions fans pick the fight early, claiming the frozen North from Vikings country.$t$
  where name = $t$Detroit Fans Takeover Minnesota$t$ and tagline is not distinct from $t$Detroit rolls in a day early for a clue-led run through Minneapolis.$t$;
update public.games set tagline = $t$Lions fans take the fight overseas: beer-hall country, the day before kickoff.$t$
  where name = $t$Detroit Fans Takeover Munich$t$ and tagline is not distinct from $t$Detroit fans, take over Munich before kickoff.$t$;
update public.games set tagline = $t$The NFL's oldest grudge, a new chapter: Packers fans invade Bears country in the cold.$t$
  where name = $t$Green Bay Fans Takeover Chicago$t$ and tagline is not distinct from $t$Green Bay gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Division week gets personal: Packers fans seize Motown before facing the Lions.$t$
  where name = $t$Green Bay Fans Takeover Detroit$t$ and tagline is not distinct from $t$One night early, Green Bay turns Detroit into a pregame playground.$t$;
update public.games set tagline = $t$Packers fans scout Hollywood the night before, just to feel at home tomorrow.$t$
  where name = $t$Green Bay Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$Green Bay fans, take over Los Angeles before kickoff.$t$;
update public.games set tagline = $t$Border battle. Packers fans drag the Black-and-Blue fight onto Vikings turf.$t$
  where name = $t$Green Bay Fans Takeover Minnesota$t$ and tagline is not distinct from $t$Green Bay rolls in a day early for a clue-led run through Minneapolis.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Packers fans run Patriot Place.$t$
  where name = $t$Green Bay Fans Takeover New England$t$ and tagline is not distinct from $t$One night early, Green Bay turns New England into a pregame playground.$t$;
update public.games set tagline = $t$Cheeseheads on Bourbon Street: the Packers' Super Bowl city becomes Titletown South for a night.$t$
  where name = $t$Green Bay Fans Takeover New Orleans$t$ and tagline is not distinct from $t$Fun in the Super Bowl XXXI Host City$t$;
update public.games set tagline = $t$Game faces on in Times Square: Packers fans beat the home crowd to it.$t$
  where name = $t$Green Bay Fans Takeover New York$t$ and tagline is not distinct from $t$Green Bay rolls in a day early for a clue-led run through East Rutherford.$t$;
update public.games set tagline = $t$Packers fans take the long way to the stadium, straight through the bay.$t$
  where name = $t$Green Bay Fans Takeover Tampa Bay$t$ and tagline is not distinct from $t$Green Bay rolls in a day early for a clue-led run through Tampa.$t$;
update public.games set tagline = $t$Texans fans roll into the lakefront chill a full day before kickoff.$t$
  where name = $t$Houston Fans Takeover Cleveland$t$ and tagline is not distinct from $t$Houston fans, take over Cleveland before kickoff.$t$;
update public.games set tagline = $t$Texans fans scout cheesehead country the night before, just to feel at home tomorrow.$t$
  where name = $t$Houston Fans Takeover Green Bay$t$ and tagline is not distinct from $t$Houston fans, take over Green Bay before kickoff.$t$;
update public.games set tagline = $t$Old AFC South blood: Texans fans take racing country the night before they meet the Colts.$t$
  where name = $t$Houston Fans Takeover Indianapolis$t$ and tagline is not distinct from $t$Houston fans, take over Indianapolis before kickoff.$t$;
update public.games set tagline = $t$Neutral turf, road colors: Texans fans claim across the pond the night before.$t$
  where name = $t$Houston Fans Takeover London$t$ and tagline is not distinct from $t$Houston fans, take over London before kickoff.$t$;
update public.games set tagline = $t$sunshine and palm trees, but loud and in road colors: Texans fans arrive early.$t$
  where name = $t$Houston Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$Houston fans, take over Los Angeles before kickoff.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Texans fans run the cheesesteak capital.$t$
  where name = $t$Houston Fans Takeover Philadelphia$t$ and tagline is not distinct from $t$Houston gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Texans fans trade home turf for the Steel City and dare the locals to notice.$t$
  where name = $t$Houston Fans Takeover Pittsburgh$t$ and tagline is not distinct from $t$One night early, Houston turns Pittsburgh into a pregame playground.$t$;
update public.games set tagline = $t$Texans fans don't wait for kickoff to remind the Titans who they are: not in Nashville neon.$t$
  where name = $t$Houston Fans Takeover Tennessee$t$ and tagline is not distinct from $t$One night early, Houston turns Tennessee into a pregame playground.$t$;
update public.games set tagline = $t$Texans fans bring the away-game energy to D.C., 24 hours early.$t$
  where name = $t$Houston Fans Takeover Washington$t$ and tagline is not distinct from $t$One night early, Houston turns Washington into a pregame playground.$t$;
update public.games set tagline = $t$Game faces on in the Dawg Pound: Colts fans beat the home crowd to it.$t$
  where name = $t$Indianapolis Fans Takeover Cleveland$t$ and tagline is not distinct from $t$Indianapolis fans, take over Cleveland before kickoff.$t$;
update public.games set tagline = $t$Old AFC South blood: Colts fans take smoked-brisket country the night before they meet the Texans.$t$
  where name = $t$Indianapolis Fans Takeover Houston$t$ and tagline is not distinct from $t$One night early, Indianapolis turns Houston into a pregame playground.$t$;
update public.games set tagline = $t$Colts fans don't wait for kickoff to remind the Jaguars who they are: not in the beaches.$t$
  where name = $t$Indianapolis Fans Takeover Jacksonville$t$ and tagline is not distinct from $t$Indianapolis rolls in a day early for a clue-led run through Jacksonville.$t$;
update public.games set tagline = $t$Colts fans take the long way to the stadium, straight through the loudest stadium on earth.$t$
  where name = $t$Indianapolis Fans Takeover Kansas City$t$ and tagline is not distinct from $t$Indianapolis rolls in a day early for a clue-led run through Kansas City.$t$;
update public.games set tagline = $t$Colts fans go global, running Wembley before the whistle.$t$
  where name = $t$Indianapolis Fans Takeover London$t$ and tagline is not distinct from $t$Indianapolis rolls in a day early for a clue-led run through London.$t$;
update public.games set tagline = $t$Colts fans turn land of ten thousand lakes into a tailgate that started a day too early.$t$
  where name = $t$Indianapolis Fans Takeover Minnesota$t$ and tagline is not distinct from $t$Indianapolis gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Colts fans take the long way to the stadium, straight through the Rocky steps.$t$
  where name = $t$Indianapolis Fans Takeover Philadelphia$t$ and tagline is not distinct from $t$Indianapolis rolls in a day early for a clue-led run through Philadelphia.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Colts fans loose in black-and-gold country.$t$
  where name = $t$Indianapolis Fans Takeover Pittsburgh$t$ and tagline is not distinct from $t$Indianapolis rolls in a day early for a clue-led run through Pittsburgh.$t$;
update public.games set tagline = $t$AFC South bad blood with a head start: Colts fans crash Titans turf.$t$
  where name = $t$Indianapolis Fans Takeover Tennessee$t$ and tagline is not distinct from $t$Indianapolis rolls in a day early for a clue-led run through Nashville.$t$;
update public.games set tagline = $t$Pregame belongs to the visitors: Jaguars fans own Charm City for a night.$t$
  where name = $t$Jacksonville Fans Takeover Baltimore$t$ and tagline is not distinct from $t$Jacksonville fans, take over Baltimore before kickoff.$t$;
update public.games set tagline = $t$Jaguars fans hunt clues across the lakefront while the home side sleeps.$t$
  where name = $t$Jacksonville Fans Takeover Chicago$t$ and tagline is not distinct from $t$Jacksonville fans, take over Chicago before kickoff.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Jaguars fans run the Jungle.$t$
  where name = $t$Jacksonville Fans Takeover Cincinnati$t$ and tagline is not distinct from $t$Jacksonville fans, take over Cincinnati before kickoff.$t$;
update public.games set tagline = $t$Texas-sized everything, but loud and in road colors: Jaguars fans arrive early.$t$
  where name = $t$Jacksonville Fans Takeover Dallas$t$ and tagline is not distinct from $t$One night early, Jacksonville turns Dallas into a pregame playground.$t$;
update public.games set tagline = $t$Mile High, but loud and in road colors: Jaguars fans arrive early.$t$
  where name = $t$Jacksonville Fans Takeover Denver$t$ and tagline is not distinct from $t$Jacksonville fans, take over Denver before kickoff.$t$;
update public.games set tagline = $t$The AFC South score is open. Jaguars fans start settling it across the Bayou City.$t$
  where name = $t$Jacksonville Fans Takeover Houston$t$ and tagline is not distinct from $t$Jacksonville fans, take over Houston before kickoff.$t$;
update public.games set tagline = $t$Jaguars fans don't wait for kickoff to remind the Colts who they are: not in racing country.$t$
  where name = $t$Jacksonville Fans Takeover Indianapolis$t$ and tagline is not distinct from $t$Jacksonville rolls in a day early for a clue-led run through Indianapolis.$t$;
update public.games set tagline = $t$Jaguars fans take the fight overseas: across the pond, the day before kickoff.$t$
  where name = $t$Jacksonville Fans Takeover London$t$ and tagline is not distinct from $t$Jacksonville gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Jaguars fans roll into the city that never sleeps a full day before kickoff.$t$
  where name = $t$Jacksonville Fans Takeover New York$t$ and tagline is not distinct from $t$One night early, Jacksonville turns New York into a pregame playground.$t$;
update public.games set tagline = $t$Jaguars vs Titans again. The AFC South's nastiest feud spills into Nashville neon.$t$
  where name = $t$Jacksonville Fans Takeover Tennessee$t$ and tagline is not distinct from $t$Jacksonville gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Chiefs fans descend on peach-tree streets and trap beats: the home crowd can wait until tomorrow.$t$
  where name = $t$Kansas City Fans Takeover Atlanta$t$ and tagline is not distinct from $t$Kansas City fans, take over Atlanta before kickoff.$t$;
update public.games set tagline = $t$Chiefs fans bring the away-game energy to the Orchard Park snow, 24 hours early.$t$
  where name = $t$Kansas City Fans Takeover Buffalo$t$ and tagline is not distinct from $t$Kansas City fans, take over Buffalo before kickoff.$t$;
update public.games set tagline = $t$a bowl of Cincinnati chili, but loud and in road colors: Chiefs fans arrive early.$t$
  where name = $t$Kansas City Fans Takeover Cincinnati$t$ and tagline is not distinct from $t$One night early, Kansas City turns Cincinnati into a pregame playground.$t$;
update public.games set tagline = $t$Chiefs fans bring the AFC West bad blood to the thin mountain air. Let the trash talk begin.$t$
  where name = $t$Kansas City Fans Takeover Denver$t$ and tagline is not distinct from $t$Kansas City gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Chiefs-Raiders, decades of AFC West hate: Chiefs fans reignite it a day early.$t$
  where name = $t$Kansas City Fans Takeover Las Vegas$t$ and tagline is not distinct from $t$Kansas City gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Chiefs fans run Hollywood.$t$
  where name = $t$Kansas City Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$Kansas City rolls in a day early for a clue-led run through Inglewood.$t$;
update public.games set tagline = $t$Chiefs fans answer kickoff with a head start through Calle Ocho.$t$
  where name = $t$Kansas City Fans Takeover Miami$t$ and tagline is not distinct from $t$Kansas City fans, take over Miami before kickoff.$t$;
update public.games set tagline = $t$Chiefs fans bring the away-game energy to the Emerald City, 24 hours early.$t$
  where name = $t$Kansas City Fans Takeover Seattle$t$ and tagline is not distinct from $t$Kansas City fans, take over Seattle before kickoff.$t$;
update public.games set tagline = $t$Raiders fans scout cactus country the night before, just to feel at home tomorrow.$t$
  where name = $t$Las Vegas Fans Takeover Arizona$t$ and tagline is not distinct from $t$Las Vegas gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$the shores of Lake Erie, but loud and in road colors: Raiders fans arrive early.$t$
  where name = $t$Las Vegas Fans Takeover Cleveland$t$ and tagline is not distinct from $t$Las Vegas gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$The AFC West's oldest argument picks back up: Raiders fans stake out Broncos turf.$t$
  where name = $t$Las Vegas Fans Takeover Denver$t$ and tagline is not distinct from $t$Las Vegas rolls in a day early for a clue-led run through Denver.$t$;
update public.games set tagline = $t$Chiefs-Raiders, decades of AFC West hate: Raiders fans reignite it a day early.$t$
  where name = $t$Las Vegas Fans Takeover Kansas City$t$ and tagline is not distinct from $t$Las Vegas gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Raiders fans run Hollywood.$t$
  where name = $t$Las Vegas Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$One night early, Las Vegas turns Los Angeles into a pregame playground.$t$;
update public.games set tagline = $t$Game faces on in Patriot Place: Raiders fans beat the home crowd to it.$t$
  where name = $t$Las Vegas Fans Takeover New England$t$ and tagline is not distinct from $t$Las Vegas gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Raiders fans trade home turf for Times Square and dare the locals to notice.$t$
  where name = $t$Las Vegas Fans Takeover New York$t$ and tagline is not distinct from $t$Las Vegas gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Raiders fans loose in the fog and the Golden Gate.$t$
  where name = $t$Las Vegas Fans Takeover San Francisco$t$ and tagline is not distinct from $t$Las Vegas rolls in a day early for a clue-led run through Santa Clara.$t$;
update public.games set tagline = $t$Old NFC West blood: Rams fans take the Valley of the Sun the night before they meet the Cardinals.$t$
  where name = $t$Los Angeles Fans Takeover Arizona$t$ and tagline is not distinct from $t$One night early, Los Angeles turns Arizona into a pregame playground.$t$;
update public.games set tagline = $t$Chargers fans scout Charm City the night before, just to feel at home tomorrow.$t$
  where name = $t$Los Angeles Fans Takeover Baltimore$t$ and tagline is not distinct from $t$Los Angeles gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Chargers fans descend on a folding-table tailgate: the home crowd can wait until tomorrow.$t$
  where name = $t$Los Angeles Fans Takeover Buffalo$t$ and tagline is not distinct from $t$Los Angeles fans, take over Buffalo before kickoff.$t$;
update public.games set tagline = $t$Rams fans trade home turf for Mile High and dare the locals to notice.$t$
  where name = $t$Los Angeles Fans Takeover Denver$t$ and tagline is not distinct from $t$One night early, Los Angeles turns Denver into a pregame playground.$t$;
update public.games set tagline = $t$Chargers vs Chiefs again. The AFC West's nastiest feud spills into Arrowhead.$t$
  where name = $t$Los Angeles Fans Takeover Kansas City$t$ and tagline is not distinct from $t$Los Angeles fans, take over Kansas City before kickoff.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Rams fans run the Strip.$t$
  where name = $t$Los Angeles Fans Takeover Las Vegas$t$ and tagline is not distinct from $t$One night early, Los Angeles turns Las Vegas into a pregame playground.$t$;
update public.games set tagline = $t$Chargers fans answer kickoff with a head start through sunshine and palm trees.$t$
  where name = $t$Los Angeles Fans Takeover Los Angeles?!$t$ and tagline is not distinct from $t$One night early, Los Angeles turns Los Angeles into a pregame playground.$t$;
update public.games set tagline = $t$Passport, jersey, game face: Rams fans take on the land of Oz.$t$
  where name = $t$Los Angeles Fans Takeover Melbourne$t$ and tagline is not distinct from $t$Los Angeles gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$A day early, Chargers fans go looking for trouble in the neon and palm trees.$t$
  where name = $t$Los Angeles Fans Takeover Miami$t$ and tagline is not distinct from $t$Los Angeles fans, take over Miami before kickoff.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Rams fans run the cheesesteak capital.$t$
  where name = $t$Los Angeles Fans Takeover Philadelphia$t$ and tagline is not distinct from $t$Los Angeles fans, take over Philadelphia before kickoff.$t$;
update public.games set tagline = $t$Rams fans crash the Bay looking for 49ers fans to needle before kickoff.$t$
  where name = $t$Los Angeles Fans Takeover San Francisco$t$ and tagline is not distinct from $t$Los Angeles fans, take over San Francisco before kickoff.$t$;
update public.games set tagline = $t$Chargers fans descend on the Space Needle skyline: the home crowd can wait until tomorrow.$t$
  where name = $t$Los Angeles Fans Takeover Seattle$t$ and tagline is not distinct from $t$One night early, Los Angeles turns Seattle into a pregame playground.$t$;
update public.games set tagline = $t$Chargers fans roll into the Gulf beaches a full day before kickoff.$t$
  where name = $t$Los Angeles Fans Takeover Tampa Bay$t$ and tagline is not distinct from $t$One night early, Los Angeles turns Tampa Bay into a pregame playground.$t$;
update public.games set tagline = $t$Rams fans bring the away-game energy to D.C., 24 hours early.$t$
  where name = $t$Los Angeles Fans Takeover Washington$t$ and tagline is not distinct from $t$Los Angeles gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Dolphins fans don't wait for kickoff to remind the Bills who they are: not in wing country.$t$
  where name = $t$Miami Fans Takeover Buffalo$t$ and tagline is not distinct from $t$One night early, Miami turns Buffalo into a pregame playground.$t$;
update public.games set tagline = $t$the shadow of the Rockies, but loud and in road colors: Dolphins fans arrive early.$t$
  where name = $t$Miami Fans Takeover Denver$t$ and tagline is not distinct from $t$Miami fans, take over Denver before kickoff.$t$;
update public.games set tagline = $t$Pregame belongs to the visitors: Dolphins fans own a tailgate in the cold for a night.$t$
  where name = $t$Miami Fans Takeover Green Bay$t$ and tagline is not distinct from $t$Miami fans, take over Green Bay before kickoff.$t$;
update public.games set tagline = $t$Dolphins fans scout the Circle City the night before, just to feel at home tomorrow.$t$
  where name = $t$Miami Fans Takeover Indianapolis$t$ and tagline is not distinct from $t$One night early, Miami turns Indianapolis into a pregame playground.$t$;
update public.games set tagline = $t$Dolphins fans answer kickoff with a head start through Sin City.$t$
  where name = $t$Miami Fans Takeover Las Vegas$t$ and tagline is not distinct from $t$Miami fans, take over Las Vegas before kickoff.$t$;
update public.games set tagline = $t$A day early, Dolphins fans go looking for trouble in land of ten thousand lakes.$t$
  where name = $t$Miami Fans Takeover Minnesota$t$ and tagline is not distinct from $t$Miami fans, take over Minnesota before kickoff.$t$;
update public.games set tagline = $t$Two AFC East rivals, one city: Dolphins fans get Gillette first.$t$
  where name = $t$Miami Fans Takeover New England$t$ and tagline is not distinct from $t$Miami rolls in a day early for a clue-led run through Foxborough.$t$;
update public.games set tagline = $t$Dolphins fans roll into the bright lights a full day before kickoff.$t$
  where name = $t$Miami Fans Takeover New York$t$ and tagline is not distinct from $t$Miami gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Game faces on in Silicon Valley: Dolphins fans beat the home crowd to it.$t$
  where name = $t$Miami Fans Takeover San Francisco$t$ and tagline is not distinct from $t$Miami fans, take over San Francisco before kickoff.$t$;
update public.games set tagline = $t$The NFC North score is open. Vikings fans start settling it across the Windy City.$t$
  where name = $t$Minnesota Fans Takeover Chicago$t$ and tagline is not distinct from $t$One night early, Minnesota turns Chicago into a pregame playground.$t$;
update public.games set tagline = $t$Vikings fans pick the fight early, claiming Motown from Lions country.$t$
  where name = $t$Minnesota Fans Takeover Detroit$t$ and tagline is not distinct from $t$One night early, Minnesota turns Detroit into a pregame playground.$t$;
update public.games set tagline = $t$Border battle. Vikings fans drag the Black-and-Blue fight onto Packers turf.$t$
  where name = $t$Minnesota Fans Takeover Green Bay$t$ and tagline is not distinct from $t$Minnesota fans, take over Green Bay before kickoff.$t$;
update public.games set tagline = $t$Vikings fans cross an ocean to start the party in the Azteca.$t$
  where name = $t$Minnesota Fans Takeover Mexico City$t$ and tagline is not distinct from $t$Minnesota fans, take over Mexico City before kickoff.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Vikings fans loose in Patriot Place.$t$
  where name = $t$Minnesota Fans Takeover New England$t$ and tagline is not distinct from $t$Minnesota rolls in a day early for a clue-led run through Foxborough.$t$;
update public.games set tagline = $t$The visitors strike first: Vikings fans light up Times Square the night before.$t$
  where name = $t$Minnesota Fans Takeover New York$t$ and tagline is not distinct from $t$Minnesota gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Vikings fans roll into the bay a full day before kickoff.$t$
  where name = $t$Minnesota Fans Takeover Tampa Bay$t$ and tagline is not distinct from $t$Minnesota fans, take over Tampa Bay before kickoff.$t$;
update public.games set tagline = $t$The AFC East throne, contested a day early: Patriots fans come for the Bills.$t$
  where name = $t$New England Fans Takeover Buffalo$t$ and tagline is not distinct from $t$New England rolls in a day early for a clue-led run through Orchard Park.$t$;
update public.games set tagline = $t$deep-dish country, but loud and in road colors: Patriots fans arrive early.$t$
  where name = $t$New England Fans Takeover Chicago$t$ and tagline is not distinct from $t$New England rolls in a day early for a clue-led run through Chicago.$t$;
update public.games set tagline = $t$Patriots fans turn the beaches into a tailgate that started a day too early.$t$
  where name = $t$New England Fans Takeover Jacksonville$t$ and tagline is not distinct from $t$One night early, New England turns Jacksonville into a pregame playground.$t$;
update public.games set tagline = $t$Game faces on in the loudest stadium on earth: Patriots fans beat the home crowd to it.$t$
  where name = $t$New England Fans Takeover Kansas City$t$ and tagline is not distinct from $t$New England gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Patriots fans loose in the SoFi glow.$t$
  where name = $t$New England Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$New England fans, take over Los Angeles before kickoff.$t$;
update public.games set tagline = $t$Two AFC East rivals, one city: Patriots fans get South Beach first.$t$
  where name = $t$New England Fans Takeover Miami$t$ and tagline is not distinct from $t$New England rolls in a day early for a clue-led run through Miami Gardens.$t$;
update public.games set tagline = $t$Patriots fans go global, running Bavaria before the whistle.$t$
  where name = $t$New England Fans Takeover Munich$t$ and tagline is not distinct from $t$New England gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Patriots fans descend on the bright lights: the home crowd can wait until tomorrow.$t$
  where name = $t$New England Fans Takeover New York$t$ and tagline is not distinct from $t$New England gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Patriots fans hunt clues across the rain and the roar of the 12s while the home side sleeps.$t$
  where name = $t$New England Fans Takeover Seattle$t$ and tagline is not distinct from $t$New England gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Deep South grudge match: Saints fans settle the Falcons score before the snap.$t$
  where name = $t$New Orleans Fans Takeover Atlanta$t$ and tagline is not distinct from $t$New Orleans rolls in a day early for a clue-led run through Atlanta.$t$;
update public.games set tagline = $t$Saints fans bring the away-game energy to the Inner Harbor, 24 hours early.$t$
  where name = $t$New Orleans Fans Takeover Baltimore$t$ and tagline is not distinct from $t$New Orleans fans, take over Baltimore before kickoff.$t$;
update public.games set tagline = $t$Saints fans descend on deep-dish country: the home crowd can wait until tomorrow.$t$
  where name = $t$New Orleans Fans Takeover Chicago$t$ and tagline is not distinct from $t$New Orleans gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Saints fans scout the Queen City the night before, just to feel at home tomorrow.$t$
  where name = $t$New Orleans Fans Takeover Cincinnati$t$ and tagline is not distinct from $t$New Orleans rolls in a day early for a clue-led run through Cincinnati.$t$;
update public.games set tagline = $t$Road colors in the D: Saints fans get there first.$t$
  where name = $t$New Orleans Fans Takeover Detroit$t$ and tagline is not distinct from $t$New Orleans fans, take over Detroit before kickoff.$t$;
update public.games set tagline = $t$Who Dat takes Manhattan: Saints fans bring the second line to the bright lights.$t$
  where name = $t$New Orleans Fans Takeover New York$t$ and tagline is not distinct from $t$One night early, New Orleans turns New York into a pregame playground.$t$;
update public.games set tagline = $t$Kickoff abroad: Saints fans get the Seine and the City of Light to themselves first.$t$
  where name = $t$New Orleans Fans Takeover Saint-Denis$t$ and tagline is not distinct from $t$New Orleans fans, take over Saint-Denis before kickoff.$t$;
update public.games set tagline = $t$Division week gets personal: Saints fans seize pirate country before facing the Buccaneers.$t$
  where name = $t$New Orleans Fans Takeover Tampa Bay$t$ and tagline is not distinct from $t$New Orleans fans, take over Tampa Bay before kickoff.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Jets fans loose in the desert.$t$
  where name = $t$New York Fans Takeover Arizona$t$ and tagline is not distinct from $t$New York rolls in a day early for a clue-led run through Glendale.$t$;
update public.games set tagline = $t$Jets fans bring the AFC East bad blood to wing country. Let the trash talk begin.$t$
  where name = $t$New York Fans Takeover Buffalo$t$ and tagline is not distinct from $t$New York fans, take over Buffalo before kickoff.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Jets fans loose in deep-dish country.$t$
  where name = $t$New York Fans Takeover Chicago$t$ and tagline is not distinct from $t$New York rolls in a day early for a clue-led run through Chicago.$t$;
update public.games set tagline = $t$Giants fans drag the NFC East grudge into the shadow of the giant star: settle it before kickoff.$t$
  where name = $t$New York Fans Takeover Dallas$t$ and tagline is not distinct from $t$One night early, New York turns Dallas into a pregame playground.$t$;
update public.games set tagline = $t$Jets fans turn the D into a tailgate that started a day too early.$t$
  where name = $t$New York Fans Takeover Detroit$t$ and tagline is not distinct from $t$New York gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$The visitors strike first: Giants fans light up smoked-brisket country the night before.$t$
  where name = $t$New York Fans Takeover Houston$t$ and tagline is not distinct from $t$New York rolls in a day early for a clue-led run through Houston.$t$;
update public.games set tagline = $t$Road colors in the Circle City: Giants fans get there first.$t$
  where name = $t$New York Fans Takeover Indianapolis$t$ and tagline is not distinct from $t$New York gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Jets fans trade home turf for the loudest stadium on earth and dare the locals to notice.$t$
  where name = $t$New York Fans Takeover Kansas City$t$ and tagline is not distinct from $t$New York gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$The visitors strike first: Giants fans light up the SoFi glow the night before.$t$
  where name = $t$New York Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$New York fans, take over Los Angeles before kickoff.$t$;
update public.games set tagline = $t$Jets fans pick the fight early, claiming South Beach from Dolphins country.$t$
  where name = $t$New York Fans Takeover Miami$t$ and tagline is not distinct from $t$New York fans, take over Miami before kickoff.$t$;
update public.games set tagline = $t$Division week gets personal: Jets fans seize Gillette before facing the Patriots.$t$
  where name = $t$New York Fans Takeover New England$t$ and tagline is not distinct from $t$New York gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Brotherly hate. Giants fans bring the NFC East venom to Eagles country.$t$
  where name = $t$New York Fans Takeover Philadelphia$t$ and tagline is not distinct from $t$New York rolls in a day early for a clue-led run through Philadelphia.$t$;
update public.games set tagline = $t$A day early, Giants fans go looking for trouble in the rain and the roar of the 12s.$t$
  where name = $t$New York Fans Takeover Seattle$t$ and tagline is not distinct from $t$One night early, New York turns Seattle into a pregame playground.$t$;
update public.games set tagline = $t$Jets fans crash the honky-tonks of Broadway and make themselves right at home.$t$
  where name = $t$New York Fans Takeover Tennessee$t$ and tagline is not distinct from $t$New York rolls in a day early for a clue-led run through Nashville.$t$;
update public.games set tagline = $t$Giants fans hunt down the monuments while the Commanders faithful sleep on it.$t$
  where name = $t$New York Fans Takeover Washington$t$ and tagline is not distinct from $t$One night early, New York turns Washington into a pregame playground.$t$;
update public.games set tagline = $t$Eagles fans scout cactus country the night before, just to feel at home tomorrow.$t$
  where name = $t$Philadelphia Fans Takeover Arizona$t$ and tagline is not distinct from $t$Philadelphia fans, take over Arizona before kickoff.$t$;
update public.games set tagline = $t$Eagles fans scout the Windy City the night before, just to feel at home tomorrow.$t$
  where name = $t$Philadelphia Fans Takeover Chicago$t$ and tagline is not distinct from $t$Philadelphia fans, take over Chicago before kickoff.$t$;
update public.games set tagline = $t$Kickoff abroad: Eagles fans get tea, the Tube, and Tottenham's pitch to themselves first.$t$
  where name = $t$Philadelphia Fans Takeover London$t$ and tagline is not distinct from $t$Philadelphia fans, take over London before kickoff.$t$;
update public.games set tagline = $t$Eagles fans trade home turf for Times Square and dare the locals to notice.$t$
  where name = $t$Philadelphia Fans Takeover New York$t$ and tagline is not distinct from $t$Philadelphia rolls in a day early for a clue-led run through East Rutherford.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Eagles fans loose in the fog and the Golden Gate.$t$
  where name = $t$Philadelphia Fans Takeover San Francisco$t$ and tagline is not distinct from $t$Philadelphia rolls in a day early for a clue-led run through Santa Clara.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Eagles fans loose in Music City.$t$
  where name = $t$Philadelphia Fans Takeover Tennessee$t$ and tagline is not distinct from $t$Philadelphia fans, take over Tennessee before kickoff.$t$;
update public.games set tagline = $t$Eagles fans crash the Nation's Capital looking for Commanders fans to needle before kickoff.$t$
  where name = $t$Philadelphia Fans Takeover Washington$t$ and tagline is not distinct from $t$Divisional Foe Showdown In The Nation's Capital$t$;
update public.games set tagline = $t$The AFC North's meanest rivalry: Steelers fans settle the Ravens score in the streets first.$t$
  where name = $t$Pittsburgh Fans Takeover Baltimore$t$ and tagline is not distinct from $t$Pittsburgh fans, take over Baltimore before kickoff.$t$;
update public.games set tagline = $t$Two AFC North rivals, one city: Steelers fans get a bowl of Cincinnati chili first.$t$
  where name = $t$Pittsburgh Fans Takeover Cincinnati$t$ and tagline is not distinct from $t$One night early, Pittsburgh turns Cincinnati into a pregame playground.$t$;
update public.games set tagline = $t$Steelers fans hunt down the shores of Lake Erie while the Browns faithful sleep on it.$t$
  where name = $t$Pittsburgh Fans Takeover Cleveland$t$ and tagline is not distinct from $t$One night early, Pittsburgh turns Cleveland into a pregame playground.$t$;
update public.games set tagline = $t$Duuuval, but loud and in road colors: Steelers fans arrive early.$t$
  where name = $t$Pittsburgh Fans Takeover Jacksonville$t$ and tagline is not distinct from $t$Pittsburgh gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Steelers fans bring the away-game energy to Patriot Place, 24 hours early.$t$
  where name = $t$Pittsburgh Fans Takeover New England$t$ and tagline is not distinct from $t$Pittsburgh rolls in a day early for a clue-led run through Foxborough.$t$;
update public.games set tagline = $t$Steelers fans roll into the Linc a full day before kickoff.$t$
  where name = $t$Pittsburgh Fans Takeover Philadelphia$t$ and tagline is not distinct from $t$Pittsburgh gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Steelers fans take the fight overseas: the edge of Paris, the day before kickoff.$t$
  where name = $t$Pittsburgh Fans Takeover Saint-Denis$t$ and tagline is not distinct from $t$Pittsburgh gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$The visitors strike first: Steelers fans light up the bay the night before.$t$
  where name = $t$Pittsburgh Fans Takeover Tampa Bay$t$ and tagline is not distinct from $t$One night early, Pittsburgh turns Tampa Bay into a pregame playground.$t$;
update public.games set tagline = $t$Steelers fans descend on Music City: the home crowd can wait until tomorrow.$t$
  where name = $t$Pittsburgh Fans Takeover Tennessee$t$ and tagline is not distinct from $t$Pittsburgh fans, take over Tennessee before kickoff.$t$;
update public.games set tagline = $t$The NFC West score is open. 49ers fans start settling it across cactus country.$t$
  where name = $t$San Francisco Fans Takeover Arizona$t$ and tagline is not distinct from $t$San Francisco rolls in a day early for a clue-led run through Glendale.$t$;
update public.games set tagline = $t$49ers fans take the long way to the stadium, straight through peach-tree streets and trap beats.$t$
  where name = $t$San Francisco Fans Takeover Atlanta$t$ and tagline is not distinct from $t$San Francisco gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$49ers fans descend on Big D: the home crowd can wait until tomorrow.$t$
  where name = $t$San Francisco Fans Takeover Dallas$t$ and tagline is not distinct from $t$San Francisco gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: 49ers fans loose in burnt ends and BBQ smoke.$t$
  where name = $t$San Francisco Fans Takeover Kansas City$t$ and tagline is not distinct from $t$One night early, San Francisco turns Kansas City into a pregame playground.$t$;
update public.games set tagline = $t$Road colors in Hollywood: 49ers fans get there first.$t$
  where name = $t$San Francisco Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$San Francisco rolls in a day early for a clue-led run through Inglewood.$t$;
update public.games set tagline = $t$49ers fans go global, running Australia before the whistle.$t$
  where name = $t$San Francisco Fans Takeover Melbourne$t$ and tagline is not distinct from $t$San Francisco fans, take over Melbourne before kickoff.$t$;
update public.games set tagline = $t$49ers fans cross an ocean to start the party in the Azteca.$t$
  where name = $t$San Francisco Fans Takeover Mexico City$t$ and tagline is not distinct from $t$San Francisco rolls in a day early for a clue-led run through Mexico City.$t$;
update public.games set tagline = $t$49ers fans crash Times Square and make themselves right at home.$t$
  where name = $t$San Francisco Fans Takeover New York$t$ and tagline is not distinct from $t$San Francisco rolls in a day early for a clue-led run through East Rutherford.$t$;
update public.games set tagline = $t$The NFC West's loudest rivalry: 49ers fans turn up the volume in Seahawks country.$t$
  where name = $t$San Francisco Fans Takeover Seattle$t$ and tagline is not distinct from $t$San Francisco rolls in a day early for a clue-led run through Seattle.$t$;
update public.games set tagline = $t$The NFC West score is open. Seahawks fans start settling it across the Valley of the Sun.$t$
  where name = $t$Seattle Fans Takeover Arizona$t$ and tagline is not distinct from $t$Seattle rolls in a day early for a clue-led run through Glendale.$t$;
update public.games set tagline = $t$Seahawks fans descend on uptown Charlotte: the home crowd can wait until tomorrow.$t$
  where name = $t$Seattle Fans Takeover Carolina$t$ and tagline is not distinct from $t$Seattle fans, take over Carolina before kickoff.$t$;
update public.games set tagline = $t$Seahawks fans answer kickoff with a head start through Mile High.$t$
  where name = $t$Seattle Fans Takeover Denver$t$ and tagline is not distinct from $t$Seattle rolls in a day early for a clue-led run through Denver.$t$;
update public.games set tagline = $t$Seahawks fans bring the away-game energy to the Strip, 24 hours early.$t$
  where name = $t$Seattle Fans Takeover Las Vegas$t$ and tagline is not distinct from $t$One night early, Seattle turns Las Vegas into a pregame playground.$t$;
update public.games set tagline = $t$Seahawks fans descend on sunshine and palm trees: the home crowd can wait until tomorrow.$t$
  where name = $t$Seattle Fans Takeover Los Angeles$t$ and tagline is not distinct from $t$Seattle rolls in a day early for a clue-led run through Inglewood.$t$;
update public.games set tagline = $t$Seahawks fans bring the away-game energy to the cheesesteak capital, 24 hours early.$t$
  where name = $t$Seattle Fans Takeover Philadelphia$t$ and tagline is not distinct from $t$Seattle fans, take over Philadelphia before kickoff.$t$;
update public.games set tagline = $t$The NFC West's loudest rivalry: Seahawks fans turn up the volume in 49ers country.$t$
  where name = $t$Seattle Fans Takeover San Francisco$t$ and tagline is not distinct from $t$Seattle fans, take over San Francisco before kickoff.$t$;
update public.games set tagline = $t$Seahawks fans take the long way to the stadium, straight through D.C..$t$
  where name = $t$Seattle Fans Takeover Washington$t$ and tagline is not distinct from $t$One night early, Seattle turns Washington into a pregame playground.$t$;
update public.games set tagline = $t$Southern Miss fans trade Hattiesburg for the Quarter: Golden Eagles loose on Bourbon Street.$t$
  where name = $t$Southern Mississippi Fans Takeover New Orleans$t$ and tagline is not distinct from $t$A New Orleans adventure for Southern Miss fans.$t$;
update public.games set tagline = $t$The NFC South score is open. Buccaneers fans start settling it across the Benz.$t$
  where name = $t$Tampa Bay Fans Takeover Atlanta$t$ and tagline is not distinct from $t$Tampa Bay rolls in a day early for a clue-led run through Atlanta.$t$;
update public.games set tagline = $t$Buccaneers fans take the long way to the stadium, straight through Charm City.$t$
  where name = $t$Tampa Bay Fans Takeover Baltimore$t$ and tagline is not distinct from $t$One night early, Tampa Bay turns Baltimore into a pregame playground.$t$;
update public.games set tagline = $t$Two NFC South rivals, one city: Buccaneers fans get uptown Charlotte first.$t$
  where name = $t$Tampa Bay Fans Takeover Carolina$t$ and tagline is not distinct from $t$Tampa Bay rolls in a day early for a clue-led run through Charlotte.$t$;
update public.games set tagline = $t$Buccaneers fans turn the lakefront into a tailgate that started a day too early.$t$
  where name = $t$Tampa Bay Fans Takeover Chicago$t$ and tagline is not distinct from $t$Tampa Bay rolls in a day early for a clue-led run through Chicago.$t$;
update public.games set tagline = $t$Buccaneers fans trade home turf for the Jungle and dare the locals to notice.$t$
  where name = $t$Tampa Bay Fans Takeover Cincinnati$t$ and tagline is not distinct from $t$Tampa Bay gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$The visitors strike first: Buccaneers fans light up Texas-sized everything the night before.$t$
  where name = $t$Tampa Bay Fans Takeover Dallas$t$ and tagline is not distinct from $t$One night early, Tampa Bay turns Dallas into a pregame playground.$t$;
update public.games set tagline = $t$Buccaneers fans scout Ford Field the night before, just to feel at home tomorrow.$t$
  where name = $t$Tampa Bay Fans Takeover Detroit$t$ and tagline is not distinct from $t$Tampa Bay rolls in a day early for a clue-led run through Detroit.$t$;
update public.games set tagline = $t$Division week gets personal: Buccaneers fans seize a second-line down the French Quarter before facing the Saints.$t$
  where name = $t$Tampa Bay Fans Takeover New Orleans$t$ and tagline is not distinct from $t$An escape room style game that takes place on the streets of New Orleans$t$;
update public.games set tagline = $t$Charm City, but loud and in road colors: Titans fans arrive early.$t$
  where name = $t$Tennessee Fans Takeover Baltimore$t$ and tagline is not distinct from $t$Tennessee fans, take over Baltimore before kickoff.$t$;
update public.games set tagline = $t$Titans fans bring the away-game energy to the Jungle, 24 hours early.$t$
  where name = $t$Tennessee Fans Takeover Cincinnati$t$ and tagline is not distinct from $t$Tennessee fans, take over Cincinnati before kickoff.$t$;
update public.games set tagline = $t$Titans fans descend on Texas-sized everything: the home crowd can wait until tomorrow.$t$
  where name = $t$Tennessee Fans Takeover Dallas$t$ and tagline is not distinct from $t$One night early, Tennessee turns Dallas into a pregame playground.$t$;
update public.games set tagline = $t$Twenty-four hours before kickoff, Titans fans run Ford Field.$t$
  where name = $t$Tennessee Fans Takeover Detroit$t$ and tagline is not distinct from $t$Tennessee fans, take over Detroit before kickoff.$t$;
update public.games set tagline = $t$Titans fans don't wait for kickoff to remind the Texans who they are: not in the Bayou City.$t$
  where name = $t$Tennessee Fans Takeover Houston$t$ and tagline is not distinct from $t$Tennessee fans, take over Houston before kickoff.$t$;
update public.games set tagline = $t$AFC South bad blood with a head start: Titans fans crash Colts turf.$t$
  where name = $t$Tennessee Fans Takeover Indianapolis$t$ and tagline is not distinct from $t$One night early, Tennessee turns Indianapolis into a pregame playground.$t$;
update public.games set tagline = $t$Titans vs Jaguars again. The AFC South's nastiest feud spills into the pool-deck end zone.$t$
  where name = $t$Tennessee Fans Takeover Jacksonville$t$ and tagline is not distinct from $t$Tennessee rolls in a day early for a clue-led run through Jacksonville.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Titans fans loose in the Strip.$t$
  where name = $t$Tennessee Fans Takeover Las Vegas$t$ and tagline is not distinct from $t$Tennessee gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Titans fans crash the city that never sleeps and make themselves right at home.$t$
  where name = $t$Tennessee Fans Takeover New York$t$ and tagline is not distinct from $t$One night early, Tennessee turns New York into a pregame playground.$t$;
update public.games set tagline = $t$Commanders fans trade home turf for the Valley of the Sun and dare the locals to notice.$t$
  where name = $t$Washington Fans Takeover Arizona$t$ and tagline is not distinct from $t$One night early, Washington turns Arizona into a pregame playground.$t$;
update public.games set tagline = $t$America's Team meets the Capital: Commanders fans crash Cowboys turf for an NFC East score that never settles.$t$
  where name = $t$Washington Fans Takeover Dallas$t$ and tagline is not distinct from $t$Washington gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Clues, kickoff, bragging rights: Commanders fans loose in the pool-deck end zone.$t$
  where name = $t$Washington Fans Takeover Jacksonville$t$ and tagline is not distinct from $t$One night early, Washington turns Jacksonville into a pregame playground.$t$;
update public.games set tagline = $t$Neutral turf, road colors: Commanders fans claim across the pond the night before.$t$
  where name = $t$Washington Fans Takeover London$t$ and tagline is not distinct from $t$Washington rolls in a day early for a clue-led run through London.$t$;
update public.games set tagline = $t$Commanders fans bring the away-game energy to the frozen North, 24 hours early.$t$
  where name = $t$Washington Fans Takeover Minnesota$t$ and tagline is not distinct from $t$One night early, Washington turns Minnesota into a pregame playground.$t$;
update public.games set tagline = $t$Commanders fans answer kickoff with a head start through the city that never sleeps.$t$
  where name = $t$Washington Fans Takeover New York$t$ and tagline is not distinct from $t$Washington gets the city first. Kickoff comes tomorrow.$t$;
update public.games set tagline = $t$Commanders fans crash the cheesesteak capital looking for Eagles fans to needle before kickoff.$t$
  where name = $t$Washington Fans Takeover Philadelphia$t$ and tagline is not distinct from $t$One night early, Washington turns Philadelphia into a pregame playground.$t$;
update public.games set tagline = $t$Commanders fans hunt clues across the Bay while the home side sleeps.$t$
  where name = $t$Washington Fans Takeover San Francisco$t$ and tagline is not distinct from $t$One night early, Washington turns San Francisco into a pregame playground.$t$;
update public.games set tagline = $t$Commanders fans hunt clues across Nashville neon while the home side sleeps.$t$
  where name = $t$Washington Fans Takeover Tennessee$t$ and tagline is not distinct from $t$Washington gets the city first. Kickoff comes tomorrow.$t$;

commit;
