-- Standardize fanbase to a real "City, ST" (nearest big city to the venue),
-- never a region/state. Source: the curated game_city, with overrides where the
-- team's own city is the true fanbase city (49ers→San Francisco, Nets→Brooklyn,
-- Ducks→Anaheim, Devils→Newark, Clippers→Los Angeles). Self-contained: sets the
-- fanbase for every core team, matched by stable team_key. Supersedes the earlier
-- fanbase backfill. Safe to re-run.
--
-- fanbase is a matching key on the public games page; the nearest-team coords
-- (assets/states/your_nearest_team.js) cover all of these city keys.

-- Clippers had no game_city; give it one (its fanbase city).
update public.teams set game_city = 'Los Angeles, CA'
  where team_key = 'NBA:LAC' and coalesce(game_city, '') = '';
-- Tidy Washington game_city periods so "D.C." doesn't re-propagate.
update public.teams set game_city = 'Washington, DC'
  where game_city = 'Washington, D.C.';

update public.teams t set
  fanbase = v.fanbase
from (values
  ('MLB:ARI', 'Phoenix, AZ'),
  ('MLB:ATH', 'Sacramento, CA'),
  ('MLB:ATL', 'Atlanta, GA'),
  ('MLB:BAL', 'Baltimore, MD'),
  ('MLB:BOS', 'Boston, MA'),
  ('MLB:CHC', 'Chicago, IL'),
  ('MLB:CHW', 'Chicago, IL'),
  ('MLB:CIN', 'Cincinnati, OH'),
  ('MLB:CLE', 'Cleveland, OH'),
  ('MLB:COL', 'Denver, CO'),
  ('MLB:DET', 'Detroit, MI'),
  ('MLB:HOU', 'Houston, TX'),
  ('MLB:KC', 'Kansas City, MO'),
  ('MLB:LAA', 'Los Angeles, CA'),
  ('MLB:LAD', 'Los Angeles, CA'),
  ('MLB:MIA', 'Miami, FL'),
  ('MLB:MIL', 'Milwaukee, WI'),
  ('MLB:MIN', 'Minneapolis, MN'),
  ('MLB:NYM', 'New York, NY'),
  ('MLB:NYY', 'New York, NY'),
  ('MLB:PHI', 'Philadelphia, PA'),
  ('MLB:PIT', 'Pittsburgh, PA'),
  ('MLB:SD', 'San Diego, CA'),
  ('MLB:SEA', 'Seattle, WA'),
  ('MLB:SF', 'San Francisco, CA'),
  ('MLB:STL', 'St. Louis, MO'),
  ('MLB:TB', 'Tampa, FL'),
  ('MLB:TEX', 'Dallas, TX'),
  ('MLB:TOR', 'Toronto, ON'),
  ('MLB:WSH', 'Washington, DC'),
  ('NBA:ATL', 'Atlanta, GA'),
  ('NBA:BKN', 'Brooklyn, NY'),
  ('NBA:BOS', 'Boston, MA'),
  ('NBA:CHA', 'Charlotte, NC'),
  ('NBA:CHI', 'Chicago, IL'),
  ('NBA:CLE', 'Cleveland, OH'),
  ('NBA:DAL', 'Dallas, TX'),
  ('NBA:DEN', 'Denver, CO'),
  ('NBA:DET', 'Detroit, MI'),
  ('NBA:GS', 'San Francisco, CA'),
  ('NBA:HOU', 'Houston, TX'),
  ('NBA:IND', 'Indianapolis, IN'),
  ('NBA:LAC', 'Los Angeles, CA'),
  ('NBA:LAL', 'Los Angeles, CA'),
  ('NBA:MEM', 'Memphis, TN'),
  ('NBA:MIA', 'Miami, FL'),
  ('NBA:MIL', 'Milwaukee, WI'),
  ('NBA:MIN', 'Minneapolis, MN'),
  ('NBA:NO', 'New Orleans, LA'),
  ('NBA:NY', 'New York, NY'),
  ('NBA:OKC', 'Oklahoma City, OK'),
  ('NBA:ORL', 'Orlando, FL'),
  ('NBA:PHI', 'Philadelphia, PA'),
  ('NBA:PHX', 'Phoenix, AZ'),
  ('NBA:POR', 'Portland, OR'),
  ('NBA:SA', 'San Antonio, TX'),
  ('NBA:SAC', 'Sacramento, CA'),
  ('NBA:TOR', 'Toronto, ON'),
  ('NBA:UTAH', 'Salt Lake City, UT'),
  ('NBA:WSH', 'Washington, DC'),
  ('NFL:ARI', 'Phoenix, AZ'),
  ('NFL:ATL', 'Atlanta, GA'),
  ('NFL:BAL', 'Baltimore, MD'),
  ('NFL:BUF', 'Buffalo, NY'),
  ('NFL:CAR', 'Charlotte, NC'),
  ('NFL:CHI', 'Chicago, IL'),
  ('NFL:CIN', 'Cincinnati, OH'),
  ('NFL:CLE', 'Cleveland, OH'),
  ('NFL:DAL', 'Dallas, TX'),
  ('NFL:DEN', 'Denver, CO'),
  ('NFL:DET', 'Detroit, MI'),
  ('NFL:GB', 'Green Bay, WI'),
  ('NFL:HOU', 'Houston, TX'),
  ('NFL:IND', 'Indianapolis, IN'),
  ('NFL:JAX', 'Jacksonville, FL'),
  ('NFL:KC', 'Kansas City, MO'),
  ('NFL:LAC', 'Los Angeles, CA'),
  ('NFL:LAR', 'Los Angeles, CA'),
  ('NFL:LV', 'Las Vegas, NV'),
  ('NFL:MIA', 'Miami, FL'),
  ('NFL:MIN', 'Minneapolis, MN'),
  ('NFL:NE', 'Boston, MA'),
  ('NFL:NO', 'New Orleans, LA'),
  ('NFL:NYG', 'New York, NY'),
  ('NFL:NYJ', 'New York, NY'),
  ('NFL:PHI', 'Philadelphia, PA'),
  ('NFL:PIT', 'Pittsburgh, PA'),
  ('NFL:SEA', 'Seattle, WA'),
  ('NFL:SF', 'San Francisco, CA'),
  ('NFL:TB', 'Tampa, FL'),
  ('NFL:TEN', 'Nashville, TN'),
  ('NFL:WSH', 'Washington, DC'),
  ('NHL:ANA', 'Anaheim, CA'),
  ('NHL:BOS', 'Boston, MA'),
  ('NHL:BUF', 'Buffalo, NY'),
  ('NHL:CAR', 'Raleigh, NC'),
  ('NHL:CBJ', 'Columbus, OH'),
  ('NHL:CGY', 'Calgary, AB'),
  ('NHL:CHI', 'Chicago, IL'),
  ('NHL:COL', 'Denver, CO'),
  ('NHL:DAL', 'Dallas, TX'),
  ('NHL:DET', 'Detroit, MI'),
  ('NHL:EDM', 'Edmonton, AB'),
  ('NHL:FLA', 'Miami, FL'),
  ('NHL:LA', 'Los Angeles, CA'),
  ('NHL:MIN', 'Minneapolis, MN'),
  ('NHL:MTL', 'Montreal, QC'),
  ('NHL:NJ', 'Newark, NJ'),
  ('NHL:NSH', 'Nashville, TN'),
  ('NHL:NYI', 'New York, NY'),
  ('NHL:NYR', 'New York, NY'),
  ('NHL:OTT', 'Ottawa, ON'),
  ('NHL:PHI', 'Philadelphia, PA'),
  ('NHL:PIT', 'Pittsburgh, PA'),
  ('NHL:SEA', 'Seattle, WA'),
  ('NHL:SJ', 'San Jose, CA'),
  ('NHL:STL', 'St. Louis, MO'),
  ('NHL:TB', 'Tampa, FL'),
  ('NHL:TOR', 'Toronto, ON'),
  ('NHL:UTA', 'Salt Lake City, UT'),
  ('NHL:VAN', 'Vancouver, BC'),
  ('NHL:VGK', 'Las Vegas, NV'),
  ('NHL:WPG', 'Winnipeg, MB'),
  ('NHL:WSH', 'Washington, DC')
) as v(team_key, fanbase)
where t.team_key = v.team_key;
