-- waypoints — skunkworks catalog of real-world points (city/state/address/name)
-- with a description. Standalone table, independent of the games graph for now.
-- Start/end semantics live elsewhere, not on this table. Safe to re-run.

create table if not exists public.waypoints (
  wpid        bigint generated always as identity primary key,  -- unique auto number
  city        text,
  state       text,
  address     text,
  name        text,
  description text,
  w3w         text   -- what3words address (///word.word.word), generated by Fill
);

-- Added after initial create; safe to re-run.
alter table public.waypoints add column if not exists w3w text;

comment on table public.waypoints is
  'Skunkworks catalog of real-world points. wpid = unique auto number.';
comment on column public.waypoints.wpid is 'Unique auto-incrementing id (identity).';
comment on column public.waypoints.w3w is
  'what3words address (///word.word.word), generated from the point by the Fill button.';

alter table public.waypoints enable row level security;

-- READ: public (anon + authenticated). Mirrors the teams table; not secret.
drop policy if exists "waypoints readable by anyone" on public.waypoints;
create policy "waypoints readable by anyone"
  on public.waypoints for select
  using (true);

-- WRITE: any signed-in user (the mc/* tools sit behind mc/js/admin-auth.js).
drop policy if exists "waypoints insert by authenticated" on public.waypoints;
create policy "waypoints insert by authenticated"
  on public.waypoints for insert
  to authenticated
  with check (true);

drop policy if exists "waypoints update by authenticated" on public.waypoints;
create policy "waypoints update by authenticated"
  on public.waypoints for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "waypoints delete by authenticated" on public.waypoints;
create policy "waypoints delete by authenticated"
  on public.waypoints for delete
  to authenticated
  using (true);
