-- 2026072305_countries_all_iso.sql
--
-- Fill public.countries with the complete ISO 3166-1 set (~249 codes) so every
-- country is pickable in the country dropdowns. Self-contained: (re)creates the
-- table + RLS if 2026072304 hasn't run, then upserts with ON CONFLICT DO NOTHING
-- so the curated rows/aliases already seeded by 2026072304 are left untouched.
--
-- Display names are the common English short names, chosen to match what the
-- site already stores (Turkey, South Korea, Russia, United States, ...). Aliases
-- cover the spellings the parser needs to recognize (uk/england -> GBR, uae ->
-- ARE, czechia -> CZE, burma -> MMR, ...). Safe to re-run.

-- ── Table (idempotent; mirrors 2026072304) ──────────────────────────────────
create table if not exists public.countries (
  code       text primary key,
  name       text not null,
  aliases    text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists countries_name_lower_uidx on public.countries (lower(name));
alter table public.countries enable row level security;
drop policy if exists "Countries are publicly readable" on public.countries;
create policy "Countries are publicly readable" on public.countries for select to public using (true);
drop policy if exists "Authenticated users can manage countries" on public.countries;
create policy "Authenticated users can manage countries" on public.countries for all to authenticated using (true) with check (true);
grant select on public.countries to anon, authenticated;
grant insert, update, delete on public.countries to authenticated;

-- ── Full ISO 3166-1 list ────────────────────────────────────────────────────
insert into public.countries (code, name, aliases) values
  ('AFG', 'Afghanistan', '{}'),
  ('ALA', 'Åland Islands', '{}'),
  ('ALB', 'Albania', '{}'),
  ('DZA', 'Algeria', '{}'),
  ('ASM', 'American Samoa', '{}'),
  ('AND', 'Andorra', '{}'),
  ('AGO', 'Angola', '{}'),
  ('AIA', 'Anguilla', '{}'),
  ('ATA', 'Antarctica', '{}'),
  ('ATG', 'Antigua and Barbuda', '{}'),
  ('ARG', 'Argentina', '{}'),
  ('ARM', 'Armenia', '{}'),
  ('ABW', 'Aruba', '{}'),
  ('AUS', 'Australia', '{}'),
  ('AUT', 'Austria', '{}'),
  ('AZE', 'Azerbaijan', '{}'),
  ('BHS', 'Bahamas', '{}'),
  ('BHR', 'Bahrain', '{}'),
  ('BGD', 'Bangladesh', '{}'),
  ('BRB', 'Barbados', '{}'),
  ('BLR', 'Belarus', '{}'),
  ('BEL', 'Belgium', '{}'),
  ('BLZ', 'Belize', '{}'),
  ('BEN', 'Benin', '{}'),
  ('BMU', 'Bermuda', '{}'),
  ('BTN', 'Bhutan', '{}'),
  ('BOL', 'Bolivia', '{}'),
  ('BES', 'Caribbean Netherlands', array['bonaire']),
  ('BIH', 'Bosnia and Herzegovina', array['bosnia']),
  ('BWA', 'Botswana', '{}'),
  ('BVT', 'Bouvet Island', '{}'),
  ('BRA', 'Brazil', '{}'),
  ('IOT', 'British Indian Ocean Territory', '{}'),
  ('BRN', 'Brunei', '{}'),
  ('BGR', 'Bulgaria', '{}'),
  ('BFA', 'Burkina Faso', '{}'),
  ('BDI', 'Burundi', '{}'),
  ('CPV', 'Cape Verde', array['cabo verde']),
  ('KHM', 'Cambodia', '{}'),
  ('CMR', 'Cameroon', '{}'),
  ('CAN', 'Canada', '{}'),
  ('CYM', 'Cayman Islands', '{}'),
  ('CAF', 'Central African Republic', '{}'),
  ('TCD', 'Chad', '{}'),
  ('CHL', 'Chile', '{}'),
  ('CHN', 'China', '{}'),
  ('CXR', 'Christmas Island', '{}'),
  ('CCK', 'Cocos (Keeling) Islands', '{}'),
  ('COL', 'Colombia', '{}'),
  ('COM', 'Comoros', '{}'),
  ('COG', 'Congo', array['republic of the congo','congo-brazzaville']),
  ('COD', 'DR Congo', array['democratic republic of the congo','drc','congo-kinshasa']),
  ('COK', 'Cook Islands', '{}'),
  ('CRI', 'Costa Rica', '{}'),
  ('CIV', 'Ivory Coast', array['cote d''ivoire','côte d''ivoire']),
  ('HRV', 'Croatia', '{}'),
  ('CUB', 'Cuba', '{}'),
  ('CUW', 'Curaçao', array['curacao']),
  ('CYP', 'Cyprus', '{}'),
  ('CZE', 'Czech Republic', array['czechia']),
  ('DNK', 'Denmark', '{}'),
  ('DJI', 'Djibouti', '{}'),
  ('DMA', 'Dominica', '{}'),
  ('DOM', 'Dominican Republic', '{}'),
  ('ECU', 'Ecuador', '{}'),
  ('EGY', 'Egypt', '{}'),
  ('SLV', 'El Salvador', '{}'),
  ('GNQ', 'Equatorial Guinea', '{}'),
  ('ERI', 'Eritrea', '{}'),
  ('EST', 'Estonia', '{}'),
  ('SWZ', 'Eswatini', array['swaziland']),
  ('ETH', 'Ethiopia', '{}'),
  ('FLK', 'Falkland Islands', '{}'),
  ('FRO', 'Faroe Islands', '{}'),
  ('FJI', 'Fiji', '{}'),
  ('FIN', 'Finland', '{}'),
  ('FRA', 'France', '{}'),
  ('GUF', 'French Guiana', '{}'),
  ('PYF', 'French Polynesia', '{}'),
  ('ATF', 'French Southern Territories', '{}'),
  ('GAB', 'Gabon', '{}'),
  ('GMB', 'Gambia', '{}'),
  ('GEO', 'Georgia (country)', array['sakartvelo']),
  ('DEU', 'Germany', '{}'),
  ('GHA', 'Ghana', '{}'),
  ('GIB', 'Gibraltar', '{}'),
  ('GRC', 'Greece', '{}'),
  ('GRL', 'Greenland', '{}'),
  ('GRD', 'Grenada', '{}'),
  ('GLP', 'Guadeloupe', '{}'),
  ('GUM', 'Guam', '{}'),
  ('GTM', 'Guatemala', '{}'),
  ('GGY', 'Guernsey', '{}'),
  ('GIN', 'Guinea', '{}'),
  ('GNB', 'Guinea-Bissau', '{}'),
  ('GUY', 'Guyana', '{}'),
  ('HTI', 'Haiti', '{}'),
  ('HMD', 'Heard Island and McDonald Islands', '{}'),
  ('VAT', 'Vatican City', array['holy see','vatican']),
  ('HND', 'Honduras', '{}'),
  ('HKG', 'Hong Kong', '{}'),
  ('HUN', 'Hungary', '{}'),
  ('ISL', 'Iceland', '{}'),
  ('IND', 'India', '{}'),
  ('IDN', 'Indonesia', '{}'),
  ('IRN', 'Iran', '{}'),
  ('IRQ', 'Iraq', '{}'),
  ('IRL', 'Ireland', '{}'),
  ('IMN', 'Isle of Man', '{}'),
  ('ISR', 'Israel', '{}'),
  ('ITA', 'Italy', '{}'),
  ('JAM', 'Jamaica', '{}'),
  ('JPN', 'Japan', '{}'),
  ('JEY', 'Jersey', '{}'),
  ('JOR', 'Jordan', '{}'),
  ('KAZ', 'Kazakhstan', '{}'),
  ('KEN', 'Kenya', '{}'),
  ('KIR', 'Kiribati', '{}'),
  ('PRK', 'North Korea', array['dprk','democratic people''s republic of korea']),
  ('KOR', 'South Korea', array['korea','republic of korea']),
  ('KWT', 'Kuwait', '{}'),
  ('KGZ', 'Kyrgyzstan', '{}'),
  ('LAO', 'Laos', '{}'),
  ('LVA', 'Latvia', '{}'),
  ('LBN', 'Lebanon', '{}'),
  ('LSO', 'Lesotho', '{}'),
  ('LBR', 'Liberia', '{}'),
  ('LBY', 'Libya', '{}'),
  ('LIE', 'Liechtenstein', '{}'),
  ('LTU', 'Lithuania', '{}'),
  ('LUX', 'Luxembourg', '{}'),
  ('MAC', 'Macau', array['macao']),
  ('MDG', 'Madagascar', '{}'),
  ('MWI', 'Malawi', '{}'),
  ('MYS', 'Malaysia', '{}'),
  ('MDV', 'Maldives', '{}'),
  ('MLI', 'Mali', '{}'),
  ('MLT', 'Malta', '{}'),
  ('MHL', 'Marshall Islands', '{}'),
  ('MTQ', 'Martinique', '{}'),
  ('MRT', 'Mauritania', '{}'),
  ('MUS', 'Mauritius', '{}'),
  ('MYT', 'Mayotte', '{}'),
  ('MEX', 'Mexico', '{}'),
  ('FSM', 'Micronesia', '{}'),
  ('MDA', 'Moldova', '{}'),
  ('MCO', 'Monaco', '{}'),
  ('MNG', 'Mongolia', '{}'),
  ('MNE', 'Montenegro', '{}'),
  ('MSR', 'Montserrat', '{}'),
  ('MAR', 'Morocco', '{}'),
  ('MOZ', 'Mozambique', '{}'),
  ('MMR', 'Myanmar', array['burma']),
  ('NAM', 'Namibia', '{}'),
  ('NRU', 'Nauru', '{}'),
  ('NPL', 'Nepal', '{}'),
  ('NLD', 'Netherlands', '{}'),
  ('NCL', 'New Caledonia', '{}'),
  ('NZL', 'New Zealand', '{}'),
  ('NIC', 'Nicaragua', '{}'),
  ('NER', 'Niger', '{}'),
  ('NGA', 'Nigeria', '{}'),
  ('NIU', 'Niue', '{}'),
  ('NFK', 'Norfolk Island', '{}'),
  ('MKD', 'North Macedonia', array['macedonia']),
  ('MNP', 'Northern Mariana Islands', '{}'),
  ('NOR', 'Norway', '{}'),
  ('OMN', 'Oman', '{}'),
  ('PAK', 'Pakistan', '{}'),
  ('PLW', 'Palau', '{}'),
  ('PSE', 'Palestine', array['palestinian territory']),
  ('PAN', 'Panama', '{}'),
  ('PNG', 'Papua New Guinea', '{}'),
  ('PRY', 'Paraguay', '{}'),
  ('PER', 'Peru', '{}'),
  ('PHL', 'Philippines', '{}'),
  ('PCN', 'Pitcairn', '{}'),
  ('POL', 'Poland', '{}'),
  ('PRT', 'Portugal', '{}'),
  ('PRI', 'Puerto Rico', '{}'),
  ('QAT', 'Qatar', '{}'),
  ('REU', 'Réunion', array['reunion']),
  ('ROU', 'Romania', '{}'),
  ('RUS', 'Russia', array['russian federation']),
  ('RWA', 'Rwanda', '{}'),
  ('BLM', 'Saint Barthélemy', array['saint barthelemy','st barts']),
  ('SHN', 'Saint Helena', '{}'),
  ('KNA', 'Saint Kitts and Nevis', '{}'),
  ('LCA', 'Saint Lucia', '{}'),
  ('MAF', 'Saint Martin', '{}'),
  ('SPM', 'Saint Pierre and Miquelon', '{}'),
  ('VCT', 'Saint Vincent and the Grenadines', '{}'),
  ('WSM', 'Samoa', '{}'),
  ('SMR', 'San Marino', '{}'),
  ('STP', 'São Tomé and Príncipe', array['sao tome and principe']),
  ('SAU', 'Saudi Arabia', '{}'),
  ('SEN', 'Senegal', '{}'),
  ('SRB', 'Serbia', '{}'),
  ('SYC', 'Seychelles', '{}'),
  ('SLE', 'Sierra Leone', '{}'),
  ('SGP', 'Singapore', '{}'),
  ('SXM', 'Sint Maarten', '{}'),
  ('SVK', 'Slovakia', '{}'),
  ('SVN', 'Slovenia', '{}'),
  ('SLB', 'Solomon Islands', '{}'),
  ('SOM', 'Somalia', '{}'),
  ('ZAF', 'South Africa', '{}'),
  ('SGS', 'South Georgia and the South Sandwich Islands', '{}'),
  ('SSD', 'South Sudan', '{}'),
  ('ESP', 'Spain', '{}'),
  ('LKA', 'Sri Lanka', '{}'),
  ('SDN', 'Sudan', '{}'),
  ('SUR', 'Suriname', '{}'),
  ('SJM', 'Svalbard and Jan Mayen', '{}'),
  ('SWE', 'Sweden', '{}'),
  ('CHE', 'Switzerland', '{}'),
  ('SYR', 'Syria', '{}'),
  ('TWN', 'Taiwan', '{}'),
  ('TJK', 'Tajikistan', '{}'),
  ('TZA', 'Tanzania', '{}'),
  ('THA', 'Thailand', '{}'),
  ('TLS', 'Timor-Leste', array['east timor']),
  ('TGO', 'Togo', '{}'),
  ('TKL', 'Tokelau', '{}'),
  ('TON', 'Tonga', '{}'),
  ('TTO', 'Trinidad and Tobago', '{}'),
  ('TUN', 'Tunisia', '{}'),
  ('TUR', 'Turkey', array['türkiye','turkiye']),
  ('TKM', 'Turkmenistan', '{}'),
  ('TCA', 'Turks and Caicos Islands', '{}'),
  ('TUV', 'Tuvalu', '{}'),
  ('UGA', 'Uganda', '{}'),
  ('UKR', 'Ukraine', '{}'),
  ('ARE', 'United Arab Emirates', array['uae']),
  ('GBR', 'United Kingdom', array['england','scotland','wales','northern ireland','great britain','uk']),
  ('USA', 'United States', array['united states of america','usa','us']),
  ('UMI', 'United States Minor Outlying Islands', '{}'),
  ('URY', 'Uruguay', '{}'),
  ('UZB', 'Uzbekistan', '{}'),
  ('VUT', 'Vanuatu', '{}'),
  ('VEN', 'Venezuela', '{}'),
  ('VNM', 'Vietnam', array['viet nam']),
  ('VGB', 'British Virgin Islands', '{}'),
  ('VIR', 'U.S. Virgin Islands', array['united states virgin islands']),
  ('WLF', 'Wallis and Futuna', '{}'),
  ('ESH', 'Western Sahara', '{}'),
  ('YEM', 'Yemen', '{}'),
  ('ZMB', 'Zambia', '{}'),
  ('ZWE', 'Zimbabwe', '{}')
on conflict (code) do nothing;
