-- Enrich public.teams with TGBID + EspnId carried over from the legacy
-- mc/data/teams.json store (now retired; Supabase teams is the single source).
-- Additive + idempotent: matches existing rows on (league, fanbase, mascot);
-- never inserts or drops. teams.json had no code/conference, so it cannot define
-- identity — the table stays canonical (team_key = LEAGUE:CODE is FK-referenced).

alter table public.teams add column if not exists tgbid   int;
alter table public.teams add column if not exists espn_id text;

update public.teams t set
  tgbid   = j.tgbid,
  espn_id = nullif(j.espn_id, '')
from (values
  ('NFL', 'San Francisco', '49ers', 99, '25'),
  ('NFL', 'Chicago', 'Bears', 100, '3'),
  ('NFL', 'Cincinnati', 'Bengals', 101, '4'),
  ('NFL', 'Buffalo', 'Bills', 102, '2'),
  ('NFL', 'Denver', 'Broncos', 103, '7'),
  ('NFL', 'Cleveland', 'Browns', 104, '5'),
  ('NFL', 'Tampa Bay', 'Buccaneers', 105, '27'),
  ('NFL', 'Arizona', 'Cardinals', 106, '22'),
  ('NFL', 'Los Angeles', 'Chargers', 107, '24'),
  ('NFL', 'Kansas City', 'Chiefs', 108, '12'),
  ('NFL', 'Indianapolis', 'Colts', 109, '11'),
  ('NFL', 'Washington', 'Commanders', 110, '28'),
  ('NFL', 'Dallas', 'Cowboys', 111, '6'),
  ('NFL', 'Miami', 'Dolphins', 112, '15'),
  ('NFL', 'Philadelphia', 'Eagles', 113, '21'),
  ('NFL', 'Atlanta', 'Falcons', 114, '1'),
  ('NFL', 'New York', 'Giants', 115, '19'),
  ('NFL', 'Jacksonville', 'Jaguars', 116, '30'),
  ('NFL', 'New York', 'Jets', 117, '20'),
  ('NFL', 'Detroit', 'Lions', 118, '8'),
  ('NFL', 'Green Bay', 'Packers', 119, '9'),
  ('NFL', 'Carolina', 'Panthers', 120, '29'),
  ('NFL', 'New England', 'Patriots', 121, '17'),
  ('NFL', 'Las Vegas', 'Raiders', 122, '13'),
  ('NFL', 'Los Angeles', 'Rams', 123, '14'),
  ('NFL', 'Baltimore', 'Ravens', 124, '33'),
  ('NFL', 'New Orleans', 'Saints', 1, '18'),
  ('NFL', 'Seattle', 'Seahawks', 2, '26'),
  ('NFL', 'Pittsburgh', 'Steelers', 3, '23'),
  ('NFL', 'Houston', 'Texans', 4, '34'),
  ('NFL', 'Tennessee', 'Titans', 5, '10'),
  ('NFL', 'Minnesota', 'Vikings', 6, '16'),
  ('NBA', 'Philadelphia', '76ers', 7, '20'),
  ('NBA', 'Milwaukee', 'Bucks', 8, '15'),
  ('NBA', 'Chicago', 'Bulls', 9, '4'),
  ('NBA', 'Cleveland', 'Cavaliers', 10, '5'),
  ('NBA', 'Boston', 'Celtics', 11, '2'),
  ('NBA', 'Los Angeles', 'Clippers', 12, '12'),
  ('NBA', 'Memphis', 'Grizzlies', 13, '29'),
  ('NBA', 'Atlanta', 'Hawks', 14, '1'),
  ('NBA', 'Miami', 'Heat', 15, '14'),
  ('NBA', 'Charlotte', 'Hornets', 16, '30'),
  ('NBA', 'Utah', 'Jazz', 17, '26'),
  ('NBA', 'Sacramento', 'Kings', 18, '23'),
  ('NBA', 'New York', 'Knicks', 19, '18'),
  ('NBA', 'Los Angeles', 'Lakers', 20, '13'),
  ('NBA', 'Orlando', 'Magic', 21, '19'),
  ('NBA', 'Dallas', 'Mavericks', 22, '6'),
  ('NBA', 'Brooklyn', 'Nets', 23, '17'),
  ('NBA', 'Denver', 'Nuggets', 24, '7'),
  ('NBA', 'Indiana', 'Pacers', 25, '11'),
  ('NBA', 'New Orleans', 'Pelicans', 26, '3'),
  ('NBA', 'Detroit', 'Pistons', 27, '8'),
  ('NBA', 'Toronto', 'Raptors', 28, '28'),
  ('NBA', 'Houston', 'Rockets', 29, '10'),
  ('NBA', 'San Antonio', 'Spurs', 30, '24'),
  ('NBA', 'Phoenix', 'Suns', 31, '21'),
  ('NBA', 'Oklahoma City', 'Thunder', 32, '25'),
  ('NBA', 'Minnesota', 'Timberwolves', 33, '16'),
  ('NBA', 'Portland', 'Trail Blazers', 34, '22'),
  ('NBA', 'Golden State', 'Warriors', 35, '9'),
  ('NBA', 'Washington', 'Wizards', 36, '27'),
  ('NHL', 'Colorado', 'Avalanche', 37, '17'),
  ('NHL', 'Chicago', 'Blackhawks', 38, '4'),
  ('NHL', 'Columbus', 'Blue Jackets', 39, '29'),
  ('NHL', 'St. Louis', 'Blues', 40, '19'),
  ('NHL', 'Boston', 'Bruins', 41, '1'),
  ('NHL', 'Montreal', 'Canadiens', 42, '10'),
  ('NHL', 'Vancouver', 'Canucks', 43, '22'),
  ('NHL', 'Washington', 'Capitals', 44, '23'),
  ('NHL', 'New Jersey', 'Devils', 45, '11'),
  ('NHL', 'Anaheim', 'Ducks', 46, '25'),
  ('NHL', 'Calgary', 'Flames', 47, '3'),
  ('NHL', 'Philadelphia', 'Flyers', 48, '15'),
  ('NHL', 'Vegas', 'Golden Knights', 49, '37'),
  ('NHL', 'Carolina', 'Hurricanes', 50, '7'),
  ('NHL', 'New York', 'Islanders', 51, '12'),
  ('NHL', 'Winnipeg', 'Jets', 52, '28'),
  ('NHL', 'Los Angeles', 'Kings', 53, '8'),
  ('NHL', 'Seattle', 'Kraken', 54, '124292'),
  ('NHL', 'Tampa Bay', 'Lightning', 55, '20'),
  ('NHL', 'Utah', 'Mammoth', 56, '129764'),
  ('NHL', 'Toronto', 'Maple Leafs', 57, '21'),
  ('NHL', 'Edmonton', 'Oilers', 58, '6'),
  ('NHL', 'Florida', 'Panthers', 59, '26'),
  ('NHL', 'Pittsburgh', 'Penguins', 60, '16'),
  ('NHL', 'Nashville', 'Predators', 61, '27'),
  ('NHL', 'New York', 'Rangers', 62, '13'),
  ('NHL', 'Detroit', 'Red Wings', 63, '5'),
  ('NHL', 'Buffalo', 'Sabres', 64, '2'),
  ('NHL', 'Ottawa', 'Senators', 65, '14'),
  ('NHL', 'San Jose', 'Sharks', 66, '18'),
  ('NHL', 'Dallas', 'Stars', 67, '9'),
  ('NHL', 'Minnesota', 'Wild', 68, '30'),
  ('MLB', 'Los Angeles', 'Angels', 69, '3'),
  ('MLB', 'Houston', 'Astros', 70, '18'),
  ('MLB', 'Athletics', 'Athletics', 71, '11'),
  ('MLB', 'Toronto', 'Blue Jays', 72, '14'),
  ('MLB', 'Atlanta', 'Braves', 73, '15'),
  ('MLB', 'Milwaukee', 'Brewers', 74, '8'),
  ('MLB', 'St. Louis', 'Cardinals', 75, '24'),
  ('MLB', 'Chicago', 'Cubs', 76, '16'),
  ('MLB', 'Arizona', 'Diamondbacks', 77, '29'),
  ('MLB', 'Los Angeles', 'Dodgers', 78, '19'),
  ('MLB', 'San Francisco', 'Giants', 79, '26'),
  ('MLB', 'Cleveland', 'Guardians', 80, '5'),
  ('MLB', 'Seattle', 'Mariners', 81, '12'),
  ('MLB', 'Miami', 'Marlins', 82, '28'),
  ('MLB', 'New York', 'Mets', 83, '21'),
  ('MLB', 'Washington', 'Nationals', 84, '20'),
  ('MLB', 'Baltimore', 'Orioles', 85, '1'),
  ('MLB', 'San Diego', 'Padres', 86, '25'),
  ('MLB', 'Philadelphia', 'Phillies', 87, '22'),
  ('MLB', 'Pittsburgh', 'Pirates', 88, '23'),
  ('MLB', 'Texas', 'Rangers', 89, '13'),
  ('MLB', 'Tampa Bay', 'Rays', 90, '30'),
  ('MLB', 'Boston', 'Red Sox', 91, '2'),
  ('MLB', 'Cincinnati', 'Reds', 92, '17'),
  ('MLB', 'Colorado', 'Rockies', 93, '27'),
  ('MLB', 'Kansas City', 'Royals', 94, '7'),
  ('MLB', 'Detroit', 'Tigers', 95, '6'),
  ('MLB', 'Minnesota', 'Twins', 96, '9'),
  ('MLB', 'Chicago', 'White Sox', 97, '4'),
  ('MLB', 'New York', 'Yankees', 98, '10')
) as j(league, fanbase, mascot, tgbid, espn_id)
where lower(t.league)  = lower(j.league)
  and lower(t.fanbase) = lower(j.fanbase)
  and lower(t.mascot)  = lower(j.mascot);

-- TGBID is a permanent unique key (where present). NCAAF/other rows not in
-- teams.json keep NULL, so the uniqueness is partial.
create unique index if not exists teams_tgbid_uidx
  on public.teams (tgbid) where tgbid is not null;

comment on column public.teams.tgbid is
  'Permanent unique The Game Bureau team id (carried from legacy teams.json TGBID).';
comment on column public.teams.espn_id is
  'ESPN numeric team id (carried from legacy teams.json EspnId).';
