-- Generated from site/assets/teams/teams.json by seed_teams_from_json.mjs
-- 608 rows · 4 leagues
-- Safe to re-run: uses ON CONFLICT DO UPDATE.

insert into public.teams
  (league, conference, code, full_name, first_name, fanbase, mascot, sport, shell, stripe, mask, league_sort, team_sort)
values
  ('NFL', '', 'ARI', 'Arizona Cardinals', 'Arizona', 'Arizona', 'Cardinals', 'football', '#FFFFFF', '#97233F', '#A5ACAF', 0, 0),
  ('NFL', '', 'ATL', 'Atlanta Falcons', 'Atlanta', 'Atlanta', 'Falcons', 'football', '#000000', '#A71930', '#A5ACAF', 0, 1),
  ('NFL', '', 'BAL', 'Baltimore Ravens', 'Baltimore', 'Baltimore', 'Ravens', 'football', '#241773', '#9E7C0C', '#000000', 0, 2),
  ('NFL', '', 'BUF', 'Buffalo Bills', 'Buffalo', 'Buffalo', 'Bills', 'football', '#FFFFFF', '#C60C30', '#00338D', 0, 3),
  ('NFL', '', 'CAR', 'Carolina Panthers', 'Carolina', 'Carolina', 'Panthers', 'football', '#BFC0BF', '#0085CA', '#101820', 0, 4),
  ('NFL', '', 'CHI', 'Chicago Bears', 'Chicago', 'Chicago', 'Bears', 'football', '#0B162A', '#C83803', '#BFC0BF', 0, 5),
  ('NFL', '', 'CIN', 'Cincinnati Bengals', 'Cincinnati', 'Cincinnati', 'Bengals', 'football', '#FB4F14', '#000000', '#FFFFFF', 0, 6),
  ('NFL', '', 'CLE', 'Cleveland Browns', 'Cleveland', 'Cleveland', 'Browns', 'football', '#FF3C00', '#311D00', '#BFC0BF', 0, 7),
  ('NFL', '', 'DAL', 'Dallas Cowboys', 'Dallas', 'Dallas', 'Cowboys', 'football', '#869397', '#041E42', '#E2DFDF', 0, 8),
  ('NFL', '', 'DEN', 'Denver Broncos', 'Denver', 'Denver', 'Broncos', 'football', '#0166B3', '#FB4F14', '#FFFFFF', 0, 9),
  ('NFL', '', 'DET', 'Detroit Lions', 'Detroit', 'Detroit', 'Lions', 'football', '#B0B7BC', '#0076B6', '#0076B6', 0, 10),
  ('NFL', '', 'GB', 'Green Bay Packers', 'Green Bay', 'Green Bay', 'Packers', 'football', '#FFB612', '#203731', '#FFFFFF', 0, 11),
  ('NFL', '', 'HOU', 'Houston Texans', 'Houston', 'Houston', 'Texans', 'football', '#03202F', '#A71930', '#FFFFFF', 0, 12),
  ('NFL', '', 'IND', 'Indianapolis Colts', 'Indianapolis', 'Indianapolis', 'Colts', 'football', '#FFFFFF', '#002C5F', '#A2AAAD', 0, 13),
  ('NFL', '', 'JAX', 'Jacksonville Jaguars', 'Jacksonville', 'Jacksonville', 'Jaguars', 'football', '#101820', '#006778', '#9F792C', 0, 14),
  ('NFL', '', 'KC', 'Kansas City Chiefs', 'Kansas City', 'Kansas City', 'Chiefs', 'football', '#E31837', '#E31837', '#FFFFFF', 0, 15),
  ('NFL', '', 'LV', 'Las Vegas Raiders', 'Las Vegas', 'Las Vegas', 'Raiders', 'football', '#A5ACAF', '#000000', '#575757', 0, 16),
  ('NFL', '', 'LAC', 'Los Angeles Chargers', 'Los Angeles', 'Los Angeles', 'Chargers', 'football', '#FFFFFF', '#FFC20E', '#0080C6', 0, 17),
  ('NFL', '', 'LAR', 'Los Angeles Rams', 'Los Angeles', 'Los Angeles', 'Rams', 'football', '#003594', '#FFD100', '#FFFFFF', 0, 18),
  ('NFL', '', 'MIA', 'Miami Dolphins', 'Miami', 'Miami', 'Dolphins', 'football', '#FFFFFF', '#FC4C02', '#008E97', 0, 19),
  ('NFL', '', 'MIN', 'Minnesota Vikings', 'Minnesota', 'Minnesota', 'Vikings', 'football', '#4F2683', '#FFC62F', '#FFFFFF', 0, 20),
  ('NFL', '', 'NE', 'New England Patriots', 'New England', 'New England', 'Patriots', 'football', '#002244', '#C60C30', '#B0B7BC', 0, 21),
  ('NFL', '', 'NO', 'New Orleans Saints', 'New Orleans', 'New Orleans', 'Saints', 'football', '#D3BC8D', '#101820', '#FFFFFF', 0, 22),
  ('NFL', '', 'NYG', 'New York Giants', 'New York', 'New York', 'Giants', 'football', '#0B2265', '#A71930', '#FFFFFF', 0, 23),
  ('NFL', '', 'NYJ', 'New York Jets', 'New York', 'New York', 'Jets', 'football', '#FFFFFF', '#125740', '#FFFFFF', 0, 24),
  ('NFL', '', 'PHI', 'Philadelphia Eagles', 'Philadelphia', 'Philadelphia', 'Eagles', 'football', '#339C5E', '#FFFFFF', '#A5ACAF', 0, 25),
  ('NFL', '', 'PIT', 'Pittsburgh Steelers', 'Pittsburgh', 'Pittsburgh', 'Steelers', 'football', '#101820', '#FFB612', '#FFFFFF', 0, 26),
  ('NFL', '', 'SF', 'San Francisco 49ers', 'San Francisco', 'San Francisco', '49ers', 'football', '#B3995D', '#AA0000', '#FFFFFF', 0, 27),
  ('NFL', '', 'SEA', 'Seattle Seahawks', 'Seattle', 'Seattle', 'Seahawks', 'football', '#A5ACAF', '#07317B', '#69BE28', 0, 28),
  ('NFL', '', 'TB', 'Tampa Bay Buccaneers', 'Tampa Bay', 'Tampa Bay', 'Buccaneers', 'football', '#FFFFFF', '#D50A0A', '#FF7900', 0, 29),
  ('NFL', '', 'TEN', 'Tennessee Titans', 'Tennessee', 'Tennessee', 'Titans', 'football', '#FFFFFF', '#4B92DB', '#C8102E', 0, 30),
  ('NFL', '', 'WSH', 'Washington Commanders', 'Washington', 'Washington', 'Commanders', 'football', '#5A1414', '#FFB612', '#FFFFFF', 0, 31),
  ('MLB', '', 'ARI', 'Arizona Diamondbacks', 'Arizona', 'Arizona', 'Diamondbacks', 'baseball', '#AA182C', '#000000', '#FFFFFF', 1, 0),
  ('MLB', '', 'ATH', 'Athletics', 'Athletics', 'Athletics', 'Athletics', 'baseball', '#003831', '#EFB21E', '#FFFFFF', 1, 1),
  ('MLB', '', 'ATL', 'Atlanta Braves', 'Atlanta', 'Atlanta', 'Braves', 'baseball', '#0C2340', '#BA0C2F', '#FFFFFF', 1, 2),
  ('MLB', '', 'BAL', 'Baltimore Orioles', 'Baltimore', 'Baltimore', 'Orioles', 'baseball', '#DF4601', '#000000', '#FFFFFF', 1, 3),
  ('MLB', '', 'BOS', 'Boston Red Sox', 'Boston', 'Boston', 'Red Sox', 'baseball', '#0D2B56', '#BD3039', '#FFFFFF', 1, 4),
  ('MLB', '', 'CHC', 'Chicago Cubs', 'Chicago', 'Chicago', 'Cubs', 'baseball', '#0E3386', '#CC3433', '#FFFFFF', 1, 5),
  ('MLB', '', 'CHW', 'Chicago White Sox', 'Chicago', 'Chicago', 'White Sox', 'baseball', '#000000', '#C4CED4', '#FFFFFF', 1, 6),
  ('MLB', '', 'CIN', 'Cincinnati Reds', 'Cincinnati', 'Cincinnati', 'Reds', 'baseball', '#C6011F', '#FFFFFF', '#FFFFFF', 1, 7),
  ('MLB', '', 'CLE', 'Cleveland Guardians', 'Cleveland', 'Cleveland', 'Guardians', 'baseball', '#002B5C', '#E31937', '#FFFFFF', 1, 8),
  ('MLB', '', 'COL', 'Colorado Rockies', 'Colorado', 'Colorado', 'Rockies', 'baseball', '#33006F', '#000000', '#FFFFFF', 1, 9),
  ('MLB', '', 'DET', 'Detroit Tigers', 'Detroit', 'Detroit', 'Tigers', 'baseball', '#0A2240', '#FF4713', '#FFFFFF', 1, 10),
  ('MLB', '', 'HOU', 'Houston Astros', 'Houston', 'Houston', 'Astros', 'baseball', '#002D62', '#EB6E1F', '#FFFFFF', 1, 11),
  ('MLB', '', 'KC', 'Kansas City Royals', 'Kansas City', 'Kansas City', 'Royals', 'baseball', '#004687', '#7AB2DD', '#FFFFFF', 1, 12),
  ('MLB', '', 'LAA', 'Los Angeles Angels', 'Los Angeles', 'Los Angeles', 'Angels', 'baseball', '#BA0021', '#C4CED4', '#FFFFFF', 1, 13),
  ('MLB', '', 'LAD', 'Los Angeles Dodgers', 'Los Angeles', 'Los Angeles', 'Dodgers', 'baseball', '#005A9C', '#FFFFFF', '#FFFFFF', 1, 14),
  ('MLB', '', 'MIA', 'Miami Marlins', 'Miami', 'Miami', 'Marlins', 'baseball', '#00A3E0', '#000000', '#FFFFFF', 1, 15),
  ('MLB', '', 'MIL', 'Milwaukee Brewers', 'Milwaukee', 'Milwaukee', 'Brewers', 'baseball', '#13294B', '#FFC72C', '#FFFFFF', 1, 16),
  ('MLB', '', 'MIN', 'Minnesota Twins', 'Minnesota', 'Minnesota', 'Twins', 'baseball', '#031F40', '#E20E32', '#FFFFFF', 1, 17),
  ('MLB', '', 'NYM', 'New York Mets', 'New York', 'New York', 'Mets', 'baseball', '#002D72', '#FF5910', '#FFFFFF', 1, 18),
  ('MLB', '', 'NYY', 'New York Yankees', 'New York', 'New York', 'Yankees', 'baseball', '#132448', '#C4CED4', '#FFFFFF', 1, 19),
  ('MLB', '', 'PHI', 'Philadelphia Phillies', 'Philadelphia', 'Philadelphia', 'Phillies', 'baseball', '#E81828', '#003278', '#FFFFFF', 1, 20),
  ('MLB', '', 'PIT', 'Pittsburgh Pirates', 'Pittsburgh', 'Pittsburgh', 'Pirates', 'baseball', '#000000', '#FDB827', '#FFFFFF', 1, 21),
  ('MLB', '', 'SD', 'San Diego Padres', 'San Diego', 'San Diego', 'Padres', 'baseball', '#2F241D', '#FFC425', '#FFFFFF', 1, 22),
  ('MLB', '', 'SF', 'San Francisco Giants', 'San Francisco', 'San Francisco', 'Giants', 'baseball', '#000000', '#FD5A1E', '#FFFFFF', 1, 23),
  ('MLB', '', 'SEA', 'Seattle Mariners', 'Seattle', 'Seattle', 'Mariners', 'baseball', '#005C5C', '#0C2C56', '#FFFFFF', 1, 24),
  ('MLB', '', 'STL', 'St. Louis Cardinals', 'St. Louis', 'St. Louis', 'Cardinals', 'baseball', '#BE0A14', '#001541', '#FFFFFF', 1, 25),
  ('MLB', '', 'TB', 'Tampa Bay Rays', 'Tampa Bay', 'Tampa Bay', 'Rays', 'baseball', '#092C5C', '#8FBCE6', '#FFFFFF', 1, 26),
  ('MLB', '', 'TEX', 'Texas Rangers', 'Texas', 'Texas', 'Rangers', 'baseball', '#003278', '#C0111F', '#FFFFFF', 1, 27),
  ('MLB', '', 'TOR', 'Toronto Blue Jays', 'Toronto', 'Toronto', 'Blue Jays', 'baseball', '#134A8E', '#6CACE5', '#FFFFFF', 1, 28),
  ('MLB', '', 'WSH', 'Washington Nationals', 'Washington', 'Washington', 'Nationals', 'baseball', '#AB0003', '#11225B', '#FFFFFF', 1, 29),
  ('NBA', '', 'ATL', 'Atlanta Hawks', 'Atlanta', 'Atlanta', 'Hawks', 'basketball', '#C8102E', '#FDB927', '#FFFFFF', 2, 0),
  ('NBA', '', 'BOS', 'Boston Celtics', 'Boston', 'Boston', 'Celtics', 'basketball', '#008348', '#FFFFFF', '#FFFFFF', 2, 1),
  ('NBA', '', 'BKN', 'Brooklyn Nets', 'Brooklyn', 'Brooklyn', 'Nets', 'basketball', '#000000', '#FFFFFF', '#FFFFFF', 2, 2),
  ('NBA', '', 'CHA', 'Charlotte Hornets', 'Charlotte', 'Charlotte', 'Hornets', 'basketball', '#008CA8', '#1D1060', '#FFFFFF', 2, 3),
  ('NBA', '', 'CHI', 'Chicago Bulls', 'Chicago', 'Chicago', 'Bulls', 'basketball', '#CE1141', '#000000', '#FFFFFF', 2, 4),
  ('NBA', '', 'CLE', 'Cleveland Cavaliers', 'Cleveland', 'Cleveland', 'Cavaliers', 'basketball', '#860038', '#BC945C', '#FFFFFF', 2, 5),
  ('NBA', '', 'DAL', 'Dallas Mavericks', 'Dallas', 'Dallas', 'Mavericks', 'basketball', '#0064B1', '#BBC4CA', '#FFFFFF', 2, 6),
  ('NBA', '', 'DEN', 'Denver Nuggets', 'Denver', 'Denver', 'Nuggets', 'basketball', '#0E2240', '#FEC524', '#FFFFFF', 2, 7),
  ('NBA', '', 'DET', 'Detroit Pistons', 'Detroit', 'Detroit', 'Pistons', 'basketball', '#1D428A', '#C8102E', '#FFFFFF', 2, 8),
  ('NBA', '', 'GS', 'Golden State Warriors', 'Golden State', 'Golden State', 'Warriors', 'basketball', '#FDB927', '#1D428A', '#FFFFFF', 2, 9),
  ('NBA', '', 'HOU', 'Houston Rockets', 'Houston', 'Houston', 'Rockets', 'basketball', '#CE1141', '#000000', '#FFFFFF', 2, 10),
  ('NBA', '', 'IND', 'Indiana Pacers', 'Indiana', 'Indiana', 'Pacers', 'basketball', '#0C2340', '#FFD520', '#FFFFFF', 2, 11),
  ('NBA', '', 'LAC', 'LA Clippers', 'LA', 'LA', 'Clippers', 'basketball', '#12173F', '#C8102E', '#FFFFFF', 2, 12),
  ('NBA', '', 'LAL', 'Los Angeles Lakers', 'Los Angeles', 'Los Angeles', 'Lakers', 'basketball', '#552583', '#FDB927', '#FFFFFF', 2, 13),
  ('NBA', '', 'MEM', 'Memphis Grizzlies', 'Memphis', 'Memphis', 'Grizzlies', 'basketball', '#5D76A9', '#12173F', '#FFFFFF', 2, 14),
  ('NBA', '', 'MIA', 'Miami Heat', 'Miami', 'Miami', 'Heat', 'basketball', '#98002E', '#000000', '#FFFFFF', 2, 15),
  ('NBA', '', 'MIL', 'Milwaukee Bucks', 'Milwaukee', 'Milwaukee', 'Bucks', 'basketball', '#00471B', '#EEE1C6', '#FFFFFF', 2, 16),
  ('NBA', '', 'MIN', 'Minnesota Timberwolves', 'Minnesota', 'Minnesota', 'Timberwolves', 'basketball', '#266092', '#79BC43', '#FFFFFF', 2, 17),
  ('NBA', '', 'NO', 'New Orleans Pelicans', 'New Orleans', 'New Orleans', 'Pelicans', 'basketball', '#0A2240', '#B4975A', '#FFFFFF', 2, 18),
  ('NBA', '', 'NY', 'New York Knicks', 'New York', 'New York', 'Knicks', 'basketball', '#1D428A', '#F58426', '#FFFFFF', 2, 19),
  ('NBA', '', 'OKC', 'Oklahoma City Thunder', 'Oklahoma City', 'Oklahoma City', 'Thunder', 'basketball', '#007AC1', '#EF3B24', '#FFFFFF', 2, 20),
  ('NBA', '', 'ORL', 'Orlando Magic', 'Orlando', 'Orlando', 'Magic', 'basketball', '#0150B5', '#9CA0A3', '#FFFFFF', 2, 21),
  ('NBA', '', 'PHI', 'Philadelphia 76ers', 'Philadelphia', 'Philadelphia', '76ers', 'basketball', '#1D428A', '#E01234', '#FFFFFF', 2, 22),
  ('NBA', '', 'PHX', 'Phoenix Suns', 'Phoenix', 'Phoenix', 'Suns', 'basketball', '#29127A', '#E56020', '#FFFFFF', 2, 23),
  ('NBA', '', 'POR', 'Portland Trail Blazers', 'Portland', 'Portland', 'Trail Blazers', 'basketball', '#E03A3E', '#000000', '#FFFFFF', 2, 24),
  ('NBA', '', 'SAC', 'Sacramento Kings', 'Sacramento', 'Sacramento', 'Kings', 'basketball', '#5A2D81', '#6A7A82', '#FFFFFF', 2, 25),
  ('NBA', '', 'SA', 'San Antonio Spurs', 'San Antonio', 'San Antonio', 'Spurs', 'basketball', '#000000', '#C4CED4', '#FFFFFF', 2, 26),
  ('NBA', '', 'TOR', 'Toronto Raptors', 'Toronto', 'Toronto', 'Raptors', 'basketball', '#D91244', '#000000', '#FFFFFF', 2, 27),
  ('NBA', '', 'UTAH', 'Utah Jazz', 'Utah', 'Utah', 'Jazz', 'basketball', '#4E008E', '#79A3DC', '#FFFFFF', 2, 28),
  ('NBA', '', 'WSH', 'Washington Wizards', 'Washington', 'Washington', 'Wizards', 'basketball', '#E31837', '#002B5C', '#FFFFFF', 2, 29),
  ('NCAAF', '', 'AAMU', 'Alabama A&M Bulldogs', 'Alabama A&M', 'Alabama A&M', 'Bulldogs', 'football', '#790000', '#FFFFFF', '#FFFFFF', 3, 0),
  ('NCAAF', '', 'ABSU', 'Albany State Golden Rams', 'Albany State', 'Albany State', 'Golden Rams', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 1),
  ('NCAAF', '', 'ACU', 'Abilene Christian Wildcats', 'Abilene Christian', 'Abilene Christian', 'Wildcats', 'football', '#592D82', '#B1B3B3', '#FFFFFF', 3, 2),
  ('NCAAF', '', 'ADR', 'Adrian Bulldogs', 'Adrian', 'Adrian', 'Bulldogs', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 3),
  ('NCAAF', '', 'ADSU', 'Adams State Grizzlies', 'Adams State', 'Adams State', 'Grizzlies', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 4),
  ('NCAAF', '', 'AGSU', 'Angelo State Rams', 'Angelo State', 'Angelo State', 'Rams', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 5),
  ('NCAAF', '', 'AIC', 'American International Yellow Jackets', 'American International', 'American International', 'Yellow Jackets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 6),
  ('NCAAF', '', 'ALBR', 'Albright Lions', 'Albright', 'Albright', 'Lions', 'football', '#C82E48', '#000000', '#FFFFFF', 3, 7),
  ('NCAAF', '', 'ALCN', 'Alcorn State Braves', 'Alcorn State', 'Alcorn State', 'Braves', 'football', '#4B0058', '#46166A', '#FFFFFF', 3, 8),
  ('NCAAF', '', 'ALFR', 'Alfred Saxons', 'Alfred', 'Alfred', 'Saxons', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 9),
  ('NCAAF', '', 'ALLG', 'Allegheny Gators', 'Allegheny', 'Allegheny', 'Gators', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 10),
  ('NCAAF', '', 'ALNU', 'Allen Yellow Jackets', 'Allen', 'Allen', 'Yellow Jackets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 11),
  ('NCAAF', '', 'ALST', 'Alabama State Hornets', 'Alabama State', 'Alabama State', 'Hornets', 'football', '#E9A900', '#0A0A0A', '#FFFFFF', 3, 12),
  ('NCAAF', '', 'AMH', 'Amherst Mammoths', 'Amherst', 'Amherst', 'Mammoths', 'football', '#3F1F69', '#FFFFFF', '#FFFFFF', 3, 13),
  ('NCAAF', '', 'ANIN', 'Anderson (IN) Ravens', 'Anderson (IN)', 'Anderson (IN)', 'Ravens', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 14),
  ('NCAAF', '', 'ANMR', 'Anna Maria Amcats', 'Anna Maria', 'Anna Maria', 'Amcats', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 15),
  ('NCAAF', '', 'APSU', 'Austin Peay Governors', 'Austin Peay', 'Austin Peay', 'Governors', 'football', '#8E0B0B', '#FFFFFF', '#FFFFFF', 3, 16),
  ('NCAAF', '', 'ARTE', 'Arkansas Tech Wonder Boys', 'Arkansas Tech', 'Arkansas Tech', 'Wonder Boys', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 17),
  ('NCAAF', '', 'ASH', 'Ashland Eagles', 'Ashland', 'Ashland', 'Eagles', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 18),
  ('NCAAF', '', 'ASP', 'Assumption Greyhounds', 'Assumption', 'Assumption', 'Greyhounds', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 19),
  ('NCAAF', '', 'AUGC', 'Augustana (IL) Vikings', 'Augustana (IL)', 'Augustana (IL)', 'Vikings', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 20),
  ('NCAAF', '', 'AUGS', 'Augsburg Auggies', 'Augsburg', 'Augsburg', 'Auggies', 'football', '#74233D', '#A9A9AA', '#FFFFFF', 3, 21),
  ('NCAAF', '', 'AUR', 'Aurora Spartans', 'Aurora', 'Aurora', 'Spartans', 'football', '#00549F', '#000000', '#FFFFFF', 3, 22),
  ('NCAAF', '', 'AUS', 'Austin ''Roos', 'Austin', 'Austin', '''Roos', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 23),
  ('NCAAF', '', 'AUSD', 'Augustana University (SD) Vikings', 'Augustana University (SD)', 'Augustana University (SD)', 'Vikings', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 24),
  ('NCAAF', '', 'AVER', 'Averett Cougars', 'Averett', 'Averett', 'Cougars', 'football', '#012853', '#FDBB30', '#FFFFFF', 3, 25),
  ('NCAAF', '', 'AVILA', 'Avila University Eagles', 'Avila University', 'Avila University', 'Eagles', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 26),
  ('NCAAF', '', 'BAK', 'Baker University Baker', 'Baker University', 'Baker University', 'Baker', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 27),
  ('NCAAF', '', 'BATE', 'Bates Bobcats', 'Bates', 'Bates', 'Bobcats', 'football', '#A51E36', '#B2B3B2', '#FFFFFF', 3, 28),
  ('NCAAF', '', 'BBM', 'British Columbia British Col', 'British Columbia', 'British Columbia', 'British Col', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 29),
  ('NCAAF', '', 'BBU', 'Bloomsburg Huskies', 'Bloomsburg', 'Bloomsburg', 'Huskies', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 30),
  ('NCAAF', '', 'BCU', 'Bethune-Cookman Wildcats', 'Bethune-Cookman', 'Bethune-Cookman', 'Wildcats', 'football', '#7B1831', '#E9AA12', '#FFFFFF', 3, 31),
  ('NCAAF', '', 'BCWV', 'Bethany (WV) Bison', 'Bethany (WV)', 'Bethany (WV)', 'Bison', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 32),
  ('NCAAF', '', 'BELH', 'Belhaven Blazers', 'Belhaven', 'Belhaven', 'Blazers', 'football', '#215732', '#F2A900', '#FFFFFF', 3, 33),
  ('NCAAF', '', 'BELO', 'Beloit Buccaneers', 'Beloit', 'Beloit', 'Buccaneers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 34),
  ('NCAAF', '', 'BEN', 'Benedict Tigers', 'Benedict', 'Benedict', 'Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 35),
  ('NCAAF', '', 'BENT', 'Bentley Falcons', 'Bentley', 'Bentley', 'Falcons', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 36),
  ('NCAAF', '', 'BETHA', 'Bethany (Ks)', 'Bethany (KS)', 'Bethany (KS)', 'Bethany (Ks)', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 37),
  ('NCAAF', '', 'BETHTN', 'Bethel University Tennessee Wildcats', 'Bethel University Tennessee', 'Bethel University Tennessee', 'Wildcats', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 38),
  ('NCAAF', '', 'BHSU', 'Black Hills State Yellow Jackets', 'Black Hills State', 'Black Hills State', 'Yellow Jackets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 39),
  ('NCAAF', '', 'BLF', 'Bluffton Beavers', 'Bluffton', 'Bluffton', 'Beavers', 'football', '#46166A', '#FFFFFF', '#FFFFFF', 3, 40),
  ('NCAAF', '', 'BLU', 'BLUEFIELD Ramblin'' Rams', 'BLUEFIELD', 'BLUEFIELD', 'Ramblin'' Rams', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 41),
  ('NCAAF', '', 'BNIL', 'Benedictine (IL) Eagles', 'Benedictine (IL)', 'Benedictine (IL)', 'Eagles', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 42),
  ('NCAAF', '', 'BOW', 'Bowdoin Polar Bears', 'Bowdoin', 'Bowdoin', 'Polar Bears', 'football', '#FFFFFF', '#000000', '#FFFFFF', 3, 43),
  ('NCAAF', '', 'BOWE', 'Bowie State Bulldogs', 'Bowie State', 'Bowie State', 'Bulldogs', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 44),
  ('NCAAF', '', 'BRI', 'Bridgewater Eagles', 'Bridgewater', 'Bridgewater', 'Eagles', 'football', '#990022', '#8D724B', '#FFFFFF', 3, 45),
  ('NCAAF', '', 'BRIS', 'Bridgewater State Bears', 'Bridgewater State', 'Bridgewater State', 'Bears', 'football', '#BF2F38', '#000000', '#FFFFFF', 3, 46),
  ('NCAAF', '', 'BRWN', 'Brown Bears', 'Brown', 'Brown', 'Bears', 'football', '#411E09', '#949300', '#FFFFFF', 3, 47),
  ('NCAAF', '', 'BST', 'Bemidji State Beavers', 'Bemidji State', 'Bemidji State', 'Beavers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 48),
  ('NCAAF', '', 'BSU', 'Buffalo State Bengals', 'Buffalo State', 'Buffalo State', 'Bengals', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 49),
  ('NCAAF', '', 'BUCK', 'Bucknell Bison', 'Bucknell', 'Bucknell', 'Bison', 'football', '#000060', '#00316E', '#FFFFFF', 3, 50),
  ('NCAAF', '', 'BUT', 'Butler Bulldogs', 'Butler', 'Butler', 'Bulldogs', 'football', '#0D1361', '#00A3E0', '#FFFFFF', 3, 51),
  ('NCAAF', '', 'BVU', 'Buena Vista Beavers', 'Buena Vista', 'Buena Vista', 'Beavers', 'football', '#FEBA12', '#001440', '#FFFFFF', 3, 52),
  ('NCAAF', '', 'BW', 'Baldwin Wallace Yellow Jackets', 'Baldwin Wallace', 'Baldwin Wallace', 'Yellow Jackets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 53),
  ('NCAAF', '', 'CAM', 'Campbell Fighting Camels', 'Campbell', 'Campbell', 'Fighting Camels', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 54),
  ('NCAAF', '', 'CAPU', 'Capital Comets', 'Capital', 'Capital', 'Comets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 55),
  ('NCAAF', '', 'CAR', 'Carleton Knights', 'Carleton', 'Carleton', 'Knights', 'football', '#173A79', '#EDAC09', '#FFFFFF', 3, 56),
  ('NCAAF', '', 'CARK', 'Central Arkansas Bears', 'Central Arkansas', 'Central Arkansas', 'Bears', 'football', '#A7A9AC', '#8E959A', '#FFFFFF', 3, 57),
  ('NCAAF', '', 'CAT', 'Catawba Indians', 'Catawba', 'Catawba', 'Indians', 'football', '#0C233F', '#CB152F', '#FFFFFF', 3, 58),
  ('NCAAF', '', 'CATH', 'Catholic Cardinals', 'Catholic', 'Catholic', 'Cardinals', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 59),
  ('NCAAF', '', 'CC', 'Curry Colonels', 'Curry', 'Curry', 'Colonels', 'football', '#65448B', '#FFFFFF', '#FFFFFF', 3, 60),
  ('NCAAF', '', 'CCMN', 'Concordia (MN) Cobbers', 'Concordia (MN)', 'Concordia (MN)', 'Cobbers', 'football', '#701D45', '#FFFFFF', '#FFFFFF', 3, 61),
  ('NCAAF', '', 'CCO', 'Centre Colonels', 'Centre', 'Centre', 'Colonels', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 62),
  ('NCAAF', '', 'CCSU', 'Central Connecticut Blue Devils', 'Central Connecticut', 'Central Connecticut', 'Blue Devils', 'football', '#1B49A2', '#D1D5D8', '#FFFFFF', 3, 63),
  ('NCAAF', '', 'CCW', 'Carthage Firebirds', 'Carthage', 'Carthage', 'Firebirds', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 64),
  ('NCAAF', '', 'CGMU', 'Carnegie Mellon Tartans', 'Carnegie Mellon', 'Carnegie Mellon', 'Tartans', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 65),
  ('NCAAF', '', 'CHAD', 'Chadron State Eagles', 'Chadron State', 'Chadron State', 'Eagles', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 66),
  ('NCAAF', '', 'CHAP', 'Chapman Panthers', 'Chapman', 'Chapman', 'Panthers', 'football', '#AB1D38', '#000000', '#FFFFFF', 3, 67),
  ('NCAAF', '', 'CHI', 'Chicago Maroons', 'Chicago', 'Chicago', 'Maroons', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 68),
  ('NCAAF', '', 'CHSO', 'Charleston Southern Buccaneers', 'Charleston Southern', 'Charleston Southern', 'Buccaneers', 'football', '#2E3192', '#DED090', '#FFFFFF', 3, 69),
  ('NCAAF', '', 'CLBY', 'Colby White Mules', 'Colby', 'Colby', 'White Mules', 'football', '#012778', '#FFFFFF', '#FFFFFF', 3, 70),
  ('NCAAF', '', 'CLRN', 'Clarion Golden Eagles', 'Clarion', 'Clarion', 'Golden Eagles', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 71),
  ('NCAAF', '', 'CLU', 'Cal Lutheran Kingsmen', 'Cal Lutheran', 'Cal Lutheran', 'Kingsmen', 'football', '#3B2361', '#FEC223', '#FFFFFF', 3, 72),
  ('NCAAF', '', 'CMBS', 'Cumberlands Indians', 'Cumberlands', 'Cumberlands', 'Indians', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 73),
  ('NCAAF', '', 'CMIN', 'Colorado School of Mines Orediggers', 'Colorado School of Mines', 'Colorado School of Mines', 'Orediggers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 74),
  ('NCAAF', '', 'CMPBVIL', 'Campbellsville University Tigers', 'Campbellsville University', 'Campbellsville University', 'Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 75),
  ('NCAAF', '', 'CMS', 'Claremont Mudd Scripps Stags/Athenas', 'Claremont Mudd Scripps', 'Claremont Mudd Scripps', 'Stags/Athenas', 'football', '#981A31', '#FEBA15', '#FFFFFF', 3, 76),
  ('NCAAF', '', 'CN', 'Carson Newman Eagles', 'Carson Newman', 'Carson Newman', 'Eagles', 'football', '#F2682A', '#0C233F', '#FFFFFF', 3, 77),
  ('NCAAF', '', 'CNIA', 'Cornell (IA) Rams', 'Cornell (IA)', 'Cornell (IA)', 'Rams', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 78),
  ('NCAAF', '', 'CNSU', 'Central State Marauders', 'Central State', 'Central State', 'Marauders', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 79),
  ('NCAAF', '', 'COE', 'Coe Kohawks', 'Coe', 'Coe', 'Kohawks', 'football', '#881922', '#C8934A', '#FFFFFF', 3, 80),
  ('NCAAF', '', 'COLG', 'Colgate Raiders', 'Colgate', 'Colgate', 'Raiders', 'football', '#821019', '#FFFFFF', '#FFFFFF', 3, 81),
  ('NCAAF', '', 'COLU', 'Columbia Lions', 'Columbia', 'Columbia', 'Lions', 'football', '#7BA4DB', '#183863', '#FFFFFF', 3, 82),
  ('NCAAF', '', 'COMU', 'Colorado Mesa Mavericks', 'Colorado Mesa', 'Colorado Mesa', 'Mavericks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 83),
  ('NCAAF', '', 'CONC', 'Concord Mountain Lions', 'Concord', 'Concord', 'Mountain Lions', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 84),
  ('NCAAF', '', 'CONCONE', 'Concordia University Nebraska Clippers', 'Concordia University Nebraska', 'Concordia University Nebraska', 'Clippers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 85),
  ('NCAAF', '', 'COR', 'Cornell Big Red', 'Cornell', 'Cornell', 'Big Red', 'football', '#B31B1B', '#FFFFFF', '#FFFFFF', 3, 86),
  ('NCAAF', '', 'CP', 'Cal Poly Mustangs', 'Cal Poly', 'Cal Poly', 'Mustangs', 'football', '#1E4D2B', '#EED897', '#FFFFFF', 3, 87),
  ('NCAAF', '', 'CRU', 'Carroll (WI) Pioneers', 'Carroll (WI)', 'Carroll (WI)', 'Pioneers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 88),
  ('NCAAF', '', 'CRWN', 'Crown Polars', 'Crown', 'Crown', 'Polars', 'football', '#5C2F92', '#FFFFFF', '#FFFFFF', 3, 89),
  ('NCAAF', '', 'CSS', 'St. Scholastica Saints', 'St. Scholastica', 'St. Scholastica', 'Saints', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 90),
  ('NCAAF', '', 'CUC', 'Concordia Chicago Cougars', 'Concordia Chicago', 'Concordia Chicago', 'Cougars', 'football', '#572A31', '#FFC72E', '#FFFFFF', 3, 91),
  ('NCAAF', '', 'CULVE', 'Culver-Stockton College Wildcats', 'Culver-Stockton College', 'Culver-Stockton College', 'Wildcats', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 92),
  ('NCAAF', '', 'CUMBTN', 'Cumberland (TN) Bulldogs', 'Cumberland (TN)', 'Cumberland (TN)', 'Bulldogs', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 93),
  ('NCAAF', '', 'CUW', 'Concordia (WI) Falcons', 'Concordia (WI)', 'Concordia (WI)', 'Falcons', 'football', '#245699', '#B1B3B3', '#FFFFFF', 3, 94),
  ('NCAAF', '', 'CWAU', 'Central Washington Wildcats', 'Central Washington', 'Central Washington', 'Wildcats', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 95),
  ('NCAAF', '', 'DAKOT', 'Dakota State University Trojans', 'Dakota State University', 'Dakota State University', 'Trojans', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 96),
  ('NCAAF', '', 'DART', 'Dartmouth Big Green', 'Dartmouth', 'Dartmouth', 'Big Green', 'football', '#005730', '#000000', '#FFFFFF', 3, 97),
  ('NCAAF', '', 'DAV', 'Davidson Wildcats', 'Davidson', 'Davidson', 'Wildcats', 'football', '#000000', '#E51837', '#FFFFFF', 3, 98),
  ('NCAAF', '', 'DAY', 'Dayton Flyers', 'Dayton', 'Dayton', 'Flyers', 'football', '#004B8D', '#FFFFFF', '#FFFFFF', 3, 99),
  ('NCAAF', '', 'DBQ', 'Dubuque Spartans', 'Dubuque', 'Dubuque', 'Spartans', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 100),
  ('NCAAF', '', 'DEF', 'Defiance College Yellow Jackets', 'Defiance College', 'Defiance College', 'Yellow Jackets', 'football', '#4E2D8A', '#DED27C', '#FFFFFF', 3, 101),
  ('NCAAF', '', 'DEL', 'Delaware Blue Hens', 'Delaware', 'Delaware', 'Blue Hens', 'football', '#00539F', '#FFD200', '#FFFFFF', 3, 102),
  ('NCAAF', '', 'DIC', 'Dickinson State University Blue Hawks', 'Dickinson State University', 'Dickinson State University', 'Blue Hawks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 103),
  ('NCAAF', '', 'DKSN', 'Dickinson Red Devils', 'Dickinson', 'Dickinson', 'Red Devils', 'football', '#ED192D', '#000000', '#FFFFFF', 3, 104),
  ('NCAAF', '', 'DLST', 'Delta State Statesmen', 'Delta State', 'Delta State', 'Statesmen', 'football', '#00753E', '#000000', '#FFFFFF', 3, 105),
  ('NCAAF', '', 'DPU', 'DePauw Tigers', 'DePauw', 'DePauw', 'Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 106),
  ('NCAAF', '', 'DRKE', 'Drake Bulldogs', 'Drake', 'Drake', 'Bulldogs', 'football', '#005596', '#BEC0C2', '#FFFFFF', 3, 107),
  ('NCAAF', '', 'DSN', 'Denison Big Red', 'Denison', 'Denison', 'Big Red', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 108),
  ('NCAAF', '', 'DSU', 'Delaware State Hornets', 'Delaware State', 'Delaware State', 'Hornets', 'football', '#009CDB', '#D51C28', '#FFFFFF', 3, 109),
  ('NCAAF', '', 'DUQ', 'Duquesne Dukes', 'Duquesne', 'Duquesne', 'Dukes', 'football', '#002D62', '#B90B2E', '#FFFFFF', 3, 110),
  ('NCAAF', '', 'DWU', 'Dakota Wesleyan Tigers', 'Dakota Wesleyan', 'Dakota Wesleyan', 'Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 111),
  ('NCAAF', '', 'ECNU', 'East Central Tigers', 'East Central', 'East Central', 'Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 112),
  ('NCAAF', '', 'ECSU', 'Elizabeth City State Vikings', 'Elizabeth City State', 'Elizabeth City State', 'Vikings', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 113),
  ('NCAAF', '', 'EDBR', 'Edinboro Fighting Scots', 'Edinboro', 'Edinboro', 'Fighting Scots', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 114),
  ('NCAAF', '', 'EDW', 'Edward Waters Tigers', 'Edward Waters', 'Edward Waters', 'Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 115),
  ('NCAAF', '', 'EHC', 'Emory & Henry Wasps', 'Emory & Henry', 'Emory & Henry', 'Wasps', 'football', '#1E376D', '#DAAD27', '#FFFFFF', 3, 116),
  ('NCAAF', '', 'EIU', 'Eastern Illinois Panthers', 'Eastern Illinois', 'Eastern Illinois', 'Panthers', 'football', '#000000', '#BEBAB9', '#FFFFFF', 3, 117),
  ('NCAAF', '', 'EKU', 'Eastern Kentucky Colonels', 'Eastern Kentucky', 'Eastern Kentucky', 'Colonels', 'football', '#660819', '#F0F0F0', '#FFFFFF', 3, 118),
  ('NCAAF', '', 'ELMH', 'Elmhurst Bluejays', 'Elmhurst', 'Elmhurst', 'Bluejays', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 119),
  ('NCAAF', '', 'ELON', 'Elon Phoenix', 'Elon', 'Elon', 'Phoenix', 'football', '#020303', '#B59A57', '#FFFFFF', 3, 120),
  ('NCAAF', '', 'EMSU', 'Emporia State Hornets', 'Emporia State', 'Emporia State', 'Hornets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 121),
  ('NCAAF', '', 'ENDC', 'Endicott Gulls', 'Endicott', 'Endicott', 'Gulls', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 122),
  ('NCAAF', '', 'ENMU', 'Eastern New Mexico Greyhounds', 'Eastern New Mexico', 'Eastern New Mexico', 'Greyhounds', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 123),
  ('NCAAF', '', 'EORE', 'Eastern Oregon', 'Eastern Oregon', 'Eastern Oregon', 'Eastern Oregon', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 124),
  ('NCAAF', '', 'ERKA', 'Eureka Red Devils', 'Eureka', 'Eureka', 'Red Devils', 'football', '#960A2C', '#C09A05', '#FFFFFF', 3, 125),
  ('NCAAF', '', 'ESU', 'East Stroudsburg Warriors', 'East Stroudsburg', 'East Stroudsburg', 'Warriors', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 126),
  ('NCAAF', '', 'ETBU', 'East Texas Baptist Tigers', 'East Texas Baptist', 'East Texas Baptist', 'Tigers', 'football', '#002B44', '#E0AD13', '#FFFFFF', 3, 127),
  ('NCAAF', '', 'ETSU', 'East Tennessee State Buccaneers', 'East Tennessee State', 'East Tennessee State', 'Buccaneers', 'football', '#002D61', '#FFC423', '#FFFFFF', 3, 128),
  ('NCAAF', '', 'EWU', 'Eastern Washington Eagles', 'Eastern Washington', 'Eastern Washington', 'Eagles', 'football', '#A10022', '#ABB4BC', '#FFFFFF', 3, 129),
  ('NCAAF', '', 'FAMU', 'Florida A&M Rattlers', 'Florida A&M', 'Florida A&M', 'Rattlers', 'football', '#F89728', '#00843D', '#FFFFFF', 3, 130),
  ('NCAAF', '', 'FAULKNER', 'Faulkner University Eagles', 'Faulkner University', 'Faulkner University', 'Eagles', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 131),
  ('NCAAF', '', 'FAYU', 'Fayetteville State Broncos', 'Fayetteville State', 'Fayetteville State', 'Broncos', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 132),
  ('NCAAF', '', 'FBSU', 'Fitchburg State Falcons', 'Fitchburg State', 'Fitchburg State', 'Falcons', 'football', '#024D36', '#FBBF16', '#FFFFFF', 3, 133),
  ('NCAAF', '', 'FC', 'Ferrum Panthers', 'Ferrum', 'Ferrum', 'Panthers', 'football', '#000000', '#C0A656', '#FFFFFF', 3, 134),
  ('NCAAF', '', 'FDUF', 'FDU Florham Devils', 'FDU Florham', 'FDU Florham', 'Devils', 'football', '#003F87', '#A32638', '#FFFFFF', 3, 135),
  ('NCAAF', '', 'FHSU', 'Fort Hays Tigers', 'Fort Hays', 'Fort Hays', 'Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 136),
  ('NCAAF', '', 'FLWC', 'Fort Lewis Skyhawks', 'Fort Lewis', 'Fort Lewis', 'Skyhawks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 137),
  ('NCAAF', '', 'FMC', 'Franklin & Marshall Diplomats', 'Franklin & Marshall', 'Franklin & Marshall', 'Diplomats', 'football', '#25377D', '#6CB3E9', '#FFFFFF', 3, 138),
  ('NCAAF', '', 'FOR', 'Fordham Rams', 'Fordham', 'Fordham', 'Rams', 'football', '#830032', '#909090', '#FFFFFF', 3, 139),
  ('NCAAF', '', 'FRIE', 'Friends University Friends', 'Friends University', 'Friends University', 'Friends', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 140),
  ('NCAAF', '', 'FRKL', 'Franklin Grizzlies', 'Franklin', 'Franklin', 'Grizzlies', 'football', '#1B295B', '#FDD106', '#FFFFFF', 3, 141),
  ('NCAAF', '', 'FRST', 'Ferris State Bulldogs', 'Ferris State', 'Ferris State', 'Bulldogs', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 142),
  ('NCAAF', '', 'FSTU', 'Frostburg State Bobcats', 'Frostburg State', 'Frostburg State', 'Bobcats', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 143),
  ('NCAAF', '', 'FUR', 'Furman Paladins', 'Furman', 'Furman', 'Paladins', 'football', '#582C83', '#FFFFFF', '#FFFFFF', 3, 144),
  ('NCAAF', '', 'FVSU', 'Fort Valley State Wildcats', 'Fort Valley State', 'Fort Valley State', 'Wildcats', 'football', '#F9BD0A', '#2A307F', '#FFFFFF', 3, 145),
  ('NCAAF', '', 'GANN', 'Gannon Golden Knights', 'Gannon', 'Gannon', 'Golden Knights', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 146),
  ('NCAAF', '', 'GEN', 'Geneva Golden Tornadoes', 'Geneva', 'Geneva', 'Golden Tornadoes', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 147),
  ('NCAAF', '', 'GFU', 'George Fox Bruins', 'George Fox', 'George Fox', 'Bruins', 'football', '#002D62', '#C2A303', '#FFFFFF', 3, 148),
  ('NCAAF', '', 'GLDT', 'Gallaudet Bison', 'Gallaudet', 'Gallaudet', 'Bison', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 149),
  ('NCAAF', '', 'GLFD', 'Guilford Quakers', 'Guilford', 'Guilford', 'Quakers', 'football', '#910028', '#DCDDDE', '#FFFFFF', 3, 150),
  ('NCAAF', '', 'GMU', 'George Mason University Patriots', 'George Mason University', 'George Mason University', 'Patriots', 'football', '#016600', '#ECB010', '#FFFFFF', 3, 151),
  ('NCAAF', '', 'GRANDVIEW', 'Des Moines Vikings', 'Des Moines', 'Des Moines', 'Vikings', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 152),
  ('NCAAF', '', 'GRC', 'Graceland University Graceland', 'Graceland University', 'Graceland University', 'Graceland', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 153),
  ('NCAAF', '', 'GRNB', 'Greensboro Pride', 'Greensboro', 'Greensboro', 'Pride', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 154),
  ('NCAAF', '', 'GRNL', 'Grinnell Pioneers', 'Grinnell', 'Grinnell', 'Pioneers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 155),
  ('NCAAF', '', 'GRNV', 'Greenville Panthers', 'Greenville', 'Greenville', 'Panthers', 'football', '#F36917', '#000000', '#FFFFFF', 3, 156),
  ('NCAAF', '', 'GRO', 'Grove City Wolverines', 'Grove City', 'Grove City', 'Wolverines', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 157),
  ('NCAAF', '', 'GTOWNCOLL', 'Georgetown College Kentucky Tigers', 'Georgetown College Kentucky', 'Georgetown College Kentucky', 'Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 158),
  ('NCAAF', '', 'GTWN', 'Georgetown Hoyas', 'Georgetown', 'Georgetown', 'Hoyas', 'football', '#110E42', '#001C58', '#FFFFFF', 3, 159),
  ('NCAAF', '', 'GTYB', 'Gettysburg Bullets', 'Gettysburg', 'Gettysburg', 'Bullets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 160),
  ('NCAAF', '', 'GVLS', 'Glenville State Pioneers', 'Glenville State', 'Glenville State', 'Pioneers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 161),
  ('NCAAF', '', 'GVSU', 'Grand Valley State Lakers', 'Grand Valley State', 'Grand Valley State', 'Lakers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 162),
  ('NCAAF', '', 'GWEB', 'Gardner-Webb Runnin'' Bulldogs', 'Gardner-Webb', 'Gardner-Webb', 'Runnin'' Bulldogs', 'football', '#C12535', '#909090', '#FFFFFF', 3, 163),
  ('NCAAF', '', 'HAM', 'Hamilton Continentals', 'Hamilton', 'Hamilton', 'Continentals', 'football', '#062F87', '#D5B98B', '#FFFFFF', 3, 164),
  ('NCAAF', '', 'HAMP', 'Hampton Pirates', 'Hampton', 'Hampton', 'Pirates', 'football', '#0067AC', '#FFFFFF', '#FFFFFF', 3, 165),
  ('NCAAF', '', 'HARD', 'Harding Bisons', 'Harding', 'Harding', 'Bisons', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 166),
  ('NCAAF', '', 'HARV', 'Harvard Crimson', 'Harvard', 'Harvard', 'Crimson', 'football', '#990000', '#DBDBDB', '#FFFFFF', 3, 167),
  ('NCAAF', '', 'HASKELL', 'Haskell Indian Nations Univ Jayhawks', 'Haskell Indian Nations Univ', 'Haskell Indian Nations Univ', 'Jayhawks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 168),
  ('NCAAF', '', 'HBRT', 'Hobart College Statesmen', 'Hobart College', 'Hobart College', 'Statesmen', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 169),
  ('NCAAF', '', 'HC', 'Holy Cross Crusaders', 'Holy Cross', 'Holy Cross', 'Crusaders', 'football', '#582C83', '#FFFFFF', '#FFFFFF', 3, 170),
  ('NCAAF', '', 'HCU', 'Houston Christian Huskies', 'Houston Christian', 'Houston Christian', 'Huskies', 'football', '#00539C', '#FFFFFF', '#FFFFFF', 3, 171),
  ('NCAAF', '', 'HDBG', 'Heidelberg Student Princes', 'Heidelberg', 'Heidelberg', 'Student Princes', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 172),
  ('NCAAF', '', 'HDX', 'Hendrix Warriors', 'Hendrix', 'Hendrix', 'Warriors', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 173),
  ('NCAAF', '', 'HIRM', 'Hiram Terriers', 'Hiram', 'Hiram', 'Terriers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 174),
  ('NCAAF', '', 'HLDL', 'Hillsdale Chargers', 'Hillsdale', 'Hillsdale', 'Chargers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 175),
  ('NCAAF', '', 'HMLN', 'Hamline Pipers', 'Hamline', 'Hamline', 'Pipers', 'football', '#98012E', '#FFFFFF', '#FFFFFF', 3, 176),
  ('NCAAF', '', 'HNVR', 'Hanover Panthers', 'Hanover', 'Hanover', 'Panthers', 'football', '#0B486D', '#990000', '#FFFFFF', 3, 177),
  ('NCAAF', '', 'HOW', 'Howard Bison', 'Howard', 'Howard', 'Bison', 'football', '#003A63', '#E51937', '#FFFFFF', 3, 178),
  ('NCAAF', '', 'HRTW', 'Hartwick Hawks', 'Hartwick', 'Hartwick', 'Hawks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 179),
  ('NCAAF', '', 'HSC', 'Hampden Sydney Tigers', 'Hampden Sydney', 'Hampden Sydney', 'Tigers', 'football', '#900028', '#A8B1B7', '#FFFFFF', 3, 180),
  ('NCAAF', '', 'HSTU', 'Henderson State Reddies', 'Henderson State', 'Henderson State', 'Reddies', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 181),
  ('NCAAF', '', 'HUSS', 'Husson Eagles', 'Husson', 'Husson', 'Eagles', 'football', '#004B44', '#B09A5F', '#FFFFFF', 3, 182),
  ('NCAAF', '', 'IDHO', 'Idaho Vandals', 'Idaho', 'Idaho', 'Vandals', 'football', '#000000', '#8C6E4A', '#FFFFFF', 3, 183),
  ('NCAAF', '', 'IDST', 'Idaho State Bengals', 'Idaho State', 'Idaho State', 'Bengals', 'football', '#EF8C00', '#E9A126', '#FFFFFF', 3, 184),
  ('NCAAF', '', 'ILLC', 'Illinois College Blueboys', 'Illinois College', 'Illinois College', 'Blueboys', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 185),
  ('NCAAF', '', 'ILST', 'Illinois State Redbirds', 'Illinois State', 'Illinois State', 'Redbirds', 'football', '#CE1126', '#FFE716', '#FFFFFF', 3, 186),
  ('NCAAF', '', 'ILWU', 'Illinois Wesleyan Titans', 'Illinois Wesleyan', 'Illinois Wesleyan', 'Titans', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 187),
  ('NCAAF', '', 'INDY', 'Indianapolis Greyhounds', 'Indianapolis', 'Indianapolis', 'Greyhounds', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 188),
  ('NCAAF', '', 'INST', 'Indiana State Sycamores', 'Indiana State', 'Indiana State', 'Sycamores', 'football', '#00669A', '#F0F0F0', '#FFFFFF', 3, 189),
  ('NCAAF', '', 'ITH', 'Ithaca Bombers', 'Ithaca', 'Ithaca', 'Bombers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 190),
  ('NCAAF', '', 'IUP', 'IU Pennsylvania Crimson Hawks', 'IU Pennsylvania', 'IU Pennsylvania', 'Crimson Hawks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 191),
  ('NCAAF', '', 'JCSU', 'Johnson C. Smith Golden Bulls', 'Johnson C. Smith', 'Johnson C. Smith', 'Golden Bulls', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 192),
  ('NCAAF', '', 'JCU', 'John Carroll Blue Streaks', 'John Carroll', 'John Carroll', 'Blue Streaks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 193),
  ('NCAAF', '', 'JHU', 'Johns Hopkins University Blue Jays', 'Johns Hopkins University', 'Johns Hopkins University', 'Blue Jays', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 194),
  ('NCAAF', '', 'JKST', 'Jackson State Tigers', 'Jackson State', 'Jackson State', 'Tigers', 'football', '#123297', '#B5B7BA', '#FFFFFF', 3, 195),
  ('NCAAF', '', 'JUN', 'Juniata Eagles', 'Juniata', 'Juniata', 'Eagles', 'football', '#031832', '#AC9C66', '#FFFFFF', 3, 196),
  ('NCAAF', '', 'KALC', 'Kalamazoo Hornets', 'Kalamazoo', 'Kalamazoo', 'Hornets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 197),
  ('NCAAF', '', 'KANSA', 'Kansas Wesleyan Ks Wesleyan', 'Kansas Wesleyan', 'Kansas Wesleyan', 'Ks Wesleyan', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 198),
  ('NCAAF', '', 'KNGS', 'King''s Monarchs', 'King''s', 'King''s', 'Monarchs', 'football', '#C41230', '#000000', '#FFFFFF', 3, 199),
  ('NCAAF', '', 'KNOX', 'Knox Prairie Fire', 'Knox', 'Knox', 'Prairie Fire', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 200),
  ('NCAAF', '', 'KNY', 'Kenyon Owls', 'Kenyon', 'Kenyon', 'Owls', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 201),
  ('NCAAF', '', 'KUTZ', 'Kutztown Golden Bears', 'Kutztown', 'Kutztown', 'Golden Bears', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 202),
  ('NCAAF', '', 'KWC', 'Kentucky Wesleyan Panthers', 'Kentucky Wesleyan', 'Kentucky Wesleyan', 'Panthers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 203),
  ('NCAAF', '', 'KYSU', 'Kentucky State Thorobreds', 'Kentucky State', 'Kentucky State', 'Thorobreds', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 204),
  ('NCAAF', '', 'LAF', 'Lafayette Leopards', 'Lafayette', 'Lafayette', 'Leopards', 'football', '#790000', '#A59474', '#FFFFFF', 3, 205),
  ('NCAAF', '', 'LAM', 'Lamar Cardinals', 'Lamar', 'Lamar', 'Cardinals', 'football', '#000000', '#EBEBEB', '#FFFFFF', 3, 206),
  ('NCAAF', '', 'LANE', 'Lane College Dragons', 'Lane College', 'Lane College', 'Dragons', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 207),
  ('NCAAF', '', 'LAW', 'Lawrence Vikings', 'Lawrence', 'Lawrence', 'Vikings', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 208),
  ('NCAAF', '', 'LC', 'Lewis & Clark Pioneers', 'Lewis & Clark', 'Lewis & Clark', 'Pioneers', 'football', '#F37737', '#000000', '#FFFFFF', 3, 209),
  ('NCAAF', '', 'LCHR', 'Louisiana Christian Wildcats', 'Louisiana Christian', 'Louisiana Christian', 'Wildcats', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 210),
  ('NCAAF', '', 'LEH', 'Lehigh Mountain Hawks', 'Lehigh', 'Lehigh', 'Mountain Hawks', 'football', '#6C2B2A', '#B69E70', '#FFFFFF', 3, 211),
  ('NCAAF', '', 'LENR', 'Lenoir Rhyne Bears', 'Lenoir Rhyne', 'Lenoir Rhyne', 'Bears', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 212),
  ('NCAAF', '', 'LFC', 'Lake Forest Foresters', 'Lake Forest', 'Lake Forest', 'Foresters', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 213),
  ('NCAAF', '', 'LGC', 'LaGrange Panthers', 'LaGrange', 'LaGrange', 'Panthers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 214),
  ('NCAAF', '', 'LHU', 'Lock Haven University Bald Eagles', 'Lock Haven University', 'Lock Haven University', 'Bald Eagles', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 215),
  ('NCAAF', '', 'LINF', 'Linfield Wildcats', 'Linfield', 'Linfield', 'Wildcats', 'football', '#46256A', '#D41E47', '#FFFFFF', 3, 216),
  ('NCAAF', '', 'LIU', 'Long Island University Sharks', 'Long Island University', 'Long Island University', 'Sharks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 217),
  ('NCAAF', '', 'LKER', 'Lake Erie Storm', 'Lake Erie', 'Lake Erie', 'Storm', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 218),
  ('NCAAF', '', 'LNGT', 'Langston Lions', 'Langston', 'Langston', 'Lions', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 219),
  ('NCAAF', '', 'LNPA', 'Lincoln (PA) Lions', 'Lincoln (PA)', 'Lincoln (PA)', 'Lions', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 220),
  ('NCAAF', '', 'LOR', 'Loras Duhawks', 'Loras', 'Loras', 'Duhawks', 'football', '#452D7D', '#D2B888', '#FFFFFF', 3, 221),
  ('NCAAF', '', 'LUTH', 'Luther Norse', 'Luther', 'Luther', 'Norse', 'football', '#015A9C', '#A5BBDA', '#FFFFFF', 3, 222),
  ('NCAAF', '', 'LVC', 'Lebanon Valley Flying Dutchmen', 'Lebanon Valley', 'Lebanon Valley', 'Flying Dutchmen', 'football', '#003767', '#FFFFFF', '#FFFFFF', 3, 223),
  ('NCAAF', '', 'LYCO', 'Lycoming Warriors', 'Lycoming', 'Lycoming', 'Warriors', 'football', '#15283F', '#EAA22E', '#FFFFFF', 3, 224),
  ('NCAAF', '', 'MACA', 'Macalester Scots', 'Macalester', 'Macalester', 'Scots', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 225),
  ('NCAAF', '', 'MARY', 'University of Mary Marauders', 'University of Mary', 'University of Mary', 'Marauders', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 226),
  ('NCAAF', '', 'MCM', 'McMurry War Hawks', 'McMurry', 'McMurry', 'War Hawks', 'football', '#98002E', '#000000', '#FFFFFF', 3, 227),
  ('NCAAF', '', 'MCN', 'McNeese Cowboys', 'McNeese', 'McNeese', 'Cowboys', 'football', '#00529C', '#FFFFFF', '#FFFFFF', 3, 228),
  ('NCAAF', '', 'MCTN', 'Maryville (TN) Scots', 'Maryville (TN)', 'Maryville (TN)', 'Scots', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 229),
  ('NCAAF', '', 'MDAR', 'UMass Dartmouth Corsairs', 'UMass Dartmouth', 'UMass Dartmouth', 'Corsairs', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 230),
  ('NCAAF', '', 'ME', 'Maine Black Bears', 'Maine', 'Maine', 'Black Bears', 'football', '#127DBE', '#FFFFFF', '#FFFFFF', 3, 231),
  ('NCAAF', '', 'MER', 'Mercer Bears', 'Mercer', 'Mercer', 'Bears', 'football', '#FF7F29', '#080808', '#FFFFFF', 3, 232),
  ('NCAAF', '', 'MERC', 'Mercyhurst Lakers', 'Mercyhurst', 'Mercyhurst', 'Lakers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 233),
  ('NCAAF', '', 'MHB', 'Mary Hardin Baylor Crusaders', 'Mary Hardin Baylor', 'Mary Hardin Baylor', 'Crusaders', 'football', '#492F92', '#FECE1C', '#FFFFFF', 3, 234),
  ('NCAAF', '', 'MHU', 'Mars Hill Lions', 'Mars Hill', 'Mars Hill', 'Lions', 'football', '#004B8D', '#EFC814', '#FFFFFF', 3, 235),
  ('NCAAF', '', 'MIDB', 'Middlebury Panthers', 'Middlebury', 'Middlebury', 'Panthers', 'football', '#365A8A', '#FFFFFF', '#FFFFFF', 3, 236),
  ('NCAAF', '', 'MIDL', 'Midland MIDLAND LUTHERAN', 'Midland', 'Midland', 'MIDLAND LUTHERAN', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 237),
  ('NCAAF', '', 'MILE', 'Miles Golden Bears', 'Miles', 'Miles', 'Golden Bears', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 238),
  ('NCAAF', '', 'MILK', 'Millikin Big Blue', 'Millikin', 'Millikin', 'Big Blue', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 239),
  ('NCAAF', '', 'MILL', 'Millersville Marauders', 'Millersville', 'Millersville', 'Marauders', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 240),
  ('NCAAF', '', 'MINS', 'Minot State Beavers', 'Minot State', 'Minot State', 'Beavers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 241),
  ('NCAAF', '', 'MIT', 'MIT Engineers', 'MIT', 'MIT', 'Engineers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 242),
  ('NCAAF', '', 'MLC', 'Martin Luther Knights', 'Martin Luther', 'Martin Luther', 'Knights', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 243),
  ('NCAAF', '', 'MLSP', 'Millsaps Majors', 'Millsaps', 'Millsaps', 'Majors', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 244),
  ('NCAAF', '', 'MMA', 'Merchant Marine Mariners', 'Merchant Marine', 'Merchant Marine', 'Mariners', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 245),
  ('NCAAF', '', 'MMT', 'Mass Maritime Buccaneers', 'Mass Maritime', 'Mass Maritime', 'Buccaneers', 'football', '#212C62', '#FED523', '#FFFFFF', 3, 246),
  ('NCAAF', '', 'MNCH', 'Manchester Spartans', 'Manchester', 'Manchester', 'Spartans', 'football', '#DDAC14', '#000000', '#FFFFFF', 3, 247),
  ('NCAAF', '', 'MNFD', 'Mansfield Mountaineers', 'Mansfield', 'Mansfield', 'Mountaineers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 248),
  ('NCAAF', '', 'MNGS', 'Morningside Chiefs', 'Morningside', 'Morningside', 'Chiefs', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 249),
  ('NCAAF', '', 'MNMO', 'Minnesota Morris Cougars', 'Minnesota Morris', 'Minnesota Morris', 'Cougars', 'football', '#8D191B', '#E19C25', '#FFFFFF', 3, 250),
  ('NCAAF', '', 'MNST', 'Minnesota State Mavericks', 'Minnesota State', 'Minnesota State', 'Mavericks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 251),
  ('NCAAF', '', 'MONM', 'Monmouth Hawks', 'Monmouth', 'Monmouth', 'Hawks', 'football', '#051844', '#FFFFFF', '#FFFFFF', 3, 252),
  ('NCAAF', '', 'MONT', 'Montana Grizzlies', 'Montana', 'Montana', 'Grizzlies', 'football', '#751D4A', '#666666', '#FFFFFF', 3, 253),
  ('NCAAF', '', 'MOR', 'Moravian Greyhounds', 'Moravian', 'Moravian', 'Greyhounds', 'football', '#1F3361', '#A5A6A9', '#FFFFFF', 3, 254),
  ('NCAAF', '', 'MORE', 'Morehead State Eagles', 'Morehead State', 'Morehead State', 'Eagles', 'football', '#094FA3', '#FED91A', '#FFFFFF', 3, 255),
  ('NCAAF', '', 'MORG', 'Morgan State Bears', 'Morgan State', 'Morgan State', 'Bears', 'football', '#014786', '#F47937', '#FFFFFF', 3, 256),
  ('NCAAF', '', 'MOWE', 'Missouri Western Griffons', 'Missouri Western', 'Missouri Western', 'Griffons', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 257),
  ('NCAAF', '', 'MRHO', 'Morehouse Maroon Tigers', 'Morehouse', 'Morehouse', 'Maroon Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 258),
  ('NCAAF', '', 'MRST', 'Marist Red Foxes', 'Marist', 'Marist', 'Red Foxes', 'football', '#E53730', '#F0F0F0', '#FFFFFF', 3, 259),
  ('NCAAF', '', 'MRTT', 'Marietta Pioneers', 'Marietta', 'Marietta', 'Pioneers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 260),
  ('NCAAF', '', 'MS&T', 'Missouri S&T Miners', 'Missouri S&T', 'Missouri S&T', 'Miners', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 261),
  ('NCAAF', '', 'MSJ', 'Mount St Joseph Lions', 'Mount St Joseph', 'Mount St Joseph', 'Lions', 'football', '#002D5D', '#F5CE3E', '#FFFFFF', 3, 262),
  ('NCAAF', '', 'MSK', 'Muskingum Fighting Muskies', 'Muskingum', 'Muskingum', 'Fighting Muskies', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 263),
  ('NCAAF', '', 'MSSU', 'Missouri Southern State Lions', 'Missouri Southern State', 'Missouri Southern State', 'Lions', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 264),
  ('NCAAF', '', 'MTST', 'Montana State Bobcats', 'Montana State', 'Montana State', 'Bobcats', 'football', '#00205C', '#BC955C', '#FFFFFF', 3, 265),
  ('NCAAF', '', 'MTU', 'Michigan Tech Huskies', 'Michigan Tech', 'Michigan Tech', 'Huskies', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 266),
  ('NCAAF', '', 'MU', 'Methodist Monarchs', 'Methodist', 'Methodist', 'Monarchs', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 267),
  ('NCAAF', '', 'MUHL', 'Muhlenberg Mules', 'Muhlenberg', 'Muhlenberg', 'Mules', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 268),
  ('NCAAF', '', 'MUIN', 'Marian (IN) MARIAN', 'Marian (IN)', 'Marian (IN)', 'MARIAN', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 269),
  ('NCAAF', '', 'MUR', 'Murray State Racers', 'Murray State', 'Murray State', 'Racers', 'football', '#002148', '#000E00', '#FFFFFF', 3, 270),
  ('NCAAF', '', 'MVSU', 'Mississippi Valley State Delta Devils', 'Mississippi Valley State', 'Mississippi Valley State', 'Delta Devils', 'football', '#005328', '#CF2D34', '#FFFFFF', 3, 271),
  ('NCAAF', '', 'MWMO', 'Northwest Missouri State Bearcats', 'Northwest Missouri State', 'Northwest Missouri State', 'Bearcats', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 272),
  ('NCAAF', '', 'MWSU', 'Midwestern State Mustangs', 'Midwestern State', 'Midwestern State', 'Mustangs', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 273),
  ('NCAAF', '', 'MYSU', 'Mayville State Comets', 'Mayville State', 'Mayville State', 'Comets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 274),
  ('NCAAF', '', 'NAU', 'Northern Arizona Lumberjacks', 'Northern Arizona', 'Northern Arizona', 'Lumberjacks', 'football', '#003976', '#1B3069', '#FFFFFF', 3, 275),
  ('NCAAF', '', 'NBRY', 'Newberry Wolves', 'Newberry', 'Newberry', 'Wolves', 'football', '#D02030', '#8A8C8F', '#FFFFFF', 3, 276),
  ('NCAAF', '', 'NCAT', 'North Carolina A&T Aggies', 'North Carolina A&T', 'North Carolina A&T', 'Aggies', 'football', '#0505AA', '#004684', '#FFFFFF', 3, 277),
  ('NCAAF', '', 'NCCU', 'North Carolina Central Eagles', 'North Carolina Central', 'North Carolina Central', 'Eagles', 'football', '#880023', '#C2C3C0', '#FFFFFF', 3, 278),
  ('NCAAF', '', 'NCW', 'North Carolina Wesleyan Battling Bishops', 'North Carolina Wesleyan', 'North Carolina Wesleyan', 'Battling Bishops', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 279),
  ('NCAAF', '', 'NDSU', 'North Dakota State Bison', 'North Dakota State', 'North Dakota State', 'Bison', 'football', '#01402A', '#FFFFFF', '#FFFFFF', 3, 280),
  ('NCAAF', '', 'NEBK', 'Nebraska Kearney Lopers', 'Nebraska Kearney', 'Nebraska Kearney', 'Lopers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 281),
  ('NCAAF', '', 'NESU', 'Northeastern State RiverHawks', 'Northeastern State', 'Northeastern State', 'RiverHawks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 282),
  ('NCAAF', '', 'NHVN', 'New Haven Chargers', 'New Haven', 'New Haven', 'Chargers', 'football', '#041E42', '#FFC425', '#FFFFFF', 3, 283),
  ('NCAAF', '', 'NICH', 'Nicholls Colonels', 'Nicholls', 'Nicholls', 'Colonels', 'football', '#C41230', '#F0F0F0', '#FFFFFF', 3, 284),
  ('NCAAF', '', 'NMHU', 'New Mexico Highlands Cowboys', 'New Mexico Highlands', 'New Mexico Highlands', 'Cowboys', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 285),
  ('NCAAF', '', 'NMI', 'Northern Michigan Wildcats', 'Northern Michigan', 'Northern Michigan', 'Wildcats', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 286),
  ('NCAAF', '', 'NORF', 'Norfolk State Spartans', 'Norfolk State', 'Norfolk State', 'Spartans', 'football', '#0C8968', '#FDB813', '#FFFFFF', 3, 287),
  ('NCAAF', '', 'NPU', 'North Park Vikings', 'North Park', 'North Park', 'Vikings', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 288),
  ('NCAAF', '', 'NSU', 'Northern State Wolves', 'Northern State', 'Northern State', 'Wolves', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 289),
  ('NCAAF', '', 'NWCH', 'Norwich Cadets', 'Norwich', 'Norwich', 'Cadets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 290),
  ('NCAAF', '', 'NWST', 'Northwestern State Demons', 'Northwestern State', 'Northwestern State', 'Demons', 'football', '#492F91', '#ED6118', '#FFFFFF', 3, 291),
  ('NCAAF', '', 'OBE', 'Oberlin Yeomen', 'Oberlin', 'Oberlin', 'Yeomen', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 292),
  ('NCAAF', '', 'OHNU', 'Ohio Northern Polar Bears', 'Ohio Northern', 'Ohio Northern', 'Polar Bears', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 293),
  ('NCAAF', '', 'OKBU', 'Oklahoma Baptist Bison', 'Oklahoma Baptist', 'Oklahoma Baptist', 'Bison', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 294),
  ('NCAAF', '', 'OLAF', 'St. Olaf Oles', 'St. Olaf', 'St. Olaf', 'Oles', 'football', '#000000', '#D18C29', '#FFFFFF', 3, 295),
  ('NCAAF', '', 'OTTB', 'Otterbein Cardinals', 'Otterbein', 'Otterbein', 'Cardinals', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 296),
  ('NCAAF', '', 'PACE', 'Pace Setters', 'Pace', 'Pace', 'Setters', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 297),
  ('NCAAF', '', 'PCLT', 'Pacific Lutheran Lutes', 'Pacific Lutheran', 'Pacific Lutheran', 'Lutes', 'football', '#FFC423', '#000000', '#FFFFFF', 3, 298),
  ('NCAAF', '', 'PCOR', 'Pacific (OR) Boxers', 'Pacific (OR)', 'Pacific (OR)', 'Boxers', 'football', '#B4183A', '#FFFFFF', '#FFFFFF', 3, 299),
  ('NCAAF', '', 'PENN', 'Pennsylvania Quakers', 'Pennsylvania', 'Pennsylvania', 'Quakers', 'football', '#082A74', '#A6163D', '#FFFFFF', 3, 300),
  ('NCAAF', '', 'PIKEV', 'Pikeville Bears', 'Pikeville', 'Pikeville', 'Bears', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 301),
  ('NCAAF', '', 'PRES', 'Presbyterian Blue Hose', 'Presbyterian', 'Presbyterian', 'Blue Hose', 'football', '#194896', '#990134', '#FFFFFF', 3, 302),
  ('NCAAF', '', 'PRIN', 'Princeton Tigers', 'Princeton', 'Princeton', 'Tigers', 'football', '#000000', '#FF6000', '#FFFFFF', 3, 303),
  ('NCAAF', '', 'PRST', 'Portland State Vikings', 'Portland State', 'Portland State', 'Vikings', 'football', '#00311E', '#EBEBEB', '#FFFFFF', 3, 304),
  ('NCAAF', '', 'PTSU', 'Pittsburg State Gorillas', 'Pittsburg State', 'Pittsburg State', 'Gorillas', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 305),
  ('NCAAF', '', 'PV', 'Prairie View A&M Panthers', 'Prairie View A&M', 'Prairie View A&M', 'Panthers', 'football', '#582C83', '#EAAA00', '#FFFFFF', 3, 306),
  ('NCAAF', '', 'REDL', 'Redlands Bulldogs', 'Redlands', 'Redlands', 'Bulldogs', 'football', '#751708', '#FFFFFF', '#FFFFFF', 3, 307),
  ('NCAAF', '', 'RHIT', 'Rose Hulman Fightin'' Engineers', 'Rose Hulman', 'Rose Hulman', 'Fightin'' Engineers', 'football', '#800000', '#B3B2B1', '#FFFFFF', 3, 308),
  ('NCAAF', '', 'RICH', 'Richmond Spiders', 'Richmond', 'Richmond', 'Spiders', 'football', '#9E0712', '#B90B2E', '#FFFFFF', 3, 309),
  ('NCAAF', '', 'RSVT', 'Roosevelt Lakers', 'Roosevelt', 'Roosevelt', 'Lakers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 310),
  ('NCAAF', '', 'SAC', 'Sacramento State Hornets', 'Sacramento State', 'Sacramento State', 'Hornets', 'football', '#00573C', '#CDB97D', '#FFFFFF', 3, 311),
  ('NCAAF', '', 'SDAK', 'South Dakota Coyotes', 'South Dakota', 'South Dakota', 'Coyotes', 'football', '#CD1241', '#F0F0F0', '#FFFFFF', 3, 312),
  ('NCAAF', '', 'SDMT', 'South Dakota Mines Hardrockers', 'South Dakota Mines', 'South Dakota Mines', 'Hardrockers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 313),
  ('NCAAF', '', 'SEHI', 'Seton Hill Griffins', 'Seton Hill', 'Seton Hill', 'Griffins', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 314),
  ('NCAAF', '', 'SEOK', 'Southeastern Oklahoma State Savage Storm', 'Southeastern Oklahoma State', 'Southeastern Oklahoma State', 'Savage Storm', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 315),
  ('NCAAF', '', 'SEU', 'Southeastern Fires', 'Southeastern', 'Southeastern', 'Fires', 'football', '#007DC3', '#FFC423', '#FFFFFF', 3, 316),
  ('NCAAF', '', 'SIU', 'Southern Illinois Salukis', 'Southern Illinois', 'Southern Illinois', 'Salukis', 'football', '#85283D', '#C2C3C0', '#FFFFFF', 3, 317),
  ('NCAAF', '', 'SNU', 'Southern Nazarene Crimson Storm', 'Southern Nazarene', 'Southern Nazarene', 'Crimson Storm', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 318),
  ('NCAAF', '', 'SPR', 'Springfield Pride', 'Springfield', 'Springfield', 'Pride', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 319),
  ('NCAAF', '', 'SRU', 'Slippery Rock The Rock', 'Slippery Rock', 'Slippery Rock', 'The Rock', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 320),
  ('NCAAF', '', 'STET', 'Stetson Hatters', 'Stetson', 'Stetson', 'Hatters', 'football', '#0A5640', '#56854E', '#FFFFFF', 3, 321),
  ('NCAAF', '', 'STJF', 'St. John Fisher Cardinals', 'St. John Fisher', 'St. John Fisher', 'Cardinals', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 322),
  ('NCAAF', '', 'STLG', 'Sterling STERLING KS', 'Sterling', 'Sterling', 'STERLING KS', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 323),
  ('NCAAF', '', 'STO', 'Stonehill Skyhawks', 'Stonehill', 'Stonehill', 'Skyhawks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 324),
  ('NCAAF', '', 'STVS', 'Stevenson Mustangs', 'Stevenson', 'Stevenson', 'Mustangs', 'football', '#005747', '#000000', '#FFFFFF', 3, 325),
  ('NCAAF', '', 'SUSQ', 'Susquehanna River Hawks', 'Susquehanna', 'Susquehanna', 'River Hawks', 'football', '#6B1A31', '#FD6B0D', '#FFFFFF', 3, 326),
  ('NCAAF', '', 'SUU', 'Southern Utah Thunderbirds', 'Southern Utah', 'Southern Utah', 'Thunderbirds', 'football', '#C72026', '#000000', '#FFFFFF', 3, 327),
  ('NCAAF', '', 'SVSU', 'Saginaw Valley State Cardinals', 'Saginaw Valley State', 'Saginaw Valley State', 'Cardinals', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 328),
  ('NCAAF', '', 'SWKS', 'Southwestern (KS) Moundbuilders', 'Southwestern (KS)', 'Southwestern (KS)', 'Moundbuilders', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 329),
  ('NCAAF', '', 'TCNJ', 'The College of New Jersey Lions', 'The College of New Jersey', 'The College of New Jersey', 'Lions', 'football', '#154C7D', '#FBBC20', '#FFFFFF', 3, 330),
  ('NCAAF', '', 'TLRU', 'Taylor Trojans', 'Taylor', 'Taylor', 'Trojans', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 331),
  ('NCAAF', '', 'TOW', 'Towson Tigers', 'Towson', 'Towson', 'Tigers', 'football', '#FFC229', '#FFFFFF', '#FFFFFF', 3, 332),
  ('NCAAF', '', 'TUFT', 'Tufts Jumbos', 'Tufts', 'Tufts', 'Jumbos', 'football', '#3E8EDE', '#C6BEB6', '#FFFFFF', 3, 333),
  ('NCAAF', '', 'TUTX', 'Trinity (TX) Tigers', 'Trinity (TX)', 'Trinity (TX)', 'Tigers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 334),
  ('NCAAF', '', 'UALB', 'UAlbany Great Danes', 'UAlbany', 'UAlbany', 'Great Danes', 'football', '#3D2777', '#FFFFFF', '#FFFFFF', 3, 335),
  ('NCAAF', '', 'UAM', 'Arkansas Monticello Boll Weevils', 'Arkansas Monticello', 'Arkansas Monticello', 'Boll Weevils', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 336),
  ('NCAAF', '', 'UAPB', 'Arkansas-Pine Bluff Golden Lions', 'Arkansas-Pine Bluff', 'Arkansas-Pine Bluff', 'Golden Lions', 'football', '#E0AA0F', '#EAAA00', '#FFFFFF', 3, 337),
  ('NCAAF', '', 'UCD', 'UC Davis Aggies', 'UC Davis', 'UC Davis', 'Aggies', 'football', '#002855', '#C3C4C6', '#FFFFFF', 3, 338),
  ('NCAAF', '', 'UCM', 'Central Missouri Mules', 'Central Missouri', 'Central Missouri', 'Mules', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 339),
  ('NCAAF', '', 'UCO', 'Central Oklahoma Bronchos', 'Central Oklahoma', 'Central Oklahoma', 'Bronchos', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 340),
  ('NCAAF', '', 'UCWV', 'Charleston (WV) Golden Eagles', 'Charleston (WV)', 'Charleston (WV)', 'Golden Eagles', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 341),
  ('NCAAF', '', 'UF', 'Findlay Oilers', 'Findlay', 'Findlay', 'Oilers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 342),
  ('NCAAF', '', 'UIU', 'Upper Iowa Peacocks', 'Upper Iowa', 'Upper Iowa', 'Peacocks', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 343),
  ('NCAAF', '', 'ULV', 'La Verne Leopards', 'La Verne', 'La Verne', 'Leopards', 'football', '#004812', '#F89828', '#FFFFFF', 3, 344),
  ('NCAAF', '', 'UMD', 'Minnesota Duluth Bulldogs', 'Minnesota Duluth', 'Minnesota Duluth', 'Bulldogs', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 345),
  ('NCAAF', '', 'UMMA', 'Maine Maritime Mariners', 'Maine Maritime', 'Maine Maritime', 'Mariners', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 346),
  ('NCAAF', '', 'UMU', 'Mount Union Raiders', 'Mount Union', 'Mount Union', 'Raiders', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 347),
  ('NCAAF', '', 'UNA', 'North Alabama Lions', 'North Alabama', 'North Alabama', 'Lions', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 348),
  ('NCAAF', '', 'UNCO', 'Northern Colorado Bears', 'Northern Colorado', 'Northern Colorado', 'Bears', 'football', '#13558D', '#FFC533', '#FFFFFF', 3, 349),
  ('NCAAF', '', 'UND', 'North Dakota Fighting Hawks', 'North Dakota', 'North Dakota', 'Fighting Hawks', 'football', '#00A26B', '#C2C3C0', '#FFFFFF', 3, 350),
  ('NCAAF', '', 'UNH', 'New Hampshire Wildcats', 'New Hampshire', 'New Hampshire', 'Wildcats', 'football', '#004990', '#C3C4C6', '#FFFFFF', 3, 351),
  ('NCAAF', '', 'UNI', 'Northern Iowa Panthers', 'Northern Iowa', 'Northern Iowa', 'Panthers', 'football', '#473282', '#FFFFFF', '#FFFFFF', 3, 352),
  ('NCAAF', '', 'UNNY', 'Union Garnet Chargers', 'Union', 'Union', 'Garnet Chargers', 'football', '#762334', '#000000', '#FFFFFF', 3, 353),
  ('NCAAF', '', 'UNW', 'Northwestern (MN) Eagles', 'Northwestern (MN)', 'Northwestern (MN)', 'Eagles', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 354),
  ('NCAAF', '', 'UOO', 'Olivet Comets', 'Olivet', 'Olivet', 'Comets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 355),
  ('NCAAF', '', 'URI', 'Rhode Island Rams', 'Rhode Island', 'Rhode Island', 'Rams', 'football', '#091F3F', '#5AB3E8', '#FFFFFF', 3, 356),
  ('NCAAF', '', 'URNY', 'Rochester (NY) Yellow Jackets', 'Rochester (NY)', 'Rochester (NY)', 'Yellow Jackets', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 357),
  ('NCAAF', '', 'USD', 'San Diego Toreros', 'San Diego', 'San Diego', 'Toreros', 'football', '#2F99D4', '#2F99D4', '#FFFFFF', 3, 358),
  ('NCAAF', '', 'UTC', 'Chattanooga Mocs', 'Chattanooga', 'Chattanooga', 'Mocs', 'football', '#00386B', '#DCA71D', '#FFFFFF', 3, 359),
  ('NCAAF', '', 'UTIC', 'Utica Pioneers', 'Utica', 'Utica', 'Pioneers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 360),
  ('NCAAF', '', 'UWO', 'Wisconsin Oshkosh Titans', 'Wisconsin Oshkosh', 'Wisconsin Oshkosh', 'Titans', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 361),
  ('NCAAF', '', 'UWP', 'Wisconsin Platteville Pioneers', 'Wisconsin Platteville', 'Wisconsin Platteville', 'Pioneers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 362),
  ('NCAAF', '', 'VCSU', 'Valley City State VALLEY CITY ST', 'Valley City State', 'Valley City State', 'VALLEY CITY ST', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 363),
  ('NCAAF', '', 'VILL', 'Villanova Wildcats', 'Villanova', 'Villanova', 'Wildcats', 'football', '#00205B', '#13B5EA', '#FFFFFF', 3, 364),
  ('NCAAF', '', 'VSU', 'Virginia State Trojans', 'Virginia State', 'Virginia State', 'Trojans', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 365),
  ('NCAAF', '', 'VTSC', 'Vermont State Castleton Spartans', 'Vermont State Castleton', 'Vermont State Castleton', 'Spartans', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 366),
  ('NCAAF', '', 'VUL', 'Virginia Lynchburg Dragons', 'Virginia Lynchburg', 'Virginia Lynchburg', 'Dragons', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 367),
  ('NCAAF', '', 'WAB', 'Wabash Little Giants', 'Wabash', 'Wabash', 'Little Giants', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 368),
  ('NCAAF', '', 'WCHT', 'West Chester Golden Rams', 'West Chester', 'West Chester', 'Golden Rams', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 369),
  ('NCAAF', '', 'WCIL', 'Wheaton (IL) Thunder', 'Wheaton (IL)', 'Wheaton (IL)', 'Thunder', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 370),
  ('NCAAF', '', 'WCMO', 'Westminster (MO) Blue Jays', 'Westminster (MO)', 'Westminster (MO)', 'Blue Jays', 'football', '#06496F', '#FFFFFF', '#FFFFFF', 3, 371),
  ('NCAAF', '', 'WILK', 'Wilkes Colonels', 'Wilkes', 'Wilkes', 'Colonels', 'football', '#002856', '#FFCD00', '#FFFFFF', 3, 372),
  ('NCAAF', '', 'WINU', 'Wingate Bulldogs', 'Wingate', 'Wingate', 'Bulldogs', 'football', '#182441', '#C1B585', '#FFFFFF', 3, 373),
  ('NCAAF', '', 'WORC', 'Worcester State Lancers', 'Worcester State', 'Worcester State', 'Lancers', 'football', '#004B8E', '#FFC629', '#FFFFFF', 3, 374),
  ('NCAAF', '', 'WSCT', 'Wesleyan (CT) Cardinals', 'Wesleyan (CT)', 'Wesleyan (CT)', 'Cardinals', 'football', '#D72121', '#000000', '#FFFFFF', 3, 375),
  ('NCAAF', '', 'WSMI', 'Wayne State (MI) Warriors', 'Wayne State (MI)', 'Wayne State (MI)', 'Warriors', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 376),
  ('NCAAF', '', 'WUMO', 'Washington St. Louis Bears', 'Washington St. Louis', 'Washington St. Louis', 'Bears', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 377),
  ('NCAAF', '', 'WVWC', 'West Virginia Wesleyan Bobcats', 'West Virginia Wesleyan', 'West Virginia Wesleyan', 'Bobcats', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 378),
  ('NCAAF', '', 'WYBU', 'Wayland Baptist Pioneers', 'Wayland Baptist', 'Wayland Baptist', 'Pioneers', 'football', '#000000', '#FFFFFF', '#FFFFFF', 3, 379),
  ('NCAAF', '', 'YALE', 'Yale Bulldogs', 'Yale', 'Yale', 'Bulldogs', 'football', '#004A81', '#286DC0', '#FFFFFF', 3, 380),
  ('NCAAF', 'SEC', 'ALA', 'Alabama Crimson Tide', 'Alabama', 'Alabama', 'Crimson Tide', 'football', '#9E1B32', '#FFFFFF', '#FFFFFF', 3, 381),
  ('NCAAF', 'SEC', 'ARK', 'Arkansas Razorbacks', 'Arkansas', 'Arkansas', 'Razorbacks', 'football', '#A32136', '#FFFFFF', '#FFFFFF', 3, 382),
  ('NCAAF', 'SEC', 'AUB', 'Auburn Tigers', 'Auburn', 'Auburn', 'Tigers', 'football', '#002B5C', '#F26522', '#FFFFFF', 3, 383),
  ('NCAAF', 'SEC', 'FLA', 'Florida Gators', 'Florida', 'Florida', 'Gators', 'football', '#0021A5', '#FA4616', '#FFFFFF', 3, 384),
  ('NCAAF', 'SEC', 'LSU', 'LSU Tigers', 'LSU', 'Louisiana', 'Tigers', 'football', '#461D76', '#FDD023', '#FFFFFF', 3, 385),
  ('NCAAF', 'SEC', 'MISS', 'Ole Miss Rebels', 'Ole Miss', 'Ole Miss', 'Rebels', 'football', '#13294B', '#CF142B', '#FFFFFF', 3, 386),
  ('NCAAF', 'SEC', 'MIZ', 'Missouri Tigers', 'Missouri', 'Missouri', 'Tigers', 'football', '#F1B82D', '#000000', '#FFFFFF', 3, 387),
  ('NCAAF', 'SEC', 'MSST', 'Mississippi State Bulldogs', 'Mississippi State', 'Mississippi State', 'Bulldogs', 'football', '#5D1725', '#C1C6C8', '#FFFFFF', 3, 388),
  ('NCAAF', 'SEC', 'OU', 'Oklahoma Sooners', 'Oklahoma', 'Oklahoma', 'Sooners', 'football', '#990000', '#FFFFFF', '#FFFFFF', 3, 389),
  ('NCAAF', 'SEC', 'TA&M', 'Texas A&M Aggies', 'Texas A&M', 'Texas A&M', 'Aggies', 'football', '#500000', '#FFFFFF', '#FFFFFF', 3, 390),
  ('NCAAF', 'SEC', 'TEX', 'Texas Longhorns', 'Texas', 'Texas', 'Longhorns', 'football', '#AF5C37', '#FFFFFF', '#FFFFFF', 3, 391),
  ('NCAAF', 'SEC', 'UGA', 'Georgia Bulldogs', 'Georgia', 'Georgia', 'Bulldogs', 'football', '#BA0C2F', '#2C2A29', '#FFFFFF', 3, 392),
  ('NCAAF', 'SEC', 'UK', 'Kentucky Wildcats', 'Kentucky', 'Kentucky', 'Wildcats', 'football', '#0033A0', '#FFFFFF', '#FFFFFF', 3, 393),
  ('NCAAF', 'SEC', 'VAN', 'Vanderbilt Commodores', 'Vanderbilt', 'Vanderbilt', 'Commodores', 'football', '#000000', '#CFAE70', '#FFFFFF', 3, 394),
  ('NCAAF', 'SEC', 'SC', 'South Carolina Gamecocks', 'South Carolina', 'South Carolina', 'Gamecocks', 'football', '#73000A', '#000000', '#FFFFFF', 3, 395),
  ('NCAAF', 'SEC', 'TENN', 'Tennessee Volunteers', 'Tennessee', 'Tennessee', 'Volunteers', 'football', '#FF8200', '#FFFFFF', '#FFFFFF', 3, 396),
  ('NCAAF', 'Big Ten', 'ILL', 'Illinois Fighting Illini', 'Illinois', 'Illinois', 'Fighting Illini', 'football', '#FF5F05', '#13294B', '#FFFFFF', 3, 397),
  ('NCAAF', 'Big Ten', 'IOWA', 'Iowa Hawkeyes', 'Iowa', 'Iowa', 'Hawkeyes', 'football', '#231F20', '#FCD116', '#FFFFFF', 3, 398),
  ('NCAAF', 'Big Ten', 'IU', 'Indiana Hoosiers', 'Indiana', 'Indiana', 'Hoosiers', 'football', '#970310', '#FFFFFF', '#FFFFFF', 3, 399),
  ('NCAAF', 'Big Ten', 'MD', 'Maryland Terrapins', 'Maryland', 'Maryland', 'Terrapins', 'football', '#CE1126', '#FFFFFF', '#FFFFFF', 3, 400),
  ('NCAAF', 'Big Ten', 'MICH', 'Michigan Wolverines', 'Michigan', 'Michigan', 'Wolverines', 'football', '#00274C', '#FFCB05', '#FFFFFF', 3, 401),
  ('NCAAF', 'Big Ten', 'MINN', 'Minnesota Golden Gophers', 'Minnesota', 'Minnesota', 'Golden Gophers', 'football', '#5E0A2F', '#FAB41C', '#FFFFFF', 3, 402),
  ('NCAAF', 'Big Ten', 'MSU', 'Michigan State Spartans', 'Michigan State', 'Michigan State', 'Spartans', 'football', '#173F35', '#FFFFFF', '#FFFFFF', 3, 403),
  ('NCAAF', 'Big Ten', 'NEB', 'Nebraska Cornhuskers', 'Nebraska', 'Nebraska', 'Cornhuskers', 'football', '#E31937', '#FFFFFF', '#FFFFFF', 3, 404),
  ('NCAAF', 'Big Ten', 'NU', 'Northwestern Wildcats', 'Northwestern', 'Northwestern', 'Wildcats', 'football', '#492F92', '#FFFFFF', '#FFFFFF', 3, 405),
  ('NCAAF', 'Big Ten', 'ORE', 'Oregon Ducks', 'Oregon', 'Oregon', 'Ducks', 'football', '#00934B', '#FFF41B', '#FFFFFF', 3, 406),
  ('NCAAF', 'Big Ten', 'OSU', 'Ohio State Buckeyes', 'Ohio State', 'Ohio State', 'Buckeyes', 'football', '#BA0C2F', '#A8ADB4', '#FFFFFF', 3, 407),
  ('NCAAF', 'Big Ten', 'PSU', 'Penn State Nittany Lions', 'Penn State', 'Penn State', 'Nittany Lions', 'football', '#061440', '#FFFFFF', '#FFFFFF', 3, 408),
  ('NCAAF', 'Big Ten', 'RUTG', 'Rutgers Scarlet Knights', 'Rutgers', 'Rutgers', 'Scarlet Knights', 'football', '#CE0E2D', '#FFFFFF', '#FFFFFF', 3, 409),
  ('NCAAF', 'Big Ten', 'UCLA', 'UCLA Bruins', 'UCLA', 'Los Angeles', 'Bruins', 'football', '#2774AE', '#F2A900', '#FFFFFF', 3, 410),
  ('NCAAF', 'Big Ten', 'USC', 'USC Trojans', 'USC', 'Los Angeles', 'Trojans', 'football', '#9D2235', '#FFC72C', '#FFFFFF', 3, 411),
  ('NCAAF', 'Big Ten', 'WASH', 'Washington Huskies', 'Washington', 'Washington', 'Huskies', 'football', '#33006F', '#E8D3A2', '#FFFFFF', 3, 412),
  ('NCAAF', 'Big Ten', 'WIS', 'Wisconsin Badgers', 'Wisconsin', 'Wisconsin', 'Badgers', 'football', '#A00000', '#FFFFFF', '#FFFFFF', 3, 413),
  ('NCAAF', 'Big Ten', 'PUR', 'Purdue Boilermakers', 'Purdue', 'Purdue', 'Boilermakers', 'football', '#CEB888', '#000000', '#FFFFFF', 3, 414),
  ('NCAAF', 'ACC', 'BC', 'Boston College Eagles', 'Boston College', 'Boston', 'Eagles', 'football', '#8C2232', '#DBCCA6', '#FFFFFF', 3, 415),
  ('NCAAF', 'ACC', 'CAL', 'California Golden Bears', 'California', 'California', 'Golden Bears', 'football', '#041E42', '#FFC72C', '#FFFFFF', 3, 416),
  ('NCAAF', 'ACC', 'CLEM', 'Clemson Tigers', 'Clemson', 'Clemson', 'Tigers', 'football', '#F56600', '#FFFFFF', '#FFFFFF', 3, 417),
  ('NCAAF', 'ACC', 'DUKE', 'Duke Blue Devils', 'Duke', 'Duke', 'Blue Devils', 'football', '#00539B', '#FFFFFF', '#FFFFFF', 3, 418),
  ('NCAAF', 'ACC', 'FSU', 'Florida State Seminoles', 'Florida State', 'Florida State', 'Seminoles', 'football', '#782F40', '#CEB888', '#FFFFFF', 3, 419),
  ('NCAAF', 'ACC', 'GT', 'Georgia Tech Yellow Jackets', 'Georgia Tech', 'Atlanta', 'Yellow Jackets', 'football', '#B3A369', '#FFFFFF', '#FFFFFF', 3, 420),
  ('NCAAF', 'ACC', 'LOU', 'Louisville Cardinals', 'Louisville', 'Louisville', 'Cardinals', 'football', '#C9001F', '#FFFFFF', '#FFFFFF', 3, 421),
  ('NCAAF', 'ACC', 'MIA', 'Miami Hurricanes', 'Miami', 'Miami', 'Hurricanes', 'football', '#F47423', '#035131', '#FFFFFF', 3, 422),
  ('NCAAF', 'ACC', 'NCSU', 'NC State Wolfpack', 'NC State', 'Raleigh', 'Wolfpack', 'football', '#CC0000', '#FFFFFF', '#FFFFFF', 3, 423),
  ('NCAAF', 'ACC', 'PITT', 'Pittsburgh Panthers', 'Pittsburgh', 'Pittsburgh', 'Panthers', 'football', '#003594', '#FFB81C', '#FFFFFF', 3, 424),
  ('NCAAF', 'ACC', 'STAN', 'Stanford Cardinal', 'Stanford', 'Stanford', 'Cardinal', 'football', '#8C1515', '#FFFFFF', '#FFFFFF', 3, 425),
  ('NCAAF', 'ACC', 'SYR', 'Syracuse Orange', 'Syracuse', 'Syracuse', 'Orange', 'football', '#000E54', '#FF431B', '#FFFFFF', 3, 426),
  ('NCAAF', 'ACC', 'UNC', 'North Carolina Tar Heels', 'North Carolina', 'North Carolina', 'Tar Heels', 'football', '#7BAFD4', '#13294B', '#FFFFFF', 3, 427),
  ('NCAAF', 'ACC', 'UVA', 'Virginia Cavaliers', 'Virginia', 'Virginia', 'Cavaliers', 'football', '#F84C1E', '#232D4B', '#FFFFFF', 3, 428),
  ('NCAAF', 'ACC', 'VT', 'Virginia Tech Hokies', 'Virginia Tech', 'Blacksburg', 'Hokies', 'football', '#6A2C3E', '#CF4520', '#FFFFFF', 3, 429),
  ('NCAAF', 'ACC', 'WAKE', 'Wake Forest Demon Deacons', 'Wake Forest', 'Wake Forest', 'Demon Deacons', 'football', '#CEB888', '#2C2A29', '#FFFFFF', 3, 430),
  ('NCAAF', 'ACC', 'SMU', 'SMU Mustangs', 'SMU', 'Dallas', 'Mustangs', 'football', '#A80000', '#0033A1', '#FFFFFF', 3, 431),
  ('NCAAF', 'Big 12', 'ARIZ', 'Arizona Wildcats', 'Arizona', 'Arizona', 'Wildcats', 'football', '#CC0033', '#003366', '#FFFFFF', 3, 432),
  ('NCAAF', 'Big 12', 'ASU', 'Arizona State Sun Devils', 'Arizona State', 'Arizona State', 'Sun Devils', 'football', '#FFC627', '#8C1D40', '#FFFFFF', 3, 433),
  ('NCAAF', 'Big 12', 'BAY', 'Baylor Bears', 'Baylor', 'Baylor', 'Bears', 'football', '#154734', '#FFB81C', '#FFFFFF', 3, 434),
  ('NCAAF', 'Big 12', 'BYU', 'BYU Cougars', 'BYU', 'Provo', 'Cougars', 'football', '#0047BA', '#002E5D', '#FFFFFF', 3, 435),
  ('NCAAF', 'Big 12', 'CIN', 'Cincinnati Bearcats', 'Cincinnati', 'Cincinnati', 'Bearcats', 'football', '#000000', '#E00122', '#FFFFFF', 3, 436),
  ('NCAAF', 'Big 12', 'COLO', 'Colorado Buffaloes', 'Colorado', 'Colorado', 'Buffaloes', 'football', '#CFB87C', '#000000', '#FFFFFF', 3, 437),
  ('NCAAF', 'Big 12', 'HOU', 'Houston Cougars', 'Houston', 'Houston', 'Cougars', 'football', '#C8102E', '#FFFFFF', '#FFFFFF', 3, 438),
  ('NCAAF', 'Big 12', 'ISU', 'Iowa State Cyclones', 'Iowa State', 'Iowa State', 'Cyclones', 'football', '#AE192D', '#FFC72A', '#FFFFFF', 3, 439),
  ('NCAAF', 'Big 12', 'KSU', 'Kansas State Wildcats', 'Kansas State', 'Kansas State', 'Wildcats', 'football', '#330A57', '#E2E3E4', '#FFFFFF', 3, 440),
  ('NCAAF', 'Big 12', 'KU', 'Kansas Jayhawks', 'Kansas', 'Kansas', 'Jayhawks', 'football', '#0051BA', '#E8000D', '#FFFFFF', 3, 441),
  ('NCAAF', 'Big 12', 'OKST', 'Oklahoma State Cowboys', 'Oklahoma State', 'Oklahoma State', 'Cowboys', 'football', '#FE5C00', '#000000', '#FFFFFF', 3, 442),
  ('NCAAF', 'Big 12', 'UCF', 'UCF Knights', 'UCF', 'Orlando', 'Knights', 'football', '#000000', '#B4A169', '#FFFFFF', 3, 443),
  ('NCAAF', 'Big 12', 'UTAH', 'Utah Utes', 'Utah', 'Utah', 'Utes', 'football', '#BE0000', '#FFFFFF', '#FFFFFF', 3, 444),
  ('NCAAF', 'Big 12', 'WVU', 'West Virginia Mountaineers', 'West Virginia', 'West Virginia', 'Mountaineers', 'football', '#EAAA00', '#002855', '#FFFFFF', 3, 445),
  ('NCAAF', 'Big 12', 'TCU', 'TCU Horned Frogs', 'TCU', 'Fort Worth', 'Horned Frogs', 'football', '#4D1979', '#FFFFFF', '#FFFFFF', 3, 446),
  ('NCAAF', 'Big 12', 'TTU', 'Texas Tech Red Raiders', 'Texas Tech', 'Texas Tech', 'Red Raiders', 'football', '#DA291C', '#000000', '#FFFFFF', 3, 447),
  ('NCAAF', 'Pac-12', 'BOIS', 'Boise State Broncos', 'Boise State', 'Boise State', 'Broncos', 'football', '#0033A0', '#D64309', '#FFFFFF', 3, 448),
  ('NCAAF', 'Pac-12', 'CSU', 'Colorado State Rams', 'Colorado State', 'Colorado State', 'Rams', 'football', '#004C23', '#C8C372', '#FFFFFF', 3, 449),
  ('NCAAF', 'Pac-12', 'FRES', 'Fresno State Bulldogs', 'Fresno State', 'Fresno State', 'Bulldogs', 'football', '#B1102B', '#13284C', '#FFFFFF', 3, 450),
  ('NCAAF', 'Pac-12', 'ORST', 'Oregon State Beavers', 'Oregon State', 'Oregon State', 'Beavers', 'football', '#DC4405', '#000000', '#FFFFFF', 3, 451),
  ('NCAAF', 'Pac-12', 'SDSU', 'San Diego State Aztecs', 'San Diego State', 'San Diego State', 'Aztecs', 'football', '#A6192E', '#000000', '#FFFFFF', 3, 452),
  ('NCAAF', 'Pac-12', 'TXST', 'Texas State Bobcats', 'Texas State', 'Texas State', 'Bobcats', 'football', '#501214', '#6A5638', '#FFFFFF', 3, 453),
  ('NCAAF', 'Pac-12', 'USU', 'Utah State Aggies', 'Utah State', 'Utah State', 'Aggies', 'football', '#0F2439', '#FFFFFF', '#FFFFFF', 3, 454),
  ('NCAAF', 'Pac-12', 'WSU', 'Washington State Cougars', 'Washington State', 'Washington State', 'Cougars', 'football', '#A60F2D', '#4D4D4D', '#FFFFFF', 3, 455),
  ('NCAAF', 'American', 'ARMY', 'Army Black Knights', 'Army', 'Army', 'Black Knights', 'football', '#000000', '#D3BC8D', '#FFFFFF', 3, 456),
  ('NCAAF', 'American', 'CLT', 'Charlotte 49ers', 'Charlotte', 'Charlotte', '49ers', 'football', '#005035', '#A49665', '#FFFFFF', 3, 457),
  ('NCAAF', 'American', 'ECU', 'East Carolina Pirates', 'East Carolina', 'East Carolina', 'Pirates', 'football', '#582C83', '#FFC72C', '#FFFFFF', 3, 458),
  ('NCAAF', 'American', 'FAU', 'Florida Atlantic Owls', 'Florida Atlantic', 'Boca Raton', 'Owls', 'football', '#003366', '#CC0000', '#FFFFFF', 3, 459),
  ('NCAAF', 'American', 'MEM', 'Memphis Tigers', 'Memphis', 'Memphis', 'Tigers', 'football', '#004991', '#8E908F', '#FFFFFF', 3, 460),
  ('NCAAF', 'American', 'NAVY', 'Navy Midshipmen', 'Navy', 'Navy', 'Midshipmen', 'football', '#00225B', '#B5A67C', '#FFFFFF', 3, 461),
  ('NCAAF', 'American', 'RICE', 'Rice Owls', 'Rice', 'Rice', 'Owls', 'football', '#00205B', '#C1C6C8', '#FFFFFF', 3, 462),
  ('NCAAF', 'American', 'TEM', 'Temple Owls', 'Temple', 'Temple', 'Owls', 'football', '#A41E35', '#FFFFFF', '#FFFFFF', 3, 463),
  ('NCAAF', 'American', 'TLSA', 'Tulsa Golden Hurricane', 'Tulsa', 'Tulsa', 'Golden Hurricane', 'football', '#003595', '#D0B787', '#FFFFFF', 3, 464),
  ('NCAAF', 'American', 'UAB', 'UAB Blazers', 'UAB', 'Birmingham', 'Blazers', 'football', '#1A5632', '#FDB913', '#FFFFFF', 3, 465),
  ('NCAAF', 'American', 'UNT', 'North Texas Mean Green', 'North Texas', 'North Texas', 'Mean Green', 'football', '#068F33', '#FFFFFF', '#FFFFFF', 3, 466),
  ('NCAAF', 'American', 'USF', 'South Florida Bulls', 'South Florida', 'South Florida', 'Bulls', 'football', '#006747', '#CFC493', '#FFFFFF', 3, 467),
  ('NCAAF', 'American', 'TULN', 'Tulane Green Wave', 'Tulane', 'Tulane', 'Green Wave', 'football', '#006747', '#418FDE', '#FFFFFF', 3, 468),
  ('NCAAF', 'American', 'UTSA', 'UTSA Roadrunners', 'UTSA', 'San Antonio', 'Roadrunners', 'football', '#0C2340', '#F15A22', '#FFFFFF', 3, 469),
  ('NCAAF', 'Mountain West', 'AF', 'Air Force Falcons', 'Air Force', 'Air Force', 'Falcons', 'football', '#003594', '#FFFFFF', '#FFFFFF', 3, 470),
  ('NCAAF', 'Mountain West', 'HAW', 'Hawai''i Rainbow Warriors', 'Hawai''i', 'Hawai''i', 'Rainbow Warriors', 'football', '#005737', '#000000', '#FFFFFF', 3, 471),
  ('NCAAF', 'Mountain West', 'NEV', 'Nevada Wolf Pack', 'Nevada', 'Nevada', 'Wolf Pack', 'football', '#041E42', '#8A8D8F', '#FFFFFF', 3, 472),
  ('NCAAF', 'Mountain West', 'SJSU', 'San José State Spartans', 'San José State', 'San José State', 'Spartans', 'football', '#0038A8', '#FFB81A', '#FFFFFF', 3, 473),
  ('NCAAF', 'Mountain West', 'UNLV', 'UNLV Rebels', 'UNLV', 'Las Vegas', 'Rebels', 'football', '#CF0A2C', '#CAC8C8', '#FFFFFF', 3, 474),
  ('NCAAF', 'Mountain West', 'UNM', 'New Mexico Lobos', 'New Mexico', 'New Mexico', 'Lobos', 'football', '#BA0C2F', '#A7A8AA', '#FFFFFF', 3, 475),
  ('NCAAF', 'MAC', 'AKR', 'Akron Zips', 'Akron', 'Akron', 'Zips', 'football', '#041E42', '#C5B783', '#FFFFFF', 3, 476),
  ('NCAAF', 'MAC', 'BALL', 'Ball State Cardinals', 'Ball State', 'Ball State', 'Cardinals', 'football', '#BA0C2F', '#FFFFFF', '#FFFFFF', 3, 477),
  ('NCAAF', 'MAC', 'BGSU', 'Bowling Green Falcons', 'Bowling Green', 'Bowling Green', 'Falcons', 'football', '#FD5000', '#4F2C1D', '#FFFFFF', 3, 478),
  ('NCAAF', 'MAC', 'BUF', 'Buffalo Bulls', 'Buffalo', 'Buffalo', 'Bulls', 'football', '#005BBB', '#FFFFFF', '#FFFFFF', 3, 479),
  ('NCAAF', 'MAC', 'CMU', 'Central Michigan Chippewas', 'Central Michigan', 'Central Michigan', 'Chippewas', 'football', '#4C0027', '#FBAB18', '#FFFFFF', 3, 480),
  ('NCAAF', 'MAC', 'EMU', 'Eastern Michigan Eagles', 'Eastern Michigan', 'Eastern Michigan', 'Eagles', 'football', '#006938', '#FFFFFF', '#FFFFFF', 3, 481),
  ('NCAAF', 'MAC', 'KENT', 'Kent State Golden Flashes', 'Kent State', 'Kent State', 'Golden Flashes', 'football', '#002664', '#EAAB00', '#FFFFFF', 3, 482),
  ('NCAAF', 'MAC', 'M-OH', 'Miami (OH) RedHawks', 'Miami (OH)', 'Miami (OH)', 'RedHawks', 'football', '#C41230', '#FFFFFF', '#FFFFFF', 3, 483),
  ('NCAAF', 'MAC', 'MASS', 'Massachusetts Minutemen', 'Massachusetts', 'Massachusetts', 'Minutemen', 'football', '#881C1C', '#FFFFFF', '#FFFFFF', 3, 484),
  ('NCAAF', 'MAC', 'NIU', 'Northern Illinois Huskies', 'Northern Illinois', 'Northern Illinois', 'Huskies', 'football', '#C8102E', '#000000', '#FFFFFF', 3, 485),
  ('NCAAF', 'MAC', 'OHIO', 'Ohio Bobcats', 'Ohio', 'Ohio', 'Bobcats', 'football', '#154734', '#FFFFFF', '#FFFFFF', 3, 486),
  ('NCAAF', 'MAC', 'TOL', 'Toledo Rockets', 'Toledo', 'Toledo', 'Rockets', 'football', '#0B2240', '#FFCD00', '#FFFFFF', 3, 487),
  ('NCAAF', 'MAC', 'WMU', 'Western Michigan Broncos', 'Western Michigan', 'Western Michigan', 'Broncos', 'football', '#532E1F', '#F1C500', '#FFFFFF', 3, 488),
  ('NCAAF', 'Sun Belt', 'APP', 'App State Mountaineers', 'App State', 'App State', 'Mountaineers', 'football', '#000000', '#FFCD00', '#FFFFFF', 3, 489),
  ('NCAAF', 'Sun Belt', 'ARST', 'Arkansas State Red Wolves', 'Arkansas State', 'Arkansas State', 'Red Wolves', 'football', '#CC092F', '#000000', '#FFFFFF', 3, 490),
  ('NCAAF', 'Sun Belt', 'CCU', 'Coastal Carolina Chanticleers', 'Coastal Carolina', 'Coastal Carolina', 'Chanticleers', 'football', '#006F71', '#A27752', '#FFFFFF', 3, 491),
  ('NCAAF', 'Sun Belt', 'GASO', 'Georgia Southern Eagles', 'Georgia Southern', 'Georgia Southern', 'Eagles', 'football', '#041E42', '#A3AAAE', '#FFFFFF', 3, 492),
  ('NCAAF', 'Sun Belt', 'GAST', 'Georgia State Panthers', 'Georgia State', 'Georgia State', 'Panthers', 'football', '#0039A6', '#FFFFFF', '#FFFFFF', 3, 493),
  ('NCAAF', 'Sun Belt', 'JMU', 'James Madison Dukes', 'James Madison', 'James Madison', 'Dukes', 'football', '#450084', '#CBB677', '#FFFFFF', 3, 494),
  ('NCAAF', 'Sun Belt', 'MRSH', 'Marshall Thundering Herd', 'Marshall', 'Marshall', 'Thundering Herd', 'football', '#00B140', '#000000', '#FFFFFF', 3, 495),
  ('NCAAF', 'Sun Belt', 'ODU', 'Old Dominion Monarchs', 'Old Dominion', 'Old Dominion', 'Monarchs', 'football', '#003768', '#A1D2F1', '#FFFFFF', 3, 496),
  ('NCAAF', 'Sun Belt', 'UL', 'Louisiana Ragin'' Cajuns', 'Louisiana', 'Louisiana', 'Ragin'' Cajuns', 'football', '#CE181E', '#000000', '#FFFFFF', 3, 497),
  ('NCAAF', 'Sun Belt', 'ULM', 'UL Monroe Warhawks', 'UL Monroe', 'Monroe', 'Warhawks', 'football', '#840029', '#FDB913', '#FFFFFF', 3, 498),
  ('NCAAF', 'Sun Belt', 'USA', 'South Alabama Jaguars', 'South Alabama', 'Mobile', 'Jaguars', 'football', '#00205B', '#BF0D3E', '#FFFFFF', 3, 499),
  ('NCAAF', 'Sun Belt', 'TROY', 'Troy Trojans', 'Troy', 'Troy', 'Trojans', 'football', '#862633', '#B1B1B1', '#FFFFFF', 3, 500),
  ('NCAAF', 'Sun Belt', 'USM', 'Southern Miss Golden Eagles', 'Southern Miss', 'Southern Miss', 'Golden Eagles', 'football', '#FFC72C', '#231F20', '#FFFFFF', 3, 501),
  ('NCAAF', 'Conference USA', 'FIU', 'Florida International Panthers', 'Florida International', 'Miami', 'Panthers', 'football', '#091F3F', '#C3993F', '#FFFFFF', 3, 502),
  ('NCAAF', 'Conference USA', 'JXST', 'Jacksonville State Gamecocks', 'Jacksonville State', 'Jacksonville State', 'Gamecocks', 'football', '#CC0000', '#000000', '#FFFFFF', 3, 503),
  ('NCAAF', 'Conference USA', 'KENN', 'Kennesaw State Owls', 'Kennesaw State', 'Kennesaw State', 'Owls', 'football', '#FDBB30', '#0B1315', '#FFFFFF', 3, 504),
  ('NCAAF', 'Conference USA', 'LIB', 'Liberty Flames', 'Liberty', 'Liberty', 'Flames', 'football', '#0A254E', '#B72025', '#FFFFFF', 3, 505),
  ('NCAAF', 'Conference USA', 'LT', 'Louisiana Tech Bulldogs', 'Louisiana Tech', 'Louisiana Tech', 'Bulldogs', 'football', '#003087', '#CB333B', '#FFFFFF', 3, 506),
  ('NCAAF', 'Conference USA', 'MTSU', 'Middle Tennessee Blue Raiders', 'Middle Tennessee', 'Middle Tennessee', 'Blue Raiders', 'football', '#036EB7', '#FFFFFF', '#FFFFFF', 3, 507),
  ('NCAAF', 'Conference USA', 'NMSU', 'New Mexico State Aggies', 'New Mexico State', 'New Mexico State', 'Aggies', 'football', '#7E141B', '#231F20', '#FFFFFF', 3, 508),
  ('NCAAF', 'Conference USA', 'WKU', 'Western Kentucky Hilltoppers', 'Western Kentucky', 'Western Kentucky', 'Hilltoppers', 'football', '#E13A3E', '#FFFFFF', '#FFFFFF', 3, 509),
  ('NCAAF', 'Conference USA', 'DEL', 'Delaware Blue Hens', 'Delaware', 'Delaware', 'Blue Hens', 'football', '#00539F', '#FFD200', '#FFFFFF', 3, 510),
  ('NCAAF', 'Conference USA', 'MOST', 'Missouri State Bears', 'Missouri State', 'Missouri State', 'Bears', 'football', '#5E0009', '#FFFFFF', '#FFFFFF', 3, 511),
  ('NCAAF', 'Conference USA', 'SHSU', 'Sam Houston Bearkats', 'Sam Houston', 'Sam Houston', 'Bearkats', 'football', '#F56423', '#FFFFFF', '#FFFFFF', 3, 512),
  ('NCAAF', 'Conference USA', 'UTEP', 'UTEP Miners', 'UTEP', 'El Paso', 'Miners', 'football', '#FF8200', '#041E42', '#FFFFFF', 3, 513),
  ('NCAAF', 'Independents', 'CONN', 'UConn Huskies', 'UConn', 'UConn', 'Huskies', 'football', '#0C2340', '#A2AAAD', '#FFFFFF', 3, 514),
  ('NCAAF', 'Independents', 'ND', 'Notre Dame Fighting Irish', 'Notre Dame', 'South Bend', 'Fighting Irish', 'football', '#062340', '#C99700', '#FFFFFF', 3, 515)
on conflict (league, conference, code) do update set
  full_name   = excluded.full_name,
  first_name  = excluded.first_name,
  fanbase     = excluded.fanbase,
  mascot      = excluded.mascot,
  sport       = excluded.sport,
  shell       = excluded.shell,
  stripe      = excluded.stripe,
  mask        = excluded.mask,
  league_sort = excluded.league_sort,
  team_sort   = excluded.team_sort;
