-- Generated from research/teams.json by seed_teams_from_json.mjs
-- 124 rows · 4 leagues
-- Safe to re-run: uses ON CONFLICT DO UPDATE.

insert into public.teams
  (league, conference, code, full_name, first_name, fanbase, mascot, sport, shell, stripe, mask, league_sort, team_sort)
values
  ('NFL', '', 'SF', 'San Francisco 49ers', 'San Francisco', 'San Francisco', '49ers', 'football', '#B3995D', '#AA0000', '#FFFFFF', 0, 0),
  ('NFL', '', 'CHI', 'Chicago Bears', 'Chicago', 'Chicago', 'Bears', 'football', '#0B162A', '#C83803', '#BFC0BF', 0, 1),
  ('NFL', '', 'CIN', 'Cincinnati Bengals', 'Cincinnati', 'Cincinnati', 'Bengals', 'football', '#FB4F14', '#000000', '#FFFFFF', 0, 2),
  ('NFL', '', 'BUF', 'Buffalo Bills', 'Buffalo', 'Buffalo', 'Bills', 'football', '#FFFFFF', '#C60C30', '#00338D', 0, 3),
  ('NFL', '', 'DEN', 'Denver Broncos', 'Denver', 'Denver', 'Broncos', 'football', '#0166B3', '#FB4F14', '#FFFFFF', 0, 4),
  ('NFL', '', 'CLE', 'Cleveland Browns', 'Cleveland', 'Cleveland', 'Browns', 'football', '#FF3C00', '#311D00', '#BFC0BF', 0, 5),
  ('NFL', '', 'TB', 'Tampa Bay Buccaneers', 'Tampa Bay', 'Tampa Bay', 'Buccaneers', 'football', '#FFFFFF', '#D50A0A', '#FF7900', 0, 6),
  ('NFL', '', 'ARI', 'Arizona Cardinals', 'Arizona', 'Arizona', 'Cardinals', 'football', '#FFFFFF', '#97233F', '#A5ACAF', 0, 7),
  ('NFL', '', 'LAC', 'Los Angeles Chargers', 'Los Angeles', 'Los Angeles', 'Chargers', 'football', '#FFFFFF', '#FFC20E', '#0080C6', 0, 8),
  ('NFL', '', 'KC', 'Kansas City Chiefs', 'Kansas City', 'Kansas City', 'Chiefs', 'football', '#E31837', '#E31837', '#FFFFFF', 0, 9),
  ('NFL', '', 'IND', 'Indianapolis Colts', 'Indianapolis', 'Indianapolis', 'Colts', 'football', '#FFFFFF', '#002C5F', '#A2AAAD', 0, 10),
  ('NFL', '', 'WSH', 'Washington Commanders', 'Washington', 'Washington', 'Commanders', 'football', '#5A1414', '#FFB612', '#FFFFFF', 0, 11),
  ('NFL', '', 'DAL', 'Dallas Cowboys', 'Dallas', 'Dallas', 'Cowboys', 'football', '#869397', '#041E42', '#E2DFDF', 0, 12),
  ('NFL', '', 'MIA', 'Miami Dolphins', 'Miami', 'Miami', 'Dolphins', 'football', '#FFFFFF', '#FC4C02', '#008E97', 0, 13),
  ('NFL', '', 'PHI', 'Philadelphia Eagles', 'Philadelphia', 'Philadelphia', 'Eagles', 'football', '#339C5E', '#FFFFFF', '#A5ACAF', 0, 14),
  ('NFL', '', 'ATL', 'Atlanta Falcons', 'Atlanta', 'Atlanta', 'Falcons', 'football', '#000000', '#A71930', '#A5ACAF', 0, 15),
  ('NFL', '', 'NYG', 'New York Giants', 'New York', 'New York', 'Giants', 'football', '#0B2265', '#A71930', '#FFFFFF', 0, 16),
  ('NFL', '', 'JAX', 'Jacksonville Jaguars', 'Jacksonville', 'Jacksonville', 'Jaguars', 'football', '#101820', '#006778', '#9F792C', 0, 17),
  ('NFL', '', 'NYJ', 'New York Jets', 'New York', 'New York', 'Jets', 'football', '#FFFFFF', '#125740', '#FFFFFF', 0, 18),
  ('NFL', '', 'DET', 'Detroit Lions', 'Detroit', 'Detroit', 'Lions', 'football', '#B0B7BC', '#0076B6', '#0076B6', 0, 19),
  ('NFL', '', 'GB', 'Green Bay Packers', 'Green Bay', 'Green Bay', 'Packers', 'football', '#FFB612', '#203731', '#FFFFFF', 0, 20),
  ('NFL', '', 'CAR', 'Carolina Panthers', 'Carolina', 'Carolina', 'Panthers', 'football', '#BFC0BF', '#0085CA', '#101820', 0, 21),
  ('NFL', '', 'NE', 'New England Patriots', 'New England', 'New England', 'Patriots', 'football', '#002244', '#C60C30', '#B0B7BC', 0, 22),
  ('NFL', '', 'LV', 'Las Vegas Raiders', 'Las Vegas', 'Las Vegas', 'Raiders', 'football', '#A5ACAF', '#000000', '#575757', 0, 23),
  ('NFL', '', 'LAR', 'Los Angeles Rams', 'Los Angeles', 'Los Angeles', 'Rams', 'football', '#003594', '#FFD100', '#FFFFFF', 0, 24),
  ('NFL', '', 'BAL', 'Baltimore Ravens', 'Baltimore', 'Baltimore', 'Ravens', 'football', '#241773', '#9E7C0C', '#000000', 0, 25),
  ('NFL', '', 'NO', 'New Orleans Saints', 'New Orleans', 'New Orleans', 'Saints', 'football', '#D3BC8D', '#101820', '#FFFFFF', 0, 26),
  ('NFL', '', 'SEA', 'Seattle Seahawks', 'Seattle', 'Seattle', 'Seahawks', 'football', '#A5ACAF', '#07317B', '#69BE28', 0, 27),
  ('NFL', '', 'PIT', 'Pittsburgh Steelers', 'Pittsburgh', 'Pittsburgh', 'Steelers', 'football', '#101820', '#FFB612', '#FFFFFF', 0, 28),
  ('NFL', '', 'HOU', 'Houston Texans', 'Houston', 'Houston', 'Texans', 'football', '#03202F', '#A71930', '#FFFFFF', 0, 29),
  ('NFL', '', 'TEN', 'Tennessee Titans', 'Tennessee', 'Tennessee', 'Titans', 'football', '#FFFFFF', '#4B92DB', '#C8102E', 0, 30),
  ('NFL', '', 'MIN', 'Minnesota Vikings', 'Minnesota', 'Minnesota', 'Vikings', 'football', '#4F2683', '#FFC62F', '#FFFFFF', 0, 31),
  ('NBA', '', 'PHI', 'Philadelphia 76ers', 'Philadelphia', 'Philadelphia', '76ers', 'basketball', '#1D428A', '#E01234', '#FFFFFF', 1, 0),
  ('NBA', '', 'MIL', 'Milwaukee Bucks', 'Milwaukee', 'Milwaukee', 'Bucks', 'basketball', '#00471B', '#EEE1C6', '#FFFFFF', 1, 1),
  ('NBA', '', 'CHI', 'Chicago Bulls', 'Chicago', 'Chicago', 'Bulls', 'basketball', '#CE1141', '#000000', '#FFFFFF', 1, 2),
  ('NBA', '', 'CLE', 'Cleveland Cavaliers', 'Cleveland', 'Cleveland', 'Cavaliers', 'basketball', '#860038', '#BC945C', '#FFFFFF', 1, 3),
  ('NBA', '', 'BOS', 'Boston Celtics', 'Boston', 'Boston', 'Celtics', 'basketball', '#008348', '#FFFFFF', '#FFFFFF', 1, 4),
  ('NBA', '', 'LAC', 'Los Angeles Clippers', 'Los Angeles', 'Los Angeles', 'Clippers', 'basketball', '#12173F', '#C8102E', '#FFFFFF', 1, 5),
  ('NBA', '', 'MEM', 'Memphis Grizzlies', 'Memphis', 'Memphis', 'Grizzlies', 'basketball', '#5D76A9', '#12173F', '#FFFFFF', 1, 6),
  ('NBA', '', 'ATL', 'Atlanta Hawks', 'Atlanta', 'Atlanta', 'Hawks', 'basketball', '#C8102E', '#FDB927', '#FFFFFF', 1, 7),
  ('NBA', '', 'MIA', 'Miami Heat', 'Miami', 'Miami', 'Heat', 'basketball', '#98002E', '#000000', '#FFFFFF', 1, 8),
  ('NBA', '', 'CHA', 'Charlotte Hornets', 'Charlotte', 'Charlotte', 'Hornets', 'basketball', '#008CA8', '#1D1060', '#FFFFFF', 1, 9),
  ('NBA', '', 'UTAH', 'Utah Jazz', 'Utah', 'Utah', 'Jazz', 'basketball', '#4E008E', '#79A3DC', '#FFFFFF', 1, 10),
  ('NBA', '', 'SAC', 'Sacramento Kings', 'Sacramento', 'Sacramento', 'Kings', 'basketball', '#5A2D81', '#6A7A82', '#FFFFFF', 1, 11),
  ('NBA', '', 'NY', 'New York Knicks', 'New York', 'New York', 'Knicks', 'basketball', '#1D428A', '#F58426', '#FFFFFF', 1, 12),
  ('NBA', '', 'LAL', 'Los Angeles Lakers', 'Los Angeles', 'Los Angeles', 'Lakers', 'basketball', '#552583', '#FDB927', '#FFFFFF', 1, 13),
  ('NBA', '', 'ORL', 'Orlando Magic', 'Orlando', 'Orlando', 'Magic', 'basketball', '#0150B5', '#9CA0A3', '#FFFFFF', 1, 14),
  ('NBA', '', 'DAL', 'Dallas Mavericks', 'Dallas', 'Dallas', 'Mavericks', 'basketball', '#0064B1', '#BBC4CA', '#FFFFFF', 1, 15),
  ('NBA', '', 'BKN', 'Brooklyn Nets', 'Brooklyn', 'Brooklyn', 'Nets', 'basketball', '#000000', '#FFFFFF', '#FFFFFF', 1, 16),
  ('NBA', '', 'DEN', 'Denver Nuggets', 'Denver', 'Denver', 'Nuggets', 'basketball', '#0E2240', '#FEC524', '#FFFFFF', 1, 17),
  ('NBA', '', 'IND', 'Indiana Pacers', 'Indiana', 'Indiana', 'Pacers', 'basketball', '#0C2340', '#FFD520', '#FFFFFF', 1, 18),
  ('NBA', '', 'NO', 'New Orleans Pelicans', 'New Orleans', 'New Orleans', 'Pelicans', 'basketball', '#0A2240', '#B4975A', '#FFFFFF', 1, 19),
  ('NBA', '', 'DET', 'Detroit Pistons', 'Detroit', 'Detroit', 'Pistons', 'basketball', '#1D428A', '#C8102E', '#FFFFFF', 1, 20),
  ('NBA', '', 'TOR', 'Toronto Raptors', 'Toronto', 'Toronto', 'Raptors', 'basketball', '#D91244', '#000000', '#FFFFFF', 1, 21),
  ('NBA', '', 'HOU', 'Houston Rockets', 'Houston', 'Houston', 'Rockets', 'basketball', '#CE1141', '#000000', '#FFFFFF', 1, 22),
  ('NBA', '', 'SA', 'San Antonio Spurs', 'San Antonio', 'San Antonio', 'Spurs', 'basketball', '#000000', '#C4CED4', '#FFFFFF', 1, 23),
  ('NBA', '', 'PHX', 'Phoenix Suns', 'Phoenix', 'Phoenix', 'Suns', 'basketball', '#29127A', '#E56020', '#FFFFFF', 1, 24),
  ('NBA', '', 'OKC', 'Oklahoma City Thunder', 'Oklahoma City', 'Oklahoma City', 'Thunder', 'basketball', '#007AC1', '#EF3B24', '#FFFFFF', 1, 25),
  ('NBA', '', 'MIN', 'Minnesota Timberwolves', 'Minnesota', 'Minnesota', 'Timberwolves', 'basketball', '#266092', '#79BC43', '#FFFFFF', 1, 26),
  ('NBA', '', 'POR', 'Portland Trail Blazers', 'Portland', 'Portland', 'Trail Blazers', 'basketball', '#E03A3E', '#000000', '#FFFFFF', 1, 27),
  ('NBA', '', 'GS', 'Golden State Warriors', 'Golden State', 'Golden State', 'Warriors', 'basketball', '#FDB927', '#1D428A', '#FFFFFF', 1, 28),
  ('NBA', '', 'WSH', 'Washington Wizards', 'Washington', 'Washington', 'Wizards', 'basketball', '#E31837', '#002B5C', '#FFFFFF', 1, 29),
  ('NHL', '', 'COL', 'Colorado Avalanche', 'Colorado', 'Colorado', 'Avalanche', 'hockey', '#860038', '#005EA3', '#FFFFFF', 2, 0),
  ('NHL', '', 'CHI', 'Chicago Blackhawks', 'Chicago', 'Chicago', 'Blackhawks', 'hockey', '#E31937', '#000000', '#FFFFFF', 2, 1),
  ('NHL', '', 'CBJ', 'Columbus Blue Jackets', 'Columbus', 'Columbus', 'Blue Jackets', 'hockey', '#002D62', '#E31937', '#FFFFFF', 2, 2),
  ('NHL', '', 'STL', 'St. Louis Blues', 'St. Louis', 'St. Louis', 'Blues', 'hockey', '#0070B9', '#FDB71A', '#FFFFFF', 2, 3),
  ('NHL', '', 'BOS', 'Boston Bruins', 'Boston', 'Boston', 'Bruins', 'hockey', '#231F20', '#FDB71A', '#FFFFFF', 2, 4),
  ('NHL', '', 'MTL', 'Montreal Canadiens', 'Montreal', 'Montreal', 'Canadiens', 'hockey', '#C41230', '#013A81', '#FFFFFF', 2, 5),
  ('NHL', '', 'VAN', 'Vancouver Canucks', 'Vancouver', 'Vancouver', 'Canucks', 'hockey', '#003E7E', '#008752', '#FFFFFF', 2, 6),
  ('NHL', '', 'WSH', 'Washington Capitals', 'Washington', 'Washington', 'Capitals', 'hockey', '#D71830', '#0B1F41', '#FFFFFF', 2, 7),
  ('NHL', '', 'NJ', 'New Jersey Devils', 'New Jersey', 'New Jersey', 'Devils', 'hockey', '#E30B2B', '#000000', '#FFFFFF', 2, 8),
  ('NHL', '', 'ANA', 'Anaheim Ducks', 'Anaheim', 'Anaheim', 'Ducks', 'hockey', '#FC4C02', '#000000', '#FFFFFF', 2, 9),
  ('NHL', '', 'CGY', 'Calgary Flames', 'Calgary', 'Calgary', 'Flames', 'hockey', '#DD1A32', '#000000', '#FFFFFF', 2, 10),
  ('NHL', '', 'PHI', 'Philadelphia Flyers', 'Philadelphia', 'Philadelphia', 'Flyers', 'hockey', '#FE5823', '#000000', '#FFFFFF', 2, 11),
  ('NHL', '', 'VGK', 'Vegas Golden Knights', 'Vegas', 'Vegas', 'Golden Knights', 'hockey', '#344043', '#B4975A', '#FFFFFF', 2, 12),
  ('NHL', '', 'CAR', 'Carolina Hurricanes', 'Carolina', 'Carolina', 'Hurricanes', 'hockey', '#E30426', '#000000', '#FFFFFF', 2, 13),
  ('NHL', '', 'NYI', 'New York Islanders', 'New York', 'New York', 'Islanders', 'hockey', '#00529B', '#F47D31', '#FFFFFF', 2, 14),
  ('NHL', '', 'WPG', 'Winnipeg Jets', 'Winnipeg', 'Winnipeg', 'Jets', 'hockey', '#002D62', '#C41230', '#FFFFFF', 2, 15),
  ('NHL', '', 'LA', 'Los Angeles Kings', 'Los Angeles', 'Los Angeles', 'Kings', 'hockey', '#121212', '#A2AAAD', '#FFFFFF', 2, 16),
  ('NHL', '', 'SEA', 'Seattle Kraken', 'Seattle', 'Seattle', 'Kraken', 'hockey', '#000D33', '#A3DCE4', '#FFFFFF', 2, 17),
  ('NHL', '', 'TB', 'Tampa Bay Lightning', 'Tampa Bay', 'Tampa Bay', 'Lightning', 'hockey', '#003E7E', '#FFFFFF', '#FFFFFF', 2, 18),
  ('NHL', '', 'UTAH', 'Utah Mammoth', 'Utah', 'Utah', 'Mammoth', 'hockey', '#000000', '#7AB2E1', '#FFFFFF', 2, 19),
  ('NHL', '', 'TOR', 'Toronto Maple Leafs', 'Toronto', 'Toronto', 'Maple Leafs', 'hockey', '#003E7E', '#FFFFFF', '#FFFFFF', 2, 20),
  ('NHL', '', 'EDM', 'Edmonton Oilers', 'Edmonton', 'Edmonton', 'Oilers', 'hockey', '#00205B', '#FF4C00', '#FFFFFF', 2, 21),
  ('NHL', '', 'FLA', 'Florida Panthers', 'Florida', 'Florida', 'Panthers', 'hockey', '#E51937', '#002D62', '#FFFFFF', 2, 22),
  ('NHL', '', 'PIT', 'Pittsburgh Penguins', 'Pittsburgh', 'Pittsburgh', 'Penguins', 'hockey', '#000000', '#FDB71A', '#FFFFFF', 2, 23),
  ('NHL', '', 'NSH', 'Nashville Predators', 'Nashville', 'Nashville', 'Predators', 'hockey', '#FDBA31', '#002D62', '#FFFFFF', 2, 24),
  ('NHL', '', 'NYR', 'New York Rangers', 'New York', 'New York', 'Rangers', 'hockey', '#0056AE', '#E51937', '#FFFFFF', 2, 25),
  ('NHL', '', 'DET', 'Detroit Red Wings', 'Detroit', 'Detroit', 'Red Wings', 'hockey', '#E30526', '#FFFFFF', '#FFFFFF', 2, 26),
  ('NHL', '', 'BUF', 'Buffalo Sabres', 'Buffalo', 'Buffalo', 'Sabres', 'hockey', '#00468B', '#FDB71A', '#FFFFFF', 2, 27),
  ('NHL', '', 'OTT', 'Ottawa Senators', 'Ottawa', 'Ottawa', 'Senators', 'hockey', '#DD1A32', '#B79257', '#FFFFFF', 2, 28),
  ('NHL', '', 'SJ', 'San Jose Sharks', 'San Jose', 'San Jose', 'Sharks', 'hockey', '#00788A', '#070707', '#FFFFFF', 2, 29),
  ('NHL', '', 'DAL', 'Dallas Stars', 'Dallas', 'Dallas', 'Stars', 'hockey', '#20864C', '#000000', '#FFFFFF', 2, 30),
  ('NHL', '', 'MIN', 'Minnesota Wild', 'Minnesota', 'Minnesota', 'Wild', 'hockey', '#124734', '#AE122A', '#FFFFFF', 2, 31),
  ('MLB', '', 'LAA', 'Los Angeles Angels', 'Los Angeles', 'Los Angeles', 'Angels', 'baseball', '#BA0021', '#C4CED4', '#FFFFFF', 3, 0),
  ('MLB', '', 'HOU', 'Houston Astros', 'Houston', 'Houston', 'Astros', 'baseball', '#002D62', '#EB6E1F', '#FFFFFF', 3, 1),
  ('MLB', '', 'ATH', 'Athletics', 'Athletics', 'Athletics', 'Athletics', 'baseball', '#003831', '#EFB21E', '#FFFFFF', 3, 2),
  ('MLB', '', 'TOR', 'Toronto Blue Jays', 'Toronto', 'Toronto', 'Blue Jays', 'baseball', '#134A8E', '#6CACE5', '#FFFFFF', 3, 3),
  ('MLB', '', 'ATL', 'Atlanta Braves', 'Atlanta', 'Atlanta', 'Braves', 'baseball', '#0C2340', '#BA0C2F', '#FFFFFF', 3, 4),
  ('MLB', '', 'MIL', 'Milwaukee Brewers', 'Milwaukee', 'Milwaukee', 'Brewers', 'baseball', '#13294B', '#FFC72C', '#FFFFFF', 3, 5),
  ('MLB', '', 'STL', 'St. Louis Cardinals', 'St. Louis', 'St. Louis', 'Cardinals', 'baseball', '#BE0A14', '#001541', '#FFFFFF', 3, 6),
  ('MLB', '', 'CHC', 'Chicago Cubs', 'Chicago', 'Chicago', 'Cubs', 'baseball', '#0E3386', '#CC3433', '#FFFFFF', 3, 7),
  ('MLB', '', 'ARI', 'Arizona Diamondbacks', 'Arizona', 'Arizona', 'Diamondbacks', 'baseball', '#AA182C', '#000000', '#FFFFFF', 3, 8),
  ('MLB', '', 'LAD', 'Los Angeles Dodgers', 'Los Angeles', 'Los Angeles', 'Dodgers', 'baseball', '#005A9C', '#FFFFFF', '#FFFFFF', 3, 9),
  ('MLB', '', 'SF', 'San Francisco Giants', 'San Francisco', 'San Francisco', 'Giants', 'baseball', '#000000', '#FD5A1E', '#FFFFFF', 3, 10),
  ('MLB', '', 'CLE', 'Cleveland Guardians', 'Cleveland', 'Cleveland', 'Guardians', 'baseball', '#002B5C', '#E31937', '#FFFFFF', 3, 11),
  ('MLB', '', 'SEA', 'Seattle Mariners', 'Seattle', 'Seattle', 'Mariners', 'baseball', '#005C5C', '#0C2C56', '#FFFFFF', 3, 12),
  ('MLB', '', 'MIA', 'Miami Marlins', 'Miami', 'Miami', 'Marlins', 'baseball', '#00A3E0', '#000000', '#FFFFFF', 3, 13),
  ('MLB', '', 'NYM', 'New York Mets', 'New York', 'New York', 'Mets', 'baseball', '#002D72', '#FF5910', '#FFFFFF', 3, 14),
  ('MLB', '', 'WSH', 'Washington Nationals', 'Washington', 'Washington', 'Nationals', 'baseball', '#AB0003', '#11225B', '#FFFFFF', 3, 15),
  ('MLB', '', 'BAL', 'Baltimore Orioles', 'Baltimore', 'Baltimore', 'Orioles', 'baseball', '#DF4601', '#000000', '#FFFFFF', 3, 16),
  ('MLB', '', 'SD', 'San Diego Padres', 'San Diego', 'San Diego', 'Padres', 'baseball', '#2F241D', '#FFC425', '#FFFFFF', 3, 17),
  ('MLB', '', 'PHI', 'Philadelphia Phillies', 'Philadelphia', 'Philadelphia', 'Phillies', 'baseball', '#E81828', '#003278', '#FFFFFF', 3, 18),
  ('MLB', '', 'PIT', 'Pittsburgh Pirates', 'Pittsburgh', 'Pittsburgh', 'Pirates', 'baseball', '#000000', '#FDB827', '#FFFFFF', 3, 19),
  ('MLB', '', 'TEX', 'Texas Rangers', 'Texas', 'Texas', 'Rangers', 'baseball', '#003278', '#C0111F', '#FFFFFF', 3, 20),
  ('MLB', '', 'TB', 'Tampa Bay Rays', 'Tampa Bay', 'Tampa Bay', 'Rays', 'baseball', '#092C5C', '#8FBCE6', '#FFFFFF', 3, 21),
  ('MLB', '', 'BOS', 'Boston Red Sox', 'Boston', 'Boston', 'Red Sox', 'baseball', '#0D2B56', '#BD3039', '#FFFFFF', 3, 22),
  ('MLB', '', 'CIN', 'Cincinnati Reds', 'Cincinnati', 'Cincinnati', 'Reds', 'baseball', '#C6011F', '#FFFFFF', '#FFFFFF', 3, 23),
  ('MLB', '', 'COL', 'Colorado Rockies', 'Colorado', 'Colorado', 'Rockies', 'baseball', '#33006F', '#000000', '#FFFFFF', 3, 24),
  ('MLB', '', 'KC', 'Kansas City Royals', 'Kansas City', 'Kansas City', 'Royals', 'baseball', '#004687', '#7AB2DD', '#FFFFFF', 3, 25),
  ('MLB', '', 'DET', 'Detroit Tigers', 'Detroit', 'Detroit', 'Tigers', 'baseball', '#0A2240', '#FF4713', '#FFFFFF', 3, 26),
  ('MLB', '', 'MIN', 'Minnesota Twins', 'Minnesota', 'Minnesota', 'Twins', 'baseball', '#031F40', '#E20E32', '#FFFFFF', 3, 27),
  ('MLB', '', 'CHW', 'Chicago White Sox', 'Chicago', 'Chicago', 'White Sox', 'baseball', '#000000', '#C4CED4', '#FFFFFF', 3, 28),
  ('MLB', '', 'NYY', 'New York Yankees', 'New York', 'New York', 'Yankees', 'baseball', '#132448', '#C4CED4', '#FFFFFF', 3, 29)
on conflict (league, conference, code) do update set
  full_name   = excluded.full_name,
  first_name  = excluded.first_name,
  fanbase     = excluded.fanbase,
  mascot      = excluded.mascot,
  sport       = excluded.sport,
  shell       = excluded.shell,
  stripe      = excluded.stripe,
  mask        = excluded.mask,
  league_sort = excluded.league_sort,
  team_sort   = excluded.team_sort;
